// Per-crate category registry for the PHP-FPM panel (t42 §4b — the nested,
// intra-crate analogue of the top-level integrations registry).
//
// The panel shell (`PhpPanel.tsx`) renders its sub-tab bar and routes tab content
// from this array. Category executors (t42-php-c1/c2) DO NOT edit this file
// directly — the per-crate integrator appends their entry, exactly mirroring the
// disjoint-append discipline of the top-level category registries. The lead ships
// it EMPTY.

import type { ComponentType } from "react";

/** Props every PHP-FPM sub-tab receives from the shell. The shell owns the
 *  connection lifecycle and only mounts a tab once connected, so `connectionId`
 *  is always a live PHP connection id — pass it as the `id` arg to every `php_*`
 *  command the tab invokes. Most commands additionally take a `version` arg (the
 *  PHP version string); each tab manages its own version selection. */
export interface PhpTabProps {
  connectionId: string;
}

/** One command-category slice of the PHP-FPM surface (`runtime` = versions /
 *  FPM pools / process / opcache / sessions, `config` = php.ini / extensions /
 *  composer / logs). `label` may be an i18n key resolved at render time; a plain
 *  English string is the safe default. */
export interface PhpCategoryTab {
  /** Stable key, e.g. `"runtime"` / `"config"`. Used for the active-tab state. */
  categoryKey: string;
  /** Human label (or i18n key). */
  label: string;
  /** Lazy import of the tab module; the shell wraps it in Suspense. */
  importTab: () => Promise<{ default: ComponentType<PhpTabProps> }>;
}

/** Registered PHP-FPM sub-tabs. EMPTY at lead time; the per-crate integrator
 *  appends `{ categoryKey, label, importTab }` for each category exec
 *  (`runtime` = Runtime & FPM, `config` = Configuration, Extensions & Composer). */
export const phpCategoryTabs: PhpCategoryTab[] = [];
