//! Master DEK and per-artifact sub-key derivation.
//!
//! The master DEK is 32 random bytes generated by the OS RNG. It lives in
//! [`MasterDek`] — a wrapper that guarantees:
//!
//! 1. The key bytes are stored in [`Zeroizing`] memory and erased on drop.
//! 2. The struct is `!Sync` (forcing a single owner — typically the
//!    `Arc<RwLock<Option<MasterDek>>>` held by Tauri state).
//! 3. The plaintext bytes are never `Debug`-printed or serialized.
//!
//! Per-artifact sub-keys come from HKDF-SHA256 with a stable label.
//! Adding a new artifact means extending [`ArtifactKind`] and nothing
//! else — every consumer derives its own sub-key on demand from the
//! shared master, so rotating the master rotates everything.

use hkdf::Hkdf;
use rand::rngs::OsRng;
use rand::RngCore;
use sha2::Sha256;
use std::fmt;
use zeroize::Zeroizing;

/// Length of the master DEK and every sub-key, in bytes (AES-256).
pub const KEY_LEN: usize = 32;

/// Prefix included in every HKDF info label so this crate's labels are
/// distinct from any other HKDF usage in the workspace and from any
/// future revision of the labelling scheme. Validated by
/// `every_artifact_label_carries_the_prefix`.
#[cfg(test)]
const HKDF_INFO_PREFIX: &str = "sorng-v1::";

/// The closed set of artifacts that can derive a sub-key from the master.
///
/// **Stability:** the byte representation of [`Self::label`] is part of
/// the on-disk crypto. Renaming a variant breaks every encrypted file of
/// that artifact. To rotate, add a new variant and migrate; never rename.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ArtifactKind {
    /// `data.json` — the connections database. Already encrypted today
    /// via a password-derived key; Phase 0 leaves it untouched, Phase 1+
    /// re-keys it from the master.
    Connections,
    /// `settings.enc` — the full settings blob (Phase 1).
    Settings,
    /// `recording/**/*.json` — per-recording metadata (Phase 2).
    RecordingsMeta,
    /// `recording/recordings/*.{webm,mp4,gif}` — chunked AEAD streams
    /// (Phase 2). Sub-key is the *root* — each chunk uses a nonce =
    /// `chunk_index || 0`.
    RecordingsMedia,
    /// `backup/**` — backup outputs (Phase 3).
    Backups,
    /// `logs/*.log.enc` — opt-in encrypted logs (Phase 3).
    Logs,
    /// `macros/*.enc` — macros library (Phase 3).
    Macros,
    /// `databases/index.json` — the per-database metadata list (P4).
    /// Distinct from `Connections` so a per-DB payload swapped into
    /// the index slot fails authentication rather than decoding
    /// successfully under the wrong slot.
    DatabasesIndex,
}

impl ArtifactKind {
    /// The HKDF `info` label for this artifact. **On-disk-stable** —
    /// changing the returned string requires a migration.
    pub fn label(self) -> &'static str {
        match self {
            ArtifactKind::Connections => "sorng-v1::connections",
            ArtifactKind::Settings => "sorng-v1::settings",
            ArtifactKind::RecordingsMeta => "sorng-v1::recordings-meta",
            ArtifactKind::RecordingsMedia => "sorng-v1::recordings-media",
            ArtifactKind::Backups => "sorng-v1::backups",
            ArtifactKind::Logs => "sorng-v1::logs",
            ArtifactKind::Macros => "sorng-v1::macros",
            ArtifactKind::DatabasesIndex => "sorng-v1::databases-index",
        }
    }

    /// Every value of the enum — useful for "rotate all sub-keys"
    /// migrations and for the [`status`] command.
    pub fn all() -> &'static [ArtifactKind] {
        &[
            ArtifactKind::Connections,
            ArtifactKind::Settings,
            ArtifactKind::RecordingsMeta,
            ArtifactKind::RecordingsMedia,
            ArtifactKind::Backups,
            ArtifactKind::Logs,
            ArtifactKind::Macros,
            ArtifactKind::DatabasesIndex,
        ]
    }
}

/// A 32-byte sub-key derived from the master DEK. Returned by
/// [`MasterDek::sub_key`]. Zeroized on drop.
pub struct SubKey(Zeroizing<[u8; KEY_LEN]>);

impl SubKey {
    /// Borrow the raw key bytes. Callers should keep this borrow as
    /// short-lived as possible.
    pub fn bytes(&self) -> &[u8; KEY_LEN] {
        &self.0
    }
}

impl fmt::Debug for SubKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("SubKey(<redacted>)")
    }
}

/// The application's master DEK. Holds 32 random bytes in a
/// zeroize-on-drop wrapper and never serializes.
///
/// Construct via [`MasterDek::generate`] (fresh random) or
/// [`MasterDek::from_bytes`] (loaded from vault / unwrapped from a
/// password envelope).
pub struct MasterDek {
    bytes: Zeroizing<[u8; KEY_LEN]>,
}

impl MasterDek {
    /// Generate a fresh DEK from the OS RNG. Used at first-run setup
    /// (both vault and password-wrap modes) and on key rotation.
    pub fn generate() -> Self {
        let mut buf = Zeroizing::new([0u8; KEY_LEN]);
        OsRng.fill_bytes(buf.as_mut());
        Self { bytes: buf }
    }

    /// Reconstruct from raw bytes loaded out of the vault or an
    /// envelope decrypt. Returns `None` on the wrong length.
    pub fn from_bytes(b: &[u8]) -> Option<Self> {
        if b.len() != KEY_LEN {
            return None;
        }
        let mut buf = Zeroizing::new([0u8; KEY_LEN]);
        buf.copy_from_slice(b);
        Some(Self { bytes: buf })
    }

    /// Borrow the raw bytes for vault storage. Kept `pub(crate)` so
    /// only this crate's `state` module can wrap-and-write to the vault;
    /// downstream artifact writers must go through [`Self::sub_key`].
    /// Currently only consumed by tests; Phase 6's portable export
    /// will lift the `#[cfg(test)]`.
    #[cfg(test)]
    pub(crate) fn raw(&self) -> &[u8; KEY_LEN] {
        &self.bytes
    }

    /// Borrow the raw bytes specifically for password-wrap. Tightly
    /// scoped via name so grep finds exactly two call sites: the
    /// wrapper in [`crate::password_wrap::wrap`] and this definition.
    /// The borrow lives as long as the returned slice; callers must
    /// not stash it.
    pub(crate) fn bytes_for_password_wrap(&self) -> &[u8; KEY_LEN] {
        &self.bytes
    }

    /// Derive the sub-key for a given artifact via HKDF-SHA256.
    ///
    /// `Hkdf::new(salt = None, ikm = master)` — no salt because the
    /// master itself is already 32 random bytes from a CSPRNG; an extra
    /// salt would only weaken extract-then-expand here. The `info` arg
    /// carries the artifact label and is the only thing that
    /// differentiates two sub-keys.
    pub fn sub_key(&self, artifact: ArtifactKind) -> SubKey {
        let hk = Hkdf::<Sha256>::new(None, &self.bytes[..]);
        let mut out = Zeroizing::new([0u8; KEY_LEN]);
        // HKDF expand never fails for a 32-byte output at this OKM length.
        hk.expand(artifact.label().as_bytes(), out.as_mut())
            .expect("HKDF-SHA256 expand to 32 bytes is infallible");
        SubKey(out)
    }
}

impl fmt::Debug for MasterDek {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("MasterDek(<redacted>)")
    }
}

/// Compile-time assertion that the prefix is present in every label.
/// Caught by `cargo test`.
#[allow(dead_code)]
const _PREFIX_INVARIANT: () = {
    // We can't string-search `const fn`-style at compile time without
    // const generics, so the runtime equivalent lives in the tests.
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_yields_random_bytes() {
        let a = MasterDek::generate();
        let b = MasterDek::generate();
        assert_ne!(a.raw(), b.raw(), "two DEKs from OsRng must differ");
    }

    #[test]
    fn from_bytes_round_trip() {
        let dek = MasterDek::generate();
        let bytes = *dek.raw();
        let again = MasterDek::from_bytes(&bytes).expect("32 bytes is valid");
        assert_eq!(dek.raw(), again.raw());
    }

    #[test]
    fn from_bytes_rejects_wrong_length() {
        assert!(MasterDek::from_bytes(&[0u8; 31]).is_none());
        assert!(MasterDek::from_bytes(&[0u8; 33]).is_none());
        assert!(MasterDek::from_bytes(&[]).is_none());
    }

    #[test]
    fn sub_keys_are_deterministic_for_the_same_artifact() {
        let dek = MasterDek::generate();
        let k1 = dek.sub_key(ArtifactKind::Settings);
        let k2 = dek.sub_key(ArtifactKind::Settings);
        assert_eq!(k1.bytes(), k2.bytes());
    }

    #[test]
    fn sub_keys_differ_per_artifact() {
        let dek = MasterDek::generate();
        let s = dek.sub_key(ArtifactKind::Settings);
        let r = dek.sub_key(ArtifactKind::RecordingsMeta);
        assert_ne!(s.bytes(), r.bytes());
    }

    #[test]
    fn sub_keys_differ_across_masters() {
        let m1 = MasterDek::generate();
        let m2 = MasterDek::generate();
        assert_ne!(
            m1.sub_key(ArtifactKind::Settings).bytes(),
            m2.sub_key(ArtifactKind::Settings).bytes(),
        );
    }

    #[test]
    fn every_artifact_label_carries_the_prefix() {
        for a in ArtifactKind::all() {
            assert!(
                a.label().starts_with(HKDF_INFO_PREFIX),
                "{:?} label {:?} missing the {HKDF_INFO_PREFIX} prefix",
                a,
                a.label(),
            );
        }
    }

    #[test]
    fn artifact_labels_are_unique() {
        let mut seen = std::collections::HashSet::new();
        for a in ArtifactKind::all() {
            assert!(seen.insert(a.label()), "duplicate label: {}", a.label());
        }
    }

    #[test]
    fn debug_does_not_leak_key_bytes() {
        let dek = MasterDek::generate();
        let dbg = format!("{:?}", dek);
        assert_eq!(dbg, "MasterDek(<redacted>)");
        let sk = dek.sub_key(ArtifactKind::Settings);
        let dbg = format!("{:?}", sk);
        assert_eq!(dbg, "SubKey(<redacted>)");
    }
}
