import type { SettingSearchEntry } from "./types";

/**
 * Search index entries for the `about` settings tab.
 *
 * Every `key` must match a `settingKey` / `data-setting-key` rendered by that
 * tab's section components — `tests/settings/settingsSearchDrift.test.ts`
 * enforces the join in both directions.
 */
export const ABOUT_SEARCH_ENTRIES: SettingSearchEntry[] = [
  // ─── Overview ───────────────────────────────────────────────────
  {
    key: "about.summary",
    label: "Summary",
    description:
      "Application name, version, author, license, and core stack at a glance.",
    tags: [
      "about",
      "version",
      "author",
      "maintainer",
      "license",
      "mit",
      "stack",
      "build",
    ],
    values: [
      "Application",
      "sortOfRemoteNG",
      "Version",
      "Author",
      "Mariana Mota",
      "License",
      "MIT",
      "Core stack",
      "Tauri, Rust, React, Next.js",
    ],
    synonyms: ["app version", "what version", "who made this", "credits"],
    section: "about",
    sectionLabel: "About",
  },
  {
    key: "about.description",
    label: "Application Description",
    description:
      "Detailed overview of sortOfRemoteNG: protocol coverage, security posture, automation, and operations scope.",
    tags: [
      "about",
      "overview",
      "description",
      "remote",
      "manager",
      "workbench",
      "protocols",
      "automation",
      "operations",
    ],
    synonyms: ["what is this", "app overview", "feature summary"],
    section: "about",
    sectionLabel: "About",
  },
  {
    key: "about.license",
    label: "License & Warranty",
    description:
      "MIT license, copyright, warranty disclaimer, and third-party license acknowledgement.",
    tags: [
      "license",
      "warranty",
      "notice",
      "mit",
      "copyright",
      "third party",
      "dependencies",
      "legal",
    ],
    synonyms: ["open source license", "copyright", "legal notice", "eula"],
    section: "about",
    sectionLabel: "About",
  },

  // ─── Paths & permissions ────────────────────────────────────────
  {
    key: "about.data-locations",
    label: "Data Locations",
    description:
      "Where sortOfRemoteNG reads and writes data on disk, and the resolved app-data root on this machine.",
    tags: [
      "data",
      "location",
      "path",
      "disk",
      "appdata",
      "folder",
      "directory",
      "storage",
      "vault",
      "settings file",
    ],
    values: [
      "Frontend settings",
      "<APPDATA>/settings.json",
      "Encrypted vault",
      "<APPDATA>/storage.json",
      "Auth users store",
      "<APPDATA>/users.json",
      "Loader asset cache",
      "<APPDATA>/loading-elements/",
      "Browser IndexedDB",
      "mremote-keyval (browser IDB)",
      "User-chosen folders",
      "<DOWNLOAD> and dialog-picked paths",
    ],
    synonyms: [
      "where are my settings",
      "config file",
      "settings.json",
      "storage.json",
      "app data folder",
      "profile directory",
    ],
    section: "about",
    sectionLabel: "About",
  },
  {
    key: "about.permissions",
    label: "Granted Permissions",
    description:
      "Tauri capabilities the app declares. Filesystem access is scoped to the app data tree and the user's Downloads folder.",
    tags: [
      "permissions",
      "capabilities",
      "tauri",
      "security",
      "filesystem",
      "scope",
      "sandbox",
      "manifest",
    ],
    values: [
      "core:window:*",
      "core:event:*",
      "core:webview:*",
      "dialog:default",
      "fs:allow-read-file / fs:allow-write-file",
      "fs:allow-mkdir / fs:allow-exists",
    ],
    synonyms: [
      "what can the app access",
      "capability manifest",
      "default.json",
      "fs access",
    ],
    section: "about",
    sectionLabel: "About",
  },

  // ─── Credits ────────────────────────────────────────────────────
  {
    key: "about.project",
    label: "Project Authors & Maintainers",
    description:
      "Project authors, contributors, maintainers, and the upstream communities the app depends on.",
    tags: [
      "author",
      "authors",
      "contributors",
      "maintainers",
      "credits",
      "project",
      "upstream",
    ],
    values: [
      "sortOfRemoteNG",
      "Mariana Mota",
      "sortOfRemoteNG contributors",
      "Project contributors",
      "Open-source maintainers",
      "Upstream communities",
    ],
    synonyms: ["who wrote this", "credits", "acknowledgements"],
    section: "about",
    sectionLabel: "About",
  },
  {
    key: "about.frontend",
    label: "Frontend & Interface Libraries",
    description:
      "React, Next.js, TypeScript, Tailwind, xterm, and the other UI dependencies.",
    tags: [
      "libraries",
      "frontend",
      "react",
      "next",
      "typescript",
      "tailwind",
      "xterm",
      "ui",
      "interface",
    ],
    synonyms: ["nextjs", "next.js", "tailwindcss", "lucide", "i18next"],
    section: "about",
    sectionLabel: "About",
  },
  {
    key: "about.desktop-runtime",
    label: "Desktop Runtime",
    description: "Tauri, Rust, WebView2, Cargo, and the desktop runtime stack.",
    tags: [
      "tauri",
      "rust",
      "webview",
      "webview2",
      "desktop",
      "cargo",
      "runtime",
      "native",
    ],
    synonyms: ["electron alternative", "wry", "tao", "webkitgtk"],
    section: "about",
    sectionLabel: "About",
  },
  {
    key: "about.backend",
    label: "Rust Backend Libraries",
    description:
      "Tokio, Serde, Axum, Reqwest, tracing, and the other backend crates.",
    tags: [
      "rust",
      "tokio",
      "serde",
      "axum",
      "reqwest",
      "backend",
      "crates",
      "async",
      "tracing",
    ],
    synonyms: ["crates.io", "cargo dependencies", "async runtime"],
    section: "about",
    sectionLabel: "About",
  },
  {
    key: "about.protocols",
    label: "Protocol Libraries",
    description:
      "SSH, RDP, VNC, FTP, SQL, Kafka, cloud, and infrastructure integrations.",
    tags: [
      "protocol",
      "ssh",
      "rdp",
      "vnc",
      "ftp",
      "sftp",
      "database",
      "sql",
      "kafka",
      "cloud",
      "infrastructure",
    ],
    synonyms: ["russh", "ironrdp", "protocol stack", "drivers"],
    section: "about",
    sectionLabel: "About",
  },
  {
    key: "about.security",
    label: "Security Libraries",
    description:
      "TLS, cryptography, TOTP, OAuth, FIDO2, and certificate tooling.",
    tags: [
      "security",
      "crypto",
      "cryptography",
      "tls",
      "rustls",
      "totp",
      "oauth",
      "fido2",
      "certificate",
    ],
    synonyms: ["webauthn", "argon2", "ring", "openssl", "2fa"],
    section: "about",
    sectionLabel: "About",
  },
  {
    key: "about.tooling",
    label: "Build & Test Tooling",
    description:
      "Vite, Vitest, Testing Library, ESLint, WebdriverIO, Docker, and cargo-chef.",
    tags: [
      "build",
      "test",
      "tooling",
      "vite",
      "vitest",
      "eslint",
      "webdriverio",
      "docker",
      "prettier",
      "ci",
    ],
    synonyms: ["wdio", "cargo-chef", "test runner", "linter"],
    section: "about",
    sectionLabel: "About",
  },
];
