import type { SettingSearchEntry } from "./types";

/**
 * Search index entries for the `advanced` settings tab.
 *
 * Every `key` must match a `settingKey` / `data-setting-key` rendered by that
 * tab's section components — `tests/settings/settingsSearchDrift.test.ts`
 * enforces the join in both directions.
 */
export const ADVANCED_SEARCH_ENTRIES: SettingSearchEntry[] = [
  // ─── Logging ────────────────────────────────────────────────────
  {
    key: "logLevel",
    label: "Log Level",
    description:
      "Minimum severity of log messages to record. Debug captures everything; Error captures only failures.",
    tags: [
      "log",
      "logging",
      "level",
      "severity",
      "debug",
      "verbose",
      "trace",
      "troubleshoot",
    ],
    // `LOG_LEVEL_CONFIG` in AdvancedSettings.tsx — both halves of every option.
    values: [
      "debug",
      "Debug",
      "All messages including debug info",
      "info",
      "Info",
      "Informational messages and above",
      "warn",
      "Warning",
      "Warnings and errors only",
      "error",
      "Error",
      "Errors only",
    ],
    synonyms: ["log verbosity", "loglevel", "warn", "error level"],
    section: "advanced",
    sectionLabel: "Advanced",
  },

  // ─── Memory Watchdog ────────────────────────────────────────────
  {
    key: "memoryWatchdog.enabled",
    label: "Enable memory watchdog",
    description:
      "Monitor JS heap and system RAM and alert when pressure thresholds are exceeded. When disabled, no memory monitoring or proactive pressure alert runs.",
    tags: [
      "memory",
      "watchdog",
      "heap",
      "ram",
      "monitor",
      "leak",
      "pressure",
      "alert",
    ],
    synonyms: ["out of memory", "oom", "memory leak", "js heap"],
    section: "advanced",
    sectionLabel: "Advanced",
  },
  {
    key: "memoryWatchdog.intervalMs",
    label: "Poll Interval",
    description:
      "How often the watchdog checks memory usage. Lower values detect leaks faster but use slightly more CPU.",
    tags: [
      "memory",
      "watchdog",
      "poll",
      "interval",
      "milliseconds",
      "ms",
      "sample",
      "cpu",
    ],
    synonyms: ["memory poll", "check interval", "sampling rate"],
    section: "advanced",
    sectionLabel: "Advanced",
  },
  {
    key: "memoryWatchdog.heapWarningMb",
    label: "Main heap — Warning",
    description:
      "Main-window JS heap usage that triggers a warning log, in megabytes.",
    tags: [
      "memory",
      "heap",
      "ram",
      "warning",
      "threshold",
      "mb",
      "megabytes",
      "main window",
      "limit",
    ],
    synonyms: ["heap warning", "memory warning", "js heap limit"],
    section: "advanced",
    sectionLabel: "Advanced",
  },
  {
    key: "memoryWatchdog.heapCriticalMb",
    label: "Main heap — Critical",
    description:
      "Main-window JS heap usage that surfaces an in-app overlay, in megabytes.",
    tags: [
      "memory",
      "heap",
      "ram",
      "critical",
      "threshold",
      "mb",
      "megabytes",
      "overlay",
      "main window",
      "limit",
    ],
    synonyms: ["heap critical", "memory critical", "critical threshold"],
    section: "advanced",
    sectionLabel: "Advanced",
  },
  {
    key: "memoryWatchdog.heapKillMb",
    label: "Main heap — Pressure",
    description:
      "Main-window JS heap usage that raises the highest-severity alert, in megabytes. Active connections remain running.",
    tags: [
      "memory",
      "heap",
      "ram",
      "pressure",
      "threshold",
      "mb",
      "megabytes",
      "severity",
      "main window",
      "limit",
    ],
    synonyms: ["heap pressure", "kill threshold", "memory pressure", "oom"],
    section: "advanced",
    sectionLabel: "Advanced",
  },
  {
    key: "memoryWatchdog.detached.heapWarningMb",
    label: "Detached heap — Warning",
    description:
      "Detached-window JS heap warning threshold in megabytes (usually lower than the main window).",
    tags: [
      "memory",
      "heap",
      "ram",
      "detached",
      "warning",
      "threshold",
      "mb",
      "window",
      "popout",
    ],
    synonyms: ["popped out window", "detached window memory", "torn off tab"],
    section: "advanced",
    sectionLabel: "Advanced",
  },
  {
    key: "memoryWatchdog.detached.heapCriticalMb",
    label: "Detached heap — Critical",
    description: "Detached-window JS heap critical threshold in megabytes.",
    tags: [
      "memory",
      "heap",
      "ram",
      "detached",
      "critical",
      "threshold",
      "mb",
      "window",
      "popout",
    ],
    synonyms: ["popped out window", "detached window memory"],
    section: "advanced",
    sectionLabel: "Advanced",
  },
  {
    key: "memoryWatchdog.detached.heapKillMb",
    label: "Detached heap — Pressure",
    description:
      "Detached-window JS heap usage that raises the highest-severity alert without closing the window.",
    tags: [
      "memory",
      "heap",
      "ram",
      "detached",
      "pressure",
      "threshold",
      "mb",
      "window",
      "popout",
    ],
    synonyms: ["popped out window", "detached window memory", "oom"],
    section: "advanced",
    sectionLabel: "Advanced",
  },
  {
    key: "memoryWatchdog.systemWarningPct",
    label: "System RAM — Warning",
    description:
      "OS-level physical RAM usage percentage that triggers a warning log.",
    tags: [
      "memory",
      "ram",
      "system",
      "physical",
      "warning",
      "percent",
      "threshold",
      "os",
    ],
    synonyms: ["system memory", "physical memory", "ram usage"],
    section: "advanced",
    sectionLabel: "Advanced",
  },
  {
    key: "memoryWatchdog.systemKillPct",
    label: "System RAM — Pressure",
    description:
      "OS-level physical RAM usage percentage that raises the highest-severity alert. The watchdog never closes sessions automatically.",
    tags: [
      "memory",
      "ram",
      "system",
      "physical",
      "pressure",
      "percent",
      "threshold",
      "os",
    ],
    synonyms: ["system memory", "physical memory", "ram pressure", "oom"],
    section: "advanced",
    sectionLabel: "Advanced",
  },

  // ─── Connection maintenance ─────────────────────────────────────
  {
    key: "protocolRepair",
    label: "Repair mis-typed connections",
    labelKey: "protocolRepair.cardTitle",
    description:
      "Finds connections typed RDP whose port or address points at a web server (e.g. 443, https://) and lets you switch them to HTTP/HTTPS. Nothing is changed automatically.",
    descriptionKey: "protocolRepair.cardDescription",
    tags: [
      "repair",
      "fix",
      "protocol",
      "rdp",
      "https",
      "http",
      "import",
      "maintenance",
      "mremoteng",
      "443",
      "wrong protocol",
    ],
    synonyms: [
      "connection maintenance",
      "mis-typed",
      "wrong type",
      "imported connections",
    ],
    section: "advanced",
    sectionLabel: "Advanced",
  },
];
