import type { SettingSearchEntry } from "./types";

/**
 * Search index entries for the `ai` settings tab.
 *
 * Every `key` must match a `settingKey` / `data-setting-key` rendered by that
 * tab's section components — `tests/settings/settingsSearchDrift.test.ts`
 * enforces the join in both directions.
 *
 * The tab renders raw `<input>` / `<select>` / `<textarea>` controls rather than
 * the settings primitives, so the anchors in `sections/AiSettings.tsx` are raw
 * `data-setting-key` attributes (plan §4.5 — anchor, do not convert).
 *
 * `PROVIDER_TYPES` and `BALANCER_STRATEGIES` (`src/types/llm.ts`) are imported
 * constants, so the drift guard cannot read them; their option text is mirrored
 * into `values` here by hand and asserted by
 * `tests/settings/settingsSearch.apiAiMcp.test.ts`.
 */
export const AI_SEARCH_ENTRIES: SettingSearchEntry[] = [
  // ─── Providers ──────────────────────────────────────────────────
  {
    key: "llm.provider.type",
    label: "Provider",
    labelKey: "integrations.llm.providerType",
    description:
      "Which LLM vendor this provider talks to. Selecting one prefills its default base URL.",
    tags: [
      "ai",
      "llm",
      "provider",
      "vendor",
      "model",
      "backend",
      "gpt",
      "claude",
      "gemini",
      "chatgpt",
      "inference",
    ],
    synonyms: ["provider type", "llm provider", "ai provider", "api provider"],
    values: [
      "open_ai",
      "OpenAI",
      "anthropic",
      "Anthropic",
      "google",
      "Google Gemini",
      "ollama",
      "Ollama",
      "azure_open_ai",
      "Azure OpenAI",
      "groq",
      "Groq",
      "mistral",
      "Mistral AI",
      "cohere",
      "Cohere",
      "deep_seek",
      "DeepSeek",
      "together",
      "Together AI",
      "fireworks",
      "Fireworks AI",
      "perplexity",
      "Perplexity",
      "hugging_face",
      "Hugging Face",
      "aws_bedrock",
      "AWS Bedrock",
      "open_router",
      "OpenRouter",
      "local",
      "Local (GGUF)",
      "custom",
      "Custom",
    ],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.provider.displayName",
    label: "Display name",
    labelKey: "integrations.llm.displayName",
    description:
      "Friendly name shown for this provider in the provider list and router logs.",
    tags: ["ai", "llm", "provider", "name", "label", "alias", "title"],
    synonyms: ["display name", "provider name", "friendly name"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.provider.apiKey",
    label: "API key",
    labelKey: "integrations.llm.apiKey",
    description:
      "Secret credential for this provider. Stored in the encrypted credential vault, never written to settings JSON.",
    tags: [
      "ai",
      "llm",
      "api key",
      "key",
      "secret",
      "token",
      "credential",
      "vault",
      "bearer",
      "openai",
      "anthropic",
      "authentication",
    ],
    synonyms: ["apikey", "secret key", "access token", "sk-"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.provider.baseUrl",
    label: "Base URL",
    labelKey: "integrations.llm.baseUrl",
    description:
      "Endpoint the provider's requests are sent to. Prefilled from the provider type; override it for proxies, gateways or self-hosted servers.",
    tags: [
      "ai",
      "llm",
      "base url",
      "url",
      "endpoint",
      "host",
      "gateway",
      "proxy",
      "self hosted",
      "ollama",
      "localhost",
    ],
    synonyms: ["baseurl", "api url", "api endpoint", "server url"],
    values: [
      "https://api.openai.com/v1",
      "https://api.anthropic.com/v1",
      "http://localhost:11434",
    ],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.provider.defaultModel",
    label: "Default model",
    labelKey: "integrations.llm.defaultModel",
    description:
      "Model this provider uses when a request does not name one explicitly.",
    tags: [
      "ai",
      "llm",
      "model",
      "default",
      "gpt",
      "claude",
      "gemini",
      "completion",
    ],
    synonyms: ["default model", "fallback model", "model name"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.provider.region",
    label: "Region",
    labelKey: "integrations.llm.region",
    description:
      "AWS region for a Bedrock provider, for example us-east-1. Shown only for AWS Bedrock.",
    tags: [
      "ai",
      "llm",
      "region",
      "aws",
      "bedrock",
      "zone",
      "datacenter",
      "location",
    ],
    synonyms: ["aws region", "bedrock region"],
    values: ["us-east-1"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.provider.orgId",
    label: "Organization ID",
    labelKey: "integrations.llm.orgId",
    description:
      "OpenAI or Azure OpenAI organization the requests are billed to. Shown only for those providers.",
    tags: [
      "ai",
      "llm",
      "organization",
      "org",
      "openai",
      "azure",
      "billing",
      "tenant",
      "account",
    ],
    synonyms: ["org id", "organisation id", "openai organization"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.provider.priority",
    label: "Priority",
    labelKey: "integrations.llm.priority",
    description:
      "Ordering weight used by the priority balancer strategy. Higher-priority providers are tried first.",
    tags: [
      "ai",
      "llm",
      "priority",
      "order",
      "weight",
      "rank",
      "balancer",
      "failover",
    ],
    synonyms: ["provider priority", "ordering", "preference"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.provider.timeoutSeconds",
    label: "Timeout (seconds)",
    labelKey: "integrations.llm.timeout",
    description:
      "How long to wait for this provider to answer before the request fails. Defaults to 120 seconds.",
    tags: ["ai", "llm", "timeout", "seconds", "deadline", "latency", "abort"],
    synonyms: ["request timeout", "response timeout", "time limit"],
    values: ["120"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.provider.maxRetries",
    label: "Max retries",
    labelKey: "integrations.llm.maxRetries",
    description:
      "How many times a failed request to this provider is retried before the router gives up. Defaults to 3.",
    tags: ["ai", "llm", "retries", "retry", "attempts", "backoff", "failure"],
    synonyms: ["max retries", "retry count", "retry limit"],
    values: ["3"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.provider.enabled",
    label: "Enabled",
    labelKey: "integrations.llm.enabled",
    description:
      "Whether the router may route requests to this provider. Disabled providers stay configured but are skipped.",
    tags: ["ai", "llm", "enabled", "disabled", "active", "provider", "toggle"],
    synonyms: ["enable provider", "disable provider", "provider enabled"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },

  // ─── Router & load balancing ────────────────────────────────────
  {
    key: "llm.router.balancerStrategy",
    label: "Balancer strategy",
    labelKey: "integrations.llm.balancerStrategy",
    description:
      "How the router picks a provider for each request: by priority, round robin, least latency, least cost, random or weighted random.",
    tags: [
      "ai",
      "llm",
      "balancer",
      "load balancing",
      "strategy",
      "routing",
      "router",
      "distribution",
      "failover",
      "latency",
      "cost",
    ],
    synonyms: [
      "load balancer",
      "balancing strategy",
      "routing strategy",
      "load balancing strategy",
    ],
    values: [
      "priority",
      "Priority",
      "round_robin",
      "Round robin",
      "least_latency",
      "Least latency",
      "least_cost",
      "Least cost",
      "random",
      "Random",
      "weighted_random",
      "Weighted random",
    ],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.router.defaultModel",
    label: "Default model",
    labelKey: "integrations.llm.defaultModel",
    description:
      "Model the router falls back to when a request does not name one and no provider default applies.",
    tags: [
      "ai",
      "llm",
      "model",
      "default",
      "router",
      "fallback",
      "gpt",
      "claude",
    ],
    synonyms: ["router default model", "global default model"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.router.failoverEnabled",
    label: "Failover enabled",
    labelKey: "integrations.llm.failover",
    description:
      "Retry a failed request against the next healthy provider instead of returning the error.",
    tags: [
      "ai",
      "llm",
      "failover",
      "fallback",
      "resilience",
      "retry",
      "high availability",
      "router",
      "balancer",
    ],
    synonyms: ["fail over", "automatic failover", "ha"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.router.stickySessions",
    label: "Sticky sessions",
    labelKey: "integrations.llm.stickySessions",
    description:
      "Keep one conversation pinned to the provider that served its first request.",
    tags: [
      "ai",
      "llm",
      "sticky",
      "session",
      "affinity",
      "pinning",
      "router",
      "balancer",
      "conversation",
    ],
    synonyms: ["session affinity", "sticky routing", "session pinning"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.router.usageTracking",
    label: "Usage tracking",
    labelKey: "integrations.llm.usageTracking",
    description:
      "Record per-request token counts and cost so the usage summary and cost reports have data.",
    tags: [
      "ai",
      "llm",
      "usage",
      "tracking",
      "telemetry",
      "cost",
      "spend",
      "tokens",
      "billing",
      "statistics",
      "metrics",
    ],
    synonyms: ["track usage", "cost tracking", "token accounting"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },

  // ─── Response cache ─────────────────────────────────────────────
  {
    key: "llm.cache.enabled",
    label: "Cache enabled",
    labelKey: "integrations.llm.cacheEnabled",
    description:
      "Serve an identical repeated request from the response cache instead of calling the provider again.",
    tags: [
      "ai",
      "llm",
      "cache",
      "caching",
      "response cache",
      "memoize",
      "cost",
      "latency",
      "performance",
    ],
    synonyms: ["enable cache", "response caching", "prompt cache"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.cache.embeddings",
    label: "Cache embeddings",
    labelKey: "integrations.llm.cacheEmbeddings",
    description:
      "Also cache embedding vectors, not just chat completions. Embeddings are large but highly repeatable.",
    tags: [
      "ai",
      "llm",
      "cache",
      "embeddings",
      "embedding",
      "vector",
      "rag",
      "similarity",
      "performance",
    ],
    synonyms: ["embedding cache", "vector cache"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.cache.ttlSeconds",
    label: "TTL (seconds)",
    labelKey: "integrations.llm.cacheTtl",
    description:
      "How long a cached response stays valid before it is discarded and the provider is called again.",
    tags: [
      "ai",
      "llm",
      "cache",
      "ttl",
      "expiry",
      "expiration",
      "seconds",
      "lifetime",
      "invalidation",
    ],
    synonyms: ["time to live", "cache ttl", "cache expiry"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },

  // ─── Model catalog ──────────────────────────────────────────────
  {
    key: "llm.models.providerFilter",
    label: "Provider (id)",
    labelKey: "integrations.llm.providerFilter",
    description:
      "Restrict the model catalog listing to a single provider id, for example openai.",
    tags: [
      "ai",
      "llm",
      "models",
      "catalog",
      "filter",
      "provider",
      "list",
      "search",
    ],
    synonyms: ["provider filter", "filter by provider", "provider id"],
    values: ["openai"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.models.modelId",
    label: "Model",
    labelKey: "integrations.llm.modelId",
    description:
      "Model id to look up in the catalog — returns its context window and input/output cost per million tokens.",
    tags: [
      "ai",
      "llm",
      "model",
      "catalog",
      "lookup",
      "context window",
      "cost",
      "pricing",
      "tokens",
      "details",
    ],
    synonyms: ["model id", "model info", "model details"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },

  // ─── Usage & cache ──────────────────────────────────────────────
  {
    key: "llm.usage.windowDays",
    label: "Window (days)",
    labelKey: "integrations.llm.days",
    description:
      "How many days of history the usage summary covers. Defaults to the last 30 days.",
    tags: [
      "ai",
      "llm",
      "usage",
      "days",
      "window",
      "history",
      "period",
      "cost",
      "spend",
      "report",
      "summary",
    ],
    synonyms: ["time window", "usage window", "reporting period"],
    values: ["30"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },

  // ─── Playground ─────────────────────────────────────────────────
  {
    key: "llm.playground.model",
    label: "Model",
    labelKey: "integrations.llm.modelId",
    description:
      "Model the playground sends its chat, embedding and token-estimate requests to.",
    tags: [
      "ai",
      "llm",
      "playground",
      "model",
      "test",
      "chat",
      "completion",
      "embedding",
    ],
    synonyms: ["playground model", "test model"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.playground.providerOverride",
    label: "Provider (optional)",
    labelKey: "integrations.llm.providerOverride",
    description:
      "Force the playground request at one provider instead of letting the balancer choose.",
    tags: [
      "ai",
      "llm",
      "playground",
      "provider",
      "override",
      "route",
      "test",
      "pin",
    ],
    synonyms: ["provider override", "force provider", "pin provider"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.playground.prompt",
    label: "Chat completion",
    labelKey: "integrations.llm.chatTest",
    description:
      "Prompt sent as a single user message to test that a provider and model actually answer.",
    tags: [
      "ai",
      "llm",
      "playground",
      "prompt",
      "chat",
      "completion",
      "message",
      "test",
      "try",
      "send",
    ],
    synonyms: ["chat test", "test prompt", "chat completion"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.playground.embedInput",
    label: "Embeddings (one per line)",
    labelKey: "integrations.llm.embedTest",
    description:
      "Input lines to embed. Each line becomes one vector; the result shows the count, dimensions and the head of the first vector.",
    tags: [
      "ai",
      "llm",
      "playground",
      "embeddings",
      "embedding",
      "vector",
      "dimensions",
      "rag",
      "test",
    ],
    synonyms: ["embedding test", "embed input", "vector test"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
  {
    key: "llm.playground.tokenText",
    label: "Estimate tokens",
    labelKey: "integrations.llm.tokenEstimate",
    description:
      "Text to run through the tokenizer to estimate how many tokens it costs before sending it.",
    tags: [
      "ai",
      "llm",
      "playground",
      "tokens",
      "token",
      "estimate",
      "count",
      "tokenizer",
      "cost",
      "context",
    ],
    synonyms: ["token estimate", "token count", "count tokens"],
    section: "ai",
    sectionLabel: "AI / LLM Router",
  },
];
