import type { SettingSearchEntry } from "./types";

/**
 * Search index entries for the `api` settings tab.
 *
 * Every `key` must match a `settingKey` / `data-setting-key` rendered by that
 * tab's section components — `tests/settings/settingsSearchDrift.test.ts`
 * enforces the join in both directions.
 */
export const API_SEARCH_ENTRIES: SettingSearchEntry[] = [
  // ─── Enable ─────────────────────────────────────────────────────
  {
    key: "restApi.enabled",
    label: "Enable API server",
    labelKey: "settings.api.enable",
    description:
      "Start an HTTP server that lets external applications control this app remotely over the REST API.",
    descriptionKey: "settings.api.enableDescription",
    tags: [
      "api",
      "rest",
      "rest api",
      "http",
      "server",
      "remote control",
      "automation",
      "integration",
      "webhook",
      "endpoint",
    ],
    synonyms: ["restful", "web api", "http api"],
    section: "api",
    sectionLabel: "API Server",
  },
  {
    key: "restApi.startOnLaunch",
    label: "Start on application launch",
    labelKey: "settings.api.startOnLaunch",
    description:
      "Automatically start the API server when the application opens, without manual activation.",
    descriptionKey: "settings.api.startOnLaunchDescription",
    tags: ["api", "rest", "startup", "autostart", "launch", "boot", "server"],
    synonyms: ["auto start", "start automatically", "on boot"],
    section: "api",
    sectionLabel: "API Server",
  },

  // ─── Network ────────────────────────────────────────────────────
  {
    key: "restApi.port",
    label: "Port",
    labelKey: "settings.api.port",
    description:
      "TCP port the API server listens on (1-65535). Choose a port no other service uses. Defaults to 9876.",
    tags: [
      "api",
      "rest",
      "port",
      "tcp",
      "network",
      "listen",
      "9876",
      "api port",
    ],
    synonyms: ["port number", "listening port", "bind port"],
    values: ["9876", "1", "65535"],
    section: "api",
    sectionLabel: "API Server",
  },
  {
    key: "restApi.useRandomPort",
    label: "Use random port on each start",
    labelKey: "settings.api.useRandomPort",
    description:
      "Assign a random available port each time the API server starts instead of using a fixed port.",
    tags: ["api", "rest", "port", "random", "ephemeral", "dynamic", "network"],
    synonyms: ["randomize port", "random port", "dynamic port"],
    section: "api",
    sectionLabel: "API Server",
  },
  {
    key: "restApi.allowRemoteConnections",
    label: "Allow remote connections",
    labelKey: "settings.api.allowRemote",
    description:
      "Listen on all network interfaces instead of localhost only. This exposes the API to other machines on your network, so authentication is enforced.",
    tags: [
      "api",
      "rest",
      "remote",
      "network",
      "bind",
      "interface",
      "localhost",
      "loopback",
      "0.0.0.0",
      "lan",
      "expose",
      "security",
    ],
    synonyms: [
      "remote access",
      "external access",
      "bind address",
      "listen address",
      "all interfaces",
    ],
    section: "api",
    sectionLabel: "API Server",
  },

  // ─── Authentication ─────────────────────────────────────────────
  {
    key: "restApi.authentication",
    label: "Require Authentication",
    labelKey: "settings.api.requireAuth",
    description:
      "Release builds always require a valid API key or JWT. Unauthenticated loopback is available only to debug builds through an explicit process environment override.",
    descriptionKey: "settings.api.requireAuthProductionDescription",
    tags: [
      "api",
      "rest",
      "auth",
      "authentication",
      "security",
      "jwt",
      "token",
      "bearer",
      "credentials",
      "login",
      "unauthorized",
      "401",
    ],
    synonyms: [
      "require auth",
      "bearer token",
      "access token",
      "json web token",
      "authorization header",
    ],
    section: "api",
    sectionLabel: "API Server",
  },
  {
    key: "restApi.apiKey",
    label: "API Key",
    labelKey: "settings.api.apiKey",
    description:
      "Secret key clients send to authenticate API requests. Stored in the OS credential vault, never in settings; copying it requires native biometric reauthentication.",
    descriptionKey: "settings.api.apiKeyDescription",
    tags: [
      "api",
      "rest",
      "api key",
      "key",
      "token",
      "bearer",
      "secret",
      "credential",
      "vault",
      "keychain",
      "auth",
      "regenerate",
      "biometric",
    ],
    synonyms: [
      "bearer token",
      "access token",
      "apikey",
      "secret key",
      "authorization header",
    ],
    section: "api",
    sectionLabel: "API Server",
  },

  // ─── SSL / TLS ──────────────────────────────────────────────────
  {
    key: "restApi.sslEnabled",
    label: "Enable HTTPS",
    labelKey: "settings.api.enableSsl",
    description:
      "Encrypt all API traffic with SSL/TLS. Required for secure communication, especially over public networks.",
    descriptionKey: "settings.api.enableSslDescription",
    tags: [
      "api",
      "rest",
      "ssl",
      "tls",
      "https",
      "encryption",
      "certificate",
      "secure",
      "transport",
    ],
    synonyms: ["ssl/tls", "secure http", "http over tls"],
    section: "api",
    sectionLabel: "API Server",
  },
  {
    key: "restApi.sslMode",
    label: "Certificate Mode",
    labelKey: "settings.api.sslMode",
    description:
      "How the SSL certificate is obtained: provide your own, auto-generate a self-signed one, or use Let's Encrypt.",
    tags: [
      "api",
      "rest",
      "ssl",
      "tls",
      "https",
      "certificate",
      "cert",
      "acme",
      "ca",
      "pki",
    ],
    synonyms: ["cert mode", "certificate source", "certificate type"],
    values: [
      "manual",
      "Manual (Provide Certificate)",
      "self-signed",
      "Auto-Generate Self-Signed",
      "letsencrypt",
      "Let's Encrypt (Auto-Renew)",
    ],
    section: "api",
    sectionLabel: "API Server",
  },
  {
    key: "restApi.sslCertPath",
    label: "Certificate Path",
    labelKey: "settings.api.certPath",
    description:
      "File path to the PEM-encoded SSL certificate the API server presents to clients.",
    tags: [
      "api",
      "rest",
      "ssl",
      "tls",
      "certificate",
      "cert",
      "pem",
      "path",
      "file",
      "crt",
      "chain",
    ],
    synonyms: ["cert path", "certificate file", "public certificate"],
    section: "api",
    sectionLabel: "API Server",
  },
  {
    key: "restApi.sslKeyPath",
    label: "Private Key Path",
    labelKey: "settings.api.keyPath",
    description:
      "File path to the PEM-encoded private key that matches the SSL certificate.",
    tags: [
      "api",
      "rest",
      "ssl",
      "tls",
      "private key",
      "key",
      "pem",
      "path",
      "file",
      "certificate",
    ],
    synonyms: ["key file", "key path", "private key file"],
    section: "api",
    sectionLabel: "API Server",
  },
  {
    key: "restApi.sslDomain",
    label: "Domain Name",
    labelKey: "settings.api.sslDomain",
    description:
      "Public domain name pointing at this server. Required for Let's Encrypt certificate issuance.",
    descriptionKey: "settings.api.sslDomainDescription",
    tags: [
      "api",
      "rest",
      "ssl",
      "tls",
      "domain",
      "hostname",
      "dns",
      "fqdn",
      "letsencrypt",
      "acme",
      "certificate",
    ],
    synonyms: ["let's encrypt domain", "domain name", "host name"],
    section: "api",
    sectionLabel: "API Server",
  },
  {
    key: "restApi.sslEmail",
    label: "Email for Certificate Notices",
    labelKey: "settings.api.sslEmail",
    description:
      "Address where Let's Encrypt sends certificate expiration and renewal reminders.",
    descriptionKey: "settings.api.sslEmailDescription",
    tags: [
      "api",
      "rest",
      "ssl",
      "tls",
      "email",
      "letsencrypt",
      "acme",
      "renewal",
      "expiry",
      "notification",
      "certificate",
    ],
    synonyms: ["let's encrypt email", "contact email", "renewal reminder"],
    section: "api",
    sectionLabel: "API Server",
  },

  // ─── Performance ────────────────────────────────────────────────
  {
    key: "restApi.maxThreads",
    label: "Max Worker Threads",
    labelKey: "settings.api.maxThreads",
    description:
      "Worker threads allocated to handle API requests concurrently. More threads improve throughput under load. 1-64.",
    tags: [
      "api",
      "rest",
      "threads",
      "workers",
      "concurrency",
      "parallel",
      "performance",
      "throughput",
      "cpu",
    ],
    synonyms: ["worker threads", "thread pool", "max threads"],
    values: ["1", "4", "64"],
    section: "api",
    sectionLabel: "API Server",
  },
  {
    key: "restApi.requestTimeout",
    label: "Request Timeout",
    labelKey: "settings.api.requestTimeout",
    description:
      "Maximum seconds to wait for a single API request to complete before aborting it. 1-300 seconds.",
    tags: [
      "api",
      "rest",
      "timeout",
      "seconds",
      "request",
      "abort",
      "deadline",
      "performance",
    ],
    synonyms: ["request timeout", "read timeout", "time limit"],
    values: ["1", "30", "300"],
    section: "api",
    sectionLabel: "API Server",
  },

  // ─── Rate limiting ──────────────────────────────────────────────
  {
    key: "restApi.rateLimiting",
    label: "Enable rate limiting",
    labelKey: "settings.api.enableRateLimiting",
    description:
      "Applies to local debug use only. Remote listeners and release builds always enforce a safe non-zero limit.",
    descriptionKey: "settings.api.rateLimitingDescription",
    tags: [
      "api",
      "rest",
      "rate limit",
      "rate limiting",
      "throttle",
      "throttling",
      "quota",
      "abuse",
      "429",
    ],
    synonyms: ["ratelimit", "request throttling", "too many requests"],
    section: "api",
    sectionLabel: "API Server",
  },
  {
    key: "restApi.maxRequestsPerMinute",
    label: "Max Requests Per Minute",
    labelKey: "settings.api.maxRequests",
    description:
      "Maximum requests per minute from one client. 0 disables the limit for local debug use only; remote listeners and release builds substitute the mandatory fallback of 120.",
    tags: [
      "api",
      "rest",
      "rate limit",
      "rate limiting",
      "throttle",
      "requests",
      "per minute",
      "rpm",
      "quota",
      "429",
    ],
    synonyms: ["requests per minute", "max requests", "request quota"],
    values: ["0", "60", "120", "10000"],
    section: "api",
    sectionLabel: "API Server",
  },
];
