import type { SettingSearchEntry } from "./types";

/**
 * Search index entries for the `behavior` settings tab.
 *
 * Every `key` must match a `settingKey` / `data-setting-key` rendered by that
 * tab's section components — `tests/settings/settingsSearchDrift.test.ts`
 * enforces the join in both directions.
 */
export const BEHAVIOR_SEARCH_ENTRIES: SettingSearchEntry[] = [
  // ─── Behavior ───────────────────────────────────────────────────
  {
    key: "singleClickConnect",
    label: "Single Click Connect",
    description: "Connect on single click",
    tags: ["click", "one click", "mouse"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "singleClickDisconnect",
    label: "Single Click Disconnect",
    description: "Disconnect on single click",
    tags: ["click", "disconnect"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "doubleClickRename",
    label: "Double Click Rename",
    description: "Rename connection on double click",
    tags: ["rename", "double click", "edit name"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "singleWindowMode",
    label: "Single Window Mode",
    description: "Only allow one application window",
    tags: ["window", "single instance"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "singleConnectionMode",
    label: "Single Connection Mode",
    description: "Only one active connection at a time",
    tags: ["connection", "exclusive"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "reconnectOnReload",
    label: "Reconnect on Reload",
    description: "Restore connections after reload",
    tags: ["reconnect", "restore", "refresh"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "enableAutocomplete",
    label: "Autocomplete",
    description: "Enable input autocomplete",
    tags: ["auto complete", "suggestions"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "doubleClickConnect",
    label: "Double Click Connect",
    description: "Connect on double click",
    tags: ["double click", "open", "mouse"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "middleClickCloseTab",
    label: "Middle Click Close Tab",
    description: "Close tabs with middle mouse click",
    tags: ["middle click", "close tab", "mouse"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "folderSingleClickToggle",
    label: "Folder expand on single click",
    description: "Click anywhere on a folder row to expand or collapse",
    tags: ["folder", "expand", "collapse", "tree", "sidebar", "click"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "folderDoubleClickToggle",
    label: "Folder expand on double click",
    description: "Double-click a folder row to expand or collapse",
    tags: ["folder", "expand", "collapse", "tree", "sidebar", "double click"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "openConnectionInBackground",
    label: "Open in Background",
    description: "Open new connections in background tab",
    tags: ["background", "tab", "new tab"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "switchTabOnActivity",
    label: "Switch Tab on Activity",
    description: "Focus tab when it receives output",
    tags: ["activity", "output", "focus", "switch"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "closeTabOnDisconnect",
    label: "Close Tab on Disconnect",
    description: "Auto-close tab when session ends",
    tags: ["close", "disconnect", "auto close"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "confirmCloseActiveTab",
    label: "Confirm Close Active Tab",
    description: "Warn before closing tab with live session",
    tags: ["confirm", "warning", "active", "close tab"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "enableRecentlyClosedTabs",
    label: "Recently Closed Tabs",
    description: "Keep a list of recently closed tabs",
    tags: ["recent", "undo close", "reopen", "history"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "focusTerminalOnTabSwitch",
    label: "Focus Terminal on Tab Switch",
    description: "Auto-focus terminal when switching tabs",
    tags: ["focus", "terminal", "keyboard", "input"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "scrollTreeToActiveConnection",
    label: "Scroll Tree to Active",
    description: "Scroll sidebar to active connection",
    tags: ["scroll", "sidebar", "tree", "reveal"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "restoreLastActiveTab",
    label: "Restore Last Tab",
    description: "Restore last active tab on startup",
    tags: ["restore", "tab", "startup", "remember"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "tabCycleMru",
    label: "Tab Cycle MRU",
    description: "Cycle tabs in most-recently-used order",
    tags: ["ctrl tab", "mru", "cycle", "order"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "copyOnSelect",
    label: "Copy on Select",
    description: "Copy terminal selection to clipboard automatically",
    tags: ["copy", "select", "clipboard", "auto copy"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "pasteOnRightClick",
    label: "Paste on Right Click",
    description: "Right-click in terminal pastes from clipboard",
    tags: ["paste", "right click", "clipboard"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "clearClipboardAfterSeconds",
    label: "Clear Clipboard Timer",
    description: "Auto-clear clipboard after a terminal paste",
    tags: ["clipboard", "clear", "security", "terminal", "timeout"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "trimPastedWhitespace",
    label: "Trim Pasted Whitespace",
    description: "Strip whitespace when pasting",
    tags: ["paste", "trim", "whitespace", "clean"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "warnOnMultiLinePaste",
    label: "Warn Multi-line Paste",
    description: "Warn before pasting multi-line text",
    tags: ["paste", "multiline", "warning", "confirm"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "maxPasteLengthChars",
    label: "Max Paste Length",
    description: "Maximum paste size before prompting",
    tags: ["paste", "limit", "size", "characters"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "idleDisconnectMinutes",
    label: "Idle Disconnect",
    description: "Disconnect after idle minutes",
    tags: ["idle", "timeout", "disconnect", "inactivity"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "sendKeepaliveOnIdle",
    label: "Send Keepalive",
    description: "Send keepalive to prevent idle timeout",
    tags: ["keepalive", "idle", "ping", "heartbeat"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "keepaliveIntervalSeconds",
    label: "Keepalive Interval",
    description: "Seconds between keepalive packets",
    tags: ["keepalive", "interval", "frequency"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "dimInactiveTabs",
    label: "Dim Inactive Tabs",
    description: "Reduce brightness of unfocused tabs",
    tags: ["dim", "inactive", "fade", "visual"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "showIdleDuration",
    label: "Show Idle Duration",
    description: "Display idle time badge on tabs",
    tags: ["idle", "duration", "badge", "time"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "autoReconnectOnDisconnect",
    label: "Auto Reconnect",
    description: "Reconnect when session drops unexpectedly",
    tags: ["reconnect", "auto", "disconnect", "retry"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "autoReconnectMaxAttempts",
    label: "Reconnect Max Attempts",
    description: "Maximum reconnection attempts",
    tags: ["reconnect", "attempts", "retry", "limit"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "autoReconnectDelaySecs",
    label: "Reconnect Delay",
    description: "Initial delay before reconnect attempts",
    tags: ["reconnect", "delay", "wait", "interval", "ssh", "reboot"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "autoReconnectBackoff",
    label: "Reconnect Backoff",
    description: "Fixed or exponential reconnect delays",
    tags: ["reconnect", "backoff", "exponential", "retry", "ssh", "reboot"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "autoReconnectMaxDelaySecs",
    label: "Reconnect Maximum Delay",
    description: "Upper bound for exponential reconnect delay",
    tags: ["reconnect", "delay", "maximum", "cap", "ssh", "reboot"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "notifyOnReconnect",
    label: "Notify on Reconnect",
    description: "Notification when session reconnects",
    tags: ["notify", "reconnect", "alert"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "notifyOnConnect",
    label: "Notify on Connect",
    description: "Notification when session connects",
    tags: ["notify", "connect", "alert", "notification"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "notifyOnDisconnect",
    label: "Notify on Disconnect",
    description: "Notification when session disconnects",
    tags: ["notify", "disconnect", "alert"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "notifyOnError",
    label: "Notify on Error",
    description: "Notification on connection error",
    tags: ["notify", "error", "alert", "failure"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "notificationSound",
    label: "Notification Sound",
    description: "Play sound with notifications",
    tags: ["sound", "audio", "beep", "alert"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "flashTaskbarOnActivity",
    label: "Flash Taskbar",
    description: "Flash taskbar on background activity",
    tags: ["taskbar", "flash", "blink", "attention"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "confirmDisconnect",
    label: "Confirm Disconnect",
    description: "Confirm before disconnecting",
    tags: ["confirm", "disconnect", "warning"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "confirmDeleteConnection",
    label: "Confirm Delete Connection",
    description: "Confirm before deleting connections",
    tags: ["confirm", "delete", "remove", "warning"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "confirmBulkOperations",
    label: "Confirm Bulk Operations",
    description: "Confirm batch actions",
    tags: ["confirm", "bulk", "batch", "multi select"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "confirmImport",
    label: "Confirm Import",
    description: "Confirm before importing connections",
    tags: ["confirm", "import", "warning"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "enableFileDragDropToTerminal",
    label: "File Drag Drop to Terminal",
    description: "Drop files onto terminal for upload",
    tags: ["drag", "drop", "file", "upload", "scp"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "dragSensitivityPx",
    label: "Drag Sensitivity",
    description: "Pixel threshold before drag starts",
    tags: ["drag", "sensitivity", "threshold"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "showDropPreview",
    label: "Drop Preview Overlay",
    description: "Visual indicator when dragging over targets",
    tags: ["drag", "drop", "preview", "overlay"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "terminalScrollSpeed",
    label: "Terminal Scroll Speed",
    description: "Scroll speed multiplier for terminal",
    tags: ["scroll", "speed", "terminal", "mouse wheel"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "terminalSmoothScroll",
    label: "Smooth Scroll",
    description: "Enable smooth scrolling in terminal",
    tags: ["smooth", "scroll", "animation"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "treeRightClickAction",
    label: "Tree Right Click",
    description: "Right-click action in connection tree",
    tags: ["right click", "context menu", "tree"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "mouseBackAction",
    label: "Mouse Back Button",
    description: "Action for mouse back button",
    tags: ["mouse", "back", "button", "navigate"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
  {
    key: "mouseForwardAction",
    label: "Mouse Forward Button",
    description: "Action for mouse forward button",
    tags: ["mouse", "forward", "button", "navigate"],
    section: "behavior",
    sectionLabel: "Behavior",
  },
];
