import type { SettingSearchEntry } from "./types";

/**
 * Search index entries for the `diagnostics` settings tab.
 *
 * Every `key` must match a `settingKey` / `data-setting-key` rendered by that
 * tab's section components — `tests/settings/settingsSearchDrift.test.ts`
 * enforces the join in both directions.
 */
export const DIAGNOSTICS_SEARCH_ENTRIES: SettingSearchEntry[] = [
  // ─── Diagnostics ──────────────────────────────────────────────
  {
    key: "diagnostics.pingCount",
    label: "Ping Count",
    description: "Number of pings to send",
    tags: ["ping", "count", "icmp", "network"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.pingTimeoutSecs",
    label: "Ping Timeout",
    description: "Timeout per ping in seconds",
    tags: ["ping", "timeout", "icmp"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.pingIntervalMs",
    label: "Ping Interval",
    description: "Delay between pings in milliseconds",
    tags: ["ping", "interval", "delay"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.tracerouteMaxHops",
    label: "Traceroute Max Hops",
    description: "Maximum hops for traceroute",
    tags: ["traceroute", "hops", "route", "path"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.tracerouteTimeoutSecs",
    label: "Traceroute Timeout",
    description: "Per-hop timeout for traceroute",
    tags: ["traceroute", "timeout"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.portCheckTimeoutSecs",
    label: "Port Check Timeout",
    description: "Timeout for TCP port checks",
    tags: ["port", "check", "timeout", "tcp"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.tcpTimingTimeoutSecs",
    label: "TCP Timing Timeout",
    description: "Timeout for TCP timing measurement",
    tags: ["tcp", "timing", "handshake", "timeout"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.mtuCheckEnabled",
    label: "MTU Check",
    description: "Enable path MTU discovery",
    tags: ["mtu", "fragmentation", "path"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.icmpBlockadeEnabled",
    label: "ICMP Blockade Detection",
    description: "Detect ICMP filtering by firewalls",
    tags: ["icmp", "firewall", "block", "filter"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.serviceFingerprintEnabled",
    label: "Service Fingerprint",
    description: "Identify services on target ports",
    tags: ["fingerprint", "service", "banner", "version"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.asymmetricRoutingEnabled",
    label: "Asymmetric Routing",
    description: "Detect asymmetric routing paths",
    tags: ["asymmetric", "routing", "path", "ttl"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.asymmetricRoutingSamples",
    label: "Routing Samples",
    description: "Number of samples for routing analysis",
    tags: ["asymmetric", "routing", "samples"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.tlsCheckEnabled",
    label: "TLS Check",
    description: "Check TLS certificates on HTTPS ports",
    tags: ["tls", "ssl", "certificate", "https"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.ipGeoEnabled",
    label: "IP Geolocation",
    description: "Look up IP geographic information",
    tags: ["geo", "location", "ip", "country", "asn"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.udpProbeEnabled",
    label: "UDP Probe",
    description: "Probe UDP ports for services",
    tags: ["udp", "probe", "dns", "ntp", "snmp"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.udpProbeTimeoutMs",
    label: "UDP Probe Timeout",
    description: "Timeout for UDP probes",
    tags: ["udp", "timeout", "probe"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.leakageDetectionEnabled",
    label: "Leakage Detection",
    description: "Detect proxy/VPN DNS and IP leaks",
    tags: ["leak", "vpn", "proxy", "dns", "privacy"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.protocolDiagEnabled",
    label: "Protocol Diagnostics",
    description: "Protocol-specific deep diagnostics",
    tags: ["protocol", "ssh", "rdp", "http", "deep"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.protocolDiagTimeoutSecs",
    label: "Protocol Diag Timeout",
    description: "Timeout for protocol diagnostics",
    tags: ["protocol", "timeout", "diagnostic"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.autoRunOnOpen",
    label: "Auto-Run on Open",
    description: "Auto-run diagnostics when tab opens",
    tags: ["auto", "run", "start", "open"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.showDetailedResults",
    label: "Detailed Results",
    description: "Show verbose diagnostic output",
    tags: ["detail", "verbose", "results"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
  {
    key: "diagnostics.expandFailedSteps",
    label: "Expand Failed Steps",
    description: "Auto-expand failed diagnostic steps",
    tags: ["expand", "failed", "error", "collapse"],
    section: "diagnostics",
    sectionLabel: "Diagnostics",
  },
];
