import type { SettingSearchEntry } from "./types";

/**
 * Search index entries for the `layout` settings tab.
 *
 * Every `key` must match a `settingKey` / `data-setting-key` rendered by that
 * tab's section components — `tests/settings/settingsSearchDrift.test.ts`
 * enforces the join in both directions.
 */
export const LAYOUT_SEARCH_ENTRIES: SettingSearchEntry[] = [
  // ─── Window persistence ─────────────────────────────────────────
  {
    key: "persistWindowSize",
    label: "Remember window size",
    labelKey: "settingsLayout.rememberWindowSize",
    description: "Save and restore the window dimensions between sessions",
    descriptionKey: "settingsLayout.rememberWindowSizeTooltip",
    tags: ["window", "size", "remember", "persist", "dimensions", "restore"],
    synonyms: ["window size", "remember size", "save window size"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "persistWindowPosition",
    label: "Remember window position",
    labelKey: "settingsLayout.rememberWindowPosition",
    description:
      "Save and restore the window location on screen between sessions",
    descriptionKey: "settingsLayout.rememberWindowPositionTooltip",
    tags: ["window", "position", "remember", "persist", "location", "screen"],
    synonyms: ["window position", "remember position", "window placement"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "autoRepatriateWindow",
    label: "Auto-repatriate window if off-screen",
    labelKey: "settingsLayout.autoRepatriateWindow",
    description:
      "Move the window back to a visible monitor if its saved position is off-screen",
    descriptionKey: "settingsLayout.autoRepatriateWindowTooltip",
    tags: [
      "window",
      "offscreen",
      "monitor",
      "display",
      "recover",
      "multi monitor",
    ],
    synonyms: [
      "off screen",
      "off-screen window",
      "lost window",
      "window disappeared",
      "external display",
      "bring window back",
    ],
    section: "layout",
    sectionLabel: "Layout",
  },

  // ─── Sidebar persistence ────────────────────────────────────────
  {
    key: "persistSidebarWidth",
    label: "Remember sidebar width",
    labelKey: "settingsLayout.rememberSidebarWidth",
    description:
      "Persist the sidebar width so it stays the same after restarting",
    descriptionKey: "settingsLayout.rememberSidebarWidthTooltip",
    tags: ["sidebar", "width", "panel", "pane", "persist", "remember"],
    synonyms: ["side bar", "left pane", "panel width", "tree width"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "persistSidebarPosition",
    label: "Remember sidebar position",
    labelKey: "settingsLayout.rememberSidebarPosition",
    description: "Save whether the sidebar is docked to the left or right side",
    descriptionKey: "settingsLayout.rememberSidebarPositionTooltip",
    tags: ["sidebar", "position", "dock", "left", "right", "pane", "persist"],
    synonyms: ["side bar", "dock left", "dock right", "panel side"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "persistSidebarCollapsed",
    label: "Remember sidebar collapsed state",
    labelKey: "settingsLayout.rememberSidebarCollapsed",
    description:
      "Persist whether the sidebar is expanded or collapsed between sessions",
    descriptionKey: "settingsLayout.rememberSidebarCollapsedTooltip",
    tags: ["sidebar", "collapse", "expand", "pane", "persist", "remember"],
    synonyms: ["side bar", "collapsed", "hide sidebar", "panel collapsed"],
    section: "layout",
    sectionLabel: "Layout",
  },

  // ─── Tab interaction ────────────────────────────────────────────
  {
    key: "enableTabReorder",
    label: "Allow tab reordering",
    labelKey: "settingsLayout.allowTabReordering",
    description:
      "Enable drag-and-drop reordering of connection tabs in the tab bar",
    descriptionKey: "settingsLayout.allowTabReorderingTooltip",
    tags: ["tabs", "drag", "reorder", "sort", "tab bar", "drag and drop"],
    synonyms: ["reorder tabs", "move tabs", "drag tabs"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "enableConnectionReorder",
    label: "Allow connection reordering",
    labelKey: "settingsLayout.allowConnectionReordering",
    description:
      "Enable drag-and-drop reordering of connections in the sidebar tree",
    descriptionKey: "settingsLayout.allowConnectionReorderingTooltip",
    tags: ["connections", "drag", "reorder", "sort", "tree", "sidebar"],
    synonyms: ["reorder connections", "move connections", "drag in tree"],
    section: "layout",
    sectionLabel: "Layout",
  },

  // ─── Default tab layout / grouping ──────────────────────────────
  {
    key: "defaultTabLayout",
    label: "Default Tab Layout",
    labelKey: "settingsLayout.defaultTabLayoutTitle",
    description:
      "Tiling mode used when the app starts. The active mode is also persisted across launches once you change it from the toolbar.",
    descriptionKey: "settingsLayout.defaultTabLayoutTooltip",
    tags: ["tabs", "layout", "tiling", "grid", "split", "mosaic", "panes"],
    // Both halves of every DEFAULT_TAB_LAYOUT_CONFIG option. The list is a
    // module constant rather than a literal `options` prop, so the drift guard
    // cannot check it — keep it in step with `LayoutSettings.tsx` by hand.
    values: [
      "tabs",
      "Tabs",
      "splitVertical",
      "Split L/R",
      "split left right",
      "splitHorizontal",
      "Split T/B",
      "split top bottom",
      "sideBySide",
      "Side-by-Side",
      "grid2",
      "Grid 2",
      "grid4",
      "Grid 4",
      "grid6",
      "Grid 6",
      "mosaic",
      "Mosaic",
      "miniMosaic",
      "Mini Mosaic",
      "customGrid",
      "Custom Grid",
    ],
    synonyms: ["tiling", "split screen", "panes", "tile windows", "grid view"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "tabGrouping",
    label: "Tab Grouping",
    labelKey: "settingsLayout.tabGroupingTitle",
    description:
      "Organize open connection tabs into groups based on a shared property.",
    descriptionKey: "settingsLayout.tabGroupingTooltip",
    tags: ["tabs", "group", "organize", "sort", "protocol", "status"],
    values: [
      "none",
      "None",
      "protocol",
      "By Protocol",
      "status",
      "By Status",
      "hostname",
      "By Hostname",
    ],
    synonyms: ["group tabs", "tab groups", "group by protocol"],
    section: "layout",
    sectionLabel: "Layout",
  },

  // ─── Secondary bar icons ────────────────────────────────────────
  {
    key: "showQuickConnectIcon",
    label: "Quick Connect",
    labelKey: "connections.quickConnect",
    description: "Show the Quick Connect icon for rapidly connecting to a host",
    descriptionKey: "settingsLayout.showQuickConnectIconTooltip",
    tags: ["toolbar", "icon", "quick connect", "secondary bar"],
    synonyms: ["quickconnect", "toolbar icon"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showCollectionSwitcherIcon",
    label: "Collection Switcher",
    labelKey: "settingsLayout.collectionSwitcher",
    description: "Show the icon for switching between connection collections",
    descriptionKey: "settingsLayout.collectionSwitcherTooltip",
    tags: ["toolbar", "icon", "collection", "switch", "secondary bar"],
    synonyms: ["switch collection", "collections icon"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showImportExportIcon",
    label: "Import / Export",
    labelKey: "settingsLayout.importExport",
    description: "Show the icon for importing and exporting connection data",
    descriptionKey: "settingsLayout.importExportTooltip",
    tags: ["toolbar", "icon", "import", "export", "secondary bar"],
    synonyms: ["import export icon", "backup icon"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showSettingsIcon",
    label: "Settings",
    labelKey: "settings.title",
    description: "Show the settings icon in the secondary bar",
    descriptionKey: "settingsLayout.settingsIconTooltip",
    tags: ["toolbar", "icon", "settings", "preferences", "secondary bar"],
    synonyms: ["gear icon", "preferences icon"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showProxyMenuIcon",
    label: "Proxy / VPN Menu",
    labelKey: "settingsLayout.proxyVpnMenu",
    description: "Show the proxy and VPN management icon",
    descriptionKey: "settingsLayout.proxyVpnMenuTooltip",
    tags: ["toolbar", "icon", "proxy", "vpn", "secondary bar"],
    synonyms: ["proxy icon", "vpn icon", "proxy chain"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showShortcutManagerIcon",
    label: "Shortcut Manager",
    labelKey: "settingsLayout.shortcutManager",
    description: "Show the keyboard shortcut manager icon",
    descriptionKey: "settingsLayout.shortcutManagerTooltip",
    tags: ["toolbar", "icon", "shortcut", "keyboard", "hotkey", "keybinding"],
    synonyms: ["hotkeys", "keybindings", "keyboard shortcuts icon"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showPerformanceMonitorIcon",
    label: "Performance Monitor",
    labelKey: "settingsLayout.performanceMonitor",
    description: "Show the real-time performance monitor icon",
    descriptionKey: "settingsLayout.performanceMonitorTooltip",
    tags: ["toolbar", "icon", "performance", "monitor", "cpu", "memory"],
    synonyms: ["perfmon", "resource monitor", "performance icon"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showActionLogIcon",
    label: "Action Log",
    labelKey: "settingsLayout.actionLog",
    description:
      "Show the action log icon for reviewing recent application actions and events",
    descriptionKey: "settingsLayout.actionLogTooltip",
    tags: ["toolbar", "icon", "action log", "audit", "events", "history"],
    synonyms: ["audit log", "activity log", "event log"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showDevtoolsIcon",
    label: "Devtools",
    labelKey: "settingsLayout.devtools",
    description:
      "Show the developer tools icon for inspecting the application UI",
    descriptionKey: "settingsLayout.devtoolsTooltip",
    tags: ["toolbar", "icon", "devtools", "developer", "inspect", "debug"],
    synonyms: ["dev tools", "developer tools", "inspector", "f12"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showDebugPanelIcon",
    label: "Debug Panel",
    labelKey: "settingsLayout.debugPanel",
    description:
      "Show the debug panel icon for development and troubleshooting tools",
    descriptionKey: "settingsLayout.debugPanelTooltip",
    tags: ["toolbar", "icon", "debug", "panel", "troubleshoot", "diagnostics"],
    synonyms: ["debugging", "troubleshooting panel"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showSecurityIcon",
    label: "Security",
    labelKey: "settings.security",
    description:
      "Show the security icon for quick access to security-related tools",
    descriptionKey: "settingsLayout.securityIconTooltip",
    tags: ["toolbar", "icon", "security", "vault", "secondary bar"],
    synonyms: ["security icon", "lock icon"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showWolIcon",
    label: "Wake-on-LAN",
    labelKey: "settingsLayout.wakeOnLan",
    description:
      "Show the Wake-on-LAN icon for sending wake packets to remote machines",
    descriptionKey: "settingsLayout.wakeOnLanTooltip",
    tags: ["toolbar", "icon", "wol", "wake", "lan", "power"],
    synonyms: ["wol", "wake on lan", "magic packet", "power on"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showBulkSSHIcon",
    label: "Bulk SSH Commander",
    labelKey: "settingsLayout.bulkSshCommander",
    description:
      "Show the Bulk SSH Commander icon for running SSH commands across multiple hosts",
    descriptionKey: "settingsLayout.bulkSshCommanderTooltip",
    tags: ["toolbar", "icon", "bulk", "ssh", "commander", "mass", "broadcast"],
    synonyms: ["bulk ssh", "mass command", "run on all hosts"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showScriptManagerIcon",
    label: "Script Manager",
    labelKey: "settingsLayout.scriptManager",
    description: "Show the Script Manager icon for managing reusable scripts",
    descriptionKey: "settingsLayout.scriptManagerTooltip",
    tags: ["toolbar", "icon", "script", "manager", "automation"],
    synonyms: ["scripts", "script library"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showMacroManagerIcon",
    label: "Macro Manager",
    labelKey: "settingsLayout.macroManager",
    description:
      "Show the Macro Manager icon for recording and replaying command sequences",
    descriptionKey: "settingsLayout.macroManagerTooltip",
    tags: ["toolbar", "icon", "macro", "manager", "replay", "automation"],
    synonyms: ["macros", "command sequences"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showRecordingManagerIcon",
    label: "Recording Manager",
    labelKey: "settingsLayout.recordingManager",
    description:
      "Show the Recording Manager icon for managing recorded sessions",
    descriptionKey: "settingsLayout.recordingManagerTooltip",
    tags: ["toolbar", "icon", "recording", "manager", "library", "sessions"],
    synonyms: ["recordings", "recording library", "session recordings"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showErrorLogBar",
    label: "Error Log Bar",
    labelKey: "settingsLayout.errorLogBar",
    description:
      "Show the error log bar toggle for quickly opening recent application errors",
    descriptionKey: "settingsLayout.errorLogBarTooltip",
    tags: ["toolbar", "icon", "error", "log", "debug", "bar"],
    synonyms: ["error bar", "error log", "recent errors"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showBackupStatusIcon",
    label: "Backup Status",
    labelKey: "settingsLayout.backupStatus",
    description:
      "Show the backup status icon for monitoring local backup state",
    descriptionKey: "settingsLayout.backupStatusTooltip",
    tags: ["toolbar", "icon", "backup", "status", "local"],
    synonyms: ["backup icon", "backup indicator"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showCloudSyncStatusIcon",
    label: "Cloud Sync Status",
    labelKey: "settingsLayout.cloudSyncStatus",
    description:
      "Show the cloud sync status icon for monitoring remote synchronization state",
    descriptionKey: "settingsLayout.cloudSyncStatusTooltip",
    tags: ["toolbar", "icon", "cloud", "sync", "status", "remote"],
    synonyms: ["cloud sync icon", "sync indicator"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showSyncBackupStatusIcon",
    label: "Sync & Backup (Combined)",
    labelKey: "settingsLayout.syncBackupCombined",
    description:
      "Show a combined status icon for backup and cloud sync activity",
    descriptionKey: "settingsLayout.syncBackupCombinedTooltip",
    tags: ["toolbar", "icon", "sync", "backup", "combined", "status"],
    synonyms: ["combined status", "sync and backup icon"],
    section: "layout",
    sectionLabel: "Layout",
  },
  {
    key: "showRdpSessionsIcon",
    label: "Session Manager",
    labelKey: "settingsLayout.sessionManager",
    description:
      "Show the Session Manager icon for opening and monitoring active sessions",
    descriptionKey: "settingsLayout.sessionManagerTooltip",
    tags: ["toolbar", "icon", "rdp", "ssh", "sessions", "manager"],
    synonyms: ["session manager", "active sessions", "rdp sessions"],
    section: "layout",
    sectionLabel: "Layout",
  },
];
