import type { SettingSearchEntry } from "./types";

/**
 * Search index entries for the `security` settings tab.
 *
 * Every `key` must match a `settingKey` / `data-setting-key` rendered by that
 * tab's section components — `tests/settings/settingsSearchDrift.test.ts`
 * enforces the join in both directions.
 *
 * Sysadmins search for the *algorithm*, not the label: `argon2`, `AES-256-GCM`,
 * `ChaCha20`, `pbkdf2`, `credssp`, `kerberos`, `sha256` all have to land here,
 * which is what `values` and `synonyms` are for.
 */

/** `ENCRYPTION_ALGORITHMS` in `hooks/settings/useSecuritySettings.ts`. */
const ENCRYPTION_ALGORITHM_VALUES = [
  "AES-256-GCM",
  "AES-256-CBC",
  "ChaCha20-Poly1305",
  "Serpent-256-GCM",
  "Serpent-256-CBC",
  "Twofish-256-GCM",
  "Twofish-256-CBC",
] as const;

/** Shared with every export-inclusion toggle. */
const EXPORT_TAGS = ["export", "import", "backup", "defaults"] as const;

/** Shared with every CredSSP / NLA row. */
const CREDSSP_TAGS = [
  "credssp",
  "nla",
  "rdp",
  "remote desktop",
  "authentication",
] as const;

export const SECURITY_SEARCH_ENTRIES: SettingSearchEntry[] = [
  // ─── Encryption at rest ─────────────────────────────────────────
  {
    key: "encryptionAtRest",
    label: "Encryption at rest",
    description:
      "Application-wide master key and per-artifact codecs for settings, recordings, backups, macros and logs. Shows the master key location, OS vault backend, on-disk state and schema version.",
    tags: [
      "encryption",
      "at rest",
      "master key",
      "dek",
      "vault",
      "keychain",
      "keyring",
      "on disk",
      "status",
      "unlock",
      "hkdf",
    ],
    synonyms: [
      "data at rest",
      "disk encryption",
      "credential manager",
      "libsecret",
      "wincred",
      "settings.enc",
      "dek.enc",
    ],
    values: ["AES-256-GCM", "HKDF-SHA256"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.lockNow",
    label: "Lock now",
    description:
      "Drop the master key from memory immediately and return to the unlock screen. Keyboard shortcut Ctrl+L (⌘L on macOS).",
    tags: ["lock", "unlock", "master key", "memory", "shortcut", "ctrl+l"],
    synonyms: ["lock the app", "wipe key from memory", "cmd+l"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.setup",
    label: "Set up encryption",
    description:
      "First-run choice between storing the master key in the OS vault or wrapping it with an Argon2id password.",
    tags: [
      "setup",
      "wizard",
      "master key",
      "vault",
      "password",
      "argon2",
      "argon2id",
      "generate",
    ],
    synonyms: ["first run", "enable encryption", "os keychain"],
    values: ["Use the OS vault", "Wrap with a password"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.masterPassword",
    label: "Master password",
    description:
      "Password used to wrap the master data-encryption key via Argon2id. At least 12 characters recommended.",
    tags: ["master password", "password", "argon2", "argon2id", "kdf", "wrap"],
    synonyms: ["passphrase", "storage password", "unlock password"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.argon2MemoryKib",
    label: "Argon2id memory",
    description:
      "Memory cost for the password KDF. Higher values dramatically slow offline guessing. OWASP recommends at least 64 MiB.",
    tags: [
      "argon2",
      "argon2id",
      "memory",
      "kib",
      "mib",
      "kdf",
      "owasp",
      "cost",
    ],
    synonyms: ["memory cost", "m_cost", "memory hardness"],
    values: ["8", "KiB"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.argon2TimeCost",
    label: "Argon2id iterations",
    description:
      "Time cost for the password KDF. 3 is the OWASP default; raise it if you can tolerate slower unlocks.",
    tags: ["argon2", "argon2id", "iterations", "time cost", "kdf", "owasp"],
    synonyms: ["t_cost", "passes", "rounds"],
    values: ["1", "50"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.argon2Parallelism",
    label: "Argon2id parallelism",
    description:
      "Number of parallel lanes for the password KDF. 4 is the OWASP default and matches typical CPU thread counts.",
    tags: [
      "argon2",
      "argon2id",
      "parallelism",
      "lanes",
      "threads",
      "kdf",
      "owasp",
    ],
    synonyms: ["p_cost", "thread count"],
    values: ["1", "64"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.migratePlaintext",
    label: "Migrate plaintext settings",
    description:
      "Rewrite a plaintext settings.json as an encrypted settings.enc under the master key.",
    tags: [
      "migrate",
      "plaintext",
      "settings.json",
      "settings.enc",
      "encrypt",
      "upgrade",
    ],
    synonyms: ["convert to encrypted", "v0 plaintext"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.changePassword",
    label: "Change master password",
    description:
      "Re-wrap the existing master key under a new password without re-encrypting any artifact.",
    tags: ["change password", "master password", "rewrap", "argon2", "rotate"],
    synonyms: ["new password", "update passphrase"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.rotateMasterKey",
    label: "Rotate master key",
    description:
      "Generate a fresh master data-encryption key and re-encrypt every artifact under it.",
    tags: ["rotate", "master key", "dek", "rekey", "re-encrypt"],
    synonyms: ["key rotation", "new master key"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.exportPortableKey",
    label: "Export portable master key",
    description:
      "Write the master key to a password-protected portable file so another machine can be provisioned with it.",
    tags: ["export", "portable", "master key", "escrow", "transfer", "backup"],
    synonyms: ["key escrow", "move key to another machine"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.importPortableKey",
    label: "Import portable master key",
    description:
      "Load a password-protected portable master key file exported from another installation.",
    tags: ["import", "portable", "master key", "restore", "provision"],
    synonyms: ["restore master key", "adopt key"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.disable",
    label: "Disable settings encryption",
    description:
      "Turn encryption at rest off and write settings back to disk in plaintext.",
    tags: ["disable", "decrypt", "plaintext", "turn off", "encryption"],
    synonyms: ["remove encryption", "revert to plaintext"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.artifacts",
    label: "Encrypted artifacts",
    description:
      "Which artifacts have their own AES-256-GCM sub-key derived from the master key via HKDF-SHA256, and their HKDF labels.",
    tags: [
      "artifacts",
      "hkdf",
      "sub-key",
      "aes",
      "domain separation",
      "recordings",
      "macros",
      "logs",
    ],
    synonyms: ["sorng-v1::settings", "per-artifact key", "hkdf label"],
    values: ["AES-256-GCM", "HKDF-SHA256"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "encryptionAtRest.auditLog",
    label: "Audit log",
    description:
      "Append-only JSON-lines log of every state-changing encryption operation, kept in plaintext at <app_data_dir>/logs/encryption-audit.log.",
    tags: [
      "audit",
      "log",
      "history",
      "events",
      "json lines",
      "jsonl",
      "compliance",
    ],
    synonyms: ["encryption-audit.log", "audit trail", "event log"],
    section: "security",
    sectionLabel: "Security",
  },

  // ─── Encryption algorithm ───────────────────────────────────────
  {
    key: "encryptionAlgorithm",
    label: "Algorithm",
    labelKey: "security.algorithm",
    description:
      "The symmetric cipher used to encrypt stored credentials and connection files. AES-256-GCM is widely supported; ChaCha20-Poly1305 is the modern alternative.",
    tags: [
      "encryption",
      "algorithm",
      "aes",
      "crypto",
      "cipher",
      "chacha",
      "serpent",
      "twofish",
      "aead",
      "hardware aes",
      "aes-ni",
    ],
    synonyms: [
      "chacha20",
      "poly1305",
      "aes256",
      "symmetric cipher",
      "vaes",
      "pclmulqdq",
    ],
    values: [...ENCRYPTION_ALGORITHM_VALUES],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "blockCipherMode",
    label: "Cipher mode",
    description:
      "Block cipher mode of operation — determines how plaintext blocks are chained together during encryption.",
    tags: ["cipher", "mode", "gcm", "cbc", "encryption", "block"],
    synonyms: ["galois counter mode", "cipher block chaining", "aead mode"],
    values: [
      "GCM",
      "GCM (Galois/Counter Mode)",
      "CBC",
      "CBC (Cipher Block Chaining)",
    ],
    section: "security",
    sectionLabel: "Security",
  },

  // ─── Key derivation (PBKDF2) ────────────────────────────────────
  {
    key: "keyDerivationIterations",
    label: "Iterations",
    labelKey: "security.iterations",
    description:
      "Number of PBKDF2 hashing rounds used to derive the encryption key from the master password. Higher values increase security but slow down unlock.",
    tags: [
      "pbkdf2",
      "iterations",
      "password",
      "key derivation",
      "kdf",
      "rounds",
      "bruteforce",
      "sha256",
    ],
    synonyms: ["key stretching", "hash rounds", "work factor"],
    values: ["10000", "1000000"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "benchmarkTimeSeconds",
    label: "Benchmark time",
    labelKey: "security.benchmarkTime",
    description:
      "Target duration in seconds the benchmark should run to determine the optimal iteration count for this hardware.",
    tags: ["benchmark", "pbkdf2", "iterations", "seconds", "tuning", "cpu"],
    synonyms: ["calibrate iterations", "kdf benchmark"],
    values: ["0.5", "10", "s", "seconds"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "autoBenchmarkIterations",
    label: "Auto benchmark",
    labelKey: "security.autoBenchmark",
    description:
      "Re-run the iteration benchmark on each launch to keep the count optimal for the current machine.",
    tags: ["benchmark", "automatic", "startup", "pbkdf2", "iterations"],
    synonyms: ["auto calibrate", "benchmark on launch"],
    section: "security",
    sectionLabel: "Security",
  },

  // ─── Export security ────────────────────────────────────────────
  {
    key: "exportSecurity.defaultFormat",
    label: "Default export format",
    description:
      "Format pre-selected in the Import / Export tool. Individual exports can still override this.",
    tags: [...EXPORT_TAGS, "format", "json", "xml", "csv", "html", "excel"],
    synonyms: ["mremoteng", "markdown export", "file format"],
    values: [
      "json",
      "JSON package",
      "xml",
      "sortOfRemoteNG XML",
      "csv",
      "CSV inventory",
      "txt",
      "Plain text outline",
      "markdown",
      "Markdown table",
      "html",
      "HTML report",
      "excel",
      "Excel table (.xls)",
      "mremoteng",
      "mRemoteNG XML",
    ],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.keyDerivationIterations",
    label: "Export PBKDF2 iterations",
    description:
      "Higher iteration counts slow down brute-force attacks against password-encrypted export files, but also slow export and import.",
    tags: [...EXPORT_TAGS, "pbkdf2", "iterations", "bruteforce", "password"],
    synonyms: ["export key derivation", "export kdf"],
    values: ["10000", "5000000"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.includeConnectionsByDefault",
    label: "Connections",
    description: "Include saved connections in exports by default.",
    tags: [...EXPORT_TAGS, "connections", "hosts", "include"],
    synonyms: ["export connections"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.encryptByDefault",
    label: "Encrypt exports",
    description: "Password-encrypt the exported file by default.",
    tags: [...EXPORT_TAGS, "encrypt", "password", "protect"],
    synonyms: ["encrypted export", "password protect export"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.includePasswordsByDefault",
    label: "Passwords",
    description: "Include saved passwords in the export by default.",
    tags: [...EXPORT_TAGS, "passwords", "credentials", "secrets", "include"],
    synonyms: ["export secrets", "include credentials"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.includeSettingsByDefault",
    label: "Application settings",
    description: "Include global application preferences in exports.",
    tags: [...EXPORT_TAGS, "settings", "preferences", "include"],
    synonyms: ["export settings"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.includeFolderItemsByDefault",
    label: "Folders / groups",
    description: "Include the folder tree structure in exports.",
    tags: [...EXPORT_TAGS, "folders", "groups", "tree", "include"],
    synonyms: ["export folder structure"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.includeEmptyFoldersByDefault",
    label: "Empty folders",
    description: "Include folders that contain no connections.",
    tags: [...EXPORT_TAGS, "empty", "folders", "include"],
    synonyms: ["export empty groups"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.includeTabGroupsByDefault",
    label: "Tab groups",
    description: "Include user-defined tab groups in exports.",
    tags: [...EXPORT_TAGS, "tab groups", "workspaces", "include"],
    synonyms: ["export tab groups"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.includeColorTagsByDefault",
    label: "Color tags",
    description: "Include color tag definitions in exports.",
    tags: [...EXPORT_TAGS, "color tags", "labels", "include"],
    synonyms: ["export colour tags"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.includeVpnDataByDefault",
    label: "VPN definitions",
    description: "Include configured VPN profiles in exports.",
    tags: [...EXPORT_TAGS, "vpn", "profiles", "include"],
    synonyms: ["export vpn", "wireguard", "openvpn"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.includeTunnelChainsByDefault",
    label: "Tunnel chains",
    description: "Include SSH tunnel chains in exports.",
    tags: [...EXPORT_TAGS, "tunnel", "chains", "ssh", "jump host", "include"],
    synonyms: ["export tunnels", "bastion chain"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.includeExportMetadataByDefault",
    label: "Export metadata",
    description: "Embed metadata describing how the export was produced.",
    tags: [...EXPORT_TAGS, "metadata", "provenance", "include"],
    synonyms: ["export provenance"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.includeDatabaseMetadataByDefault",
    label: "Database metadata",
    description: "Include the source collection's metadata in exports.",
    tags: [...EXPORT_TAGS, "database", "collection", "metadata", "include"],
    synonyms: ["export database info"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.showPasswordStrength",
    label: "Show strength meter in export tab",
    description:
      "Render a visual strength meter as the export password is typed.",
    tags: [
      ...EXPORT_TAGS,
      "password",
      "strength",
      "meter",
      "zxcvbn",
      "feedback",
    ],
    synonyms: ["password quality", "strength bar"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.showEntropyBits",
    label: "Show estimated entropy bits",
    description:
      "Display the rough entropy of the typed password alongside the meter.",
    tags: [...EXPORT_TAGS, "entropy", "bits", "password", "strength"],
    synonyms: ["bits of entropy", "password entropy"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.enforceMinimumPasswordScore",
    label: "Block export below minimum score",
    description:
      "Refuse to export when the password is below the configured score.",
    tags: [...EXPORT_TAGS, "enforce", "minimum", "score", "block", "password"],
    synonyms: ["require strong password", "reject weak password"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.minimumPasswordScore",
    label: "Minimum password score",
    description:
      "The minimum strength score the export password must reach. Higher values make encrypted exports harder to brute-force.",
    tags: [...EXPORT_TAGS, "minimum", "score", "password", "strength"],
    synonyms: ["password score threshold"],
    values: [
      "0",
      "Very weak",
      "1",
      "Weak",
      "2",
      "Fair",
      "3",
      "Strong",
      "4",
      "Very strong",
    ],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.detectCommonPasswords",
    label: "Detect common passwords",
    description: "Penalize passwords matching well-known dictionaries.",
    tags: [...EXPORT_TAGS, "common passwords", "dictionary", "denylist"],
    synonyms: ["blocklist", "rockyou", "wordlist"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.detectRepeatedCharacters",
    label: "Detect repeated characters",
    description: "Penalize runs like aaaa or 1111.",
    tags: [...EXPORT_TAGS, "repeated", "characters", "runs", "heuristic"],
    synonyms: ["aaaa", "1111"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.detectSequentialPatterns",
    label: "Detect keyboard / numeric sequences",
    description: "Penalize qwerty, 12345, abcdef and similar sequences.",
    tags: [...EXPORT_TAGS, "sequence", "keyboard", "numeric", "heuristic"],
    synonyms: ["qwerty", "12345", "abcdef"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.rewardUncommonSymbols",
    label: "Reward uncommon symbols",
    description: "Give a small score bump for less-common punctuation.",
    tags: [...EXPORT_TAGS, "symbols", "punctuation", "bonus", "heuristic"],
    synonyms: ["special characters"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "exportSecurity.customCommonPasswords",
    label: "Additional common passwords",
    description:
      "Extra entries added to the common-password denylist. One per line or comma-separated.",
    tags: [...EXPORT_TAGS, "denylist", "custom", "common passwords", "list"],
    synonyms: ["banned passwords", "custom wordlist"],
    section: "security",
    sectionLabel: "Security",
  },

  // ─── Auto lock ──────────────────────────────────────────────────
  {
    key: "autoLock.enabled",
    label: "Enable auto lock after inactivity",
    description:
      "Lock the app when the idle timeout elapses, requiring the storage password to resume.",
    tags: ["auto lock", "idle", "inactivity", "lock", "timeout", "screensaver"],
    synonyms: ["autolock", "lock on idle", "session lock"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "autoLock.timeoutMinutes",
    label: "Auto lock timeout",
    description:
      "Number of minutes of inactivity before the application automatically locks.",
    tags: ["auto lock", "timeout", "minutes", "idle", "inactivity"],
    synonyms: ["idle timeout", "lock delay"],
    values: ["1", "240", "min", "minutes"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "autoLock.lockOnMinimize",
    label: "Lock when window is minimised",
    description:
      "Lock immediately when the application window is minimised, regardless of the idle timer.",
    tags: ["auto lock", "minimize", "minimise", "window", "lock"],
    synonyms: ["lock on minimize", "shared desktop"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "autoLock.lockOnBlur",
    label: "Lock when window loses focus",
    description:
      "Lock after 250 ms when focus moves to another application; cancelled if focus returns first.",
    tags: ["auto lock", "focus", "blur", "alt-tab", "lock"],
    synonyms: ["lock on blur", "alt tab", "focus loss"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "autoLock.lockOnVisibilityHidden",
    label: "Lock when document becomes hidden",
    description:
      "Browser-side fallback that catches any platform-specific way the window can go hidden — background tab, mission-control sweep.",
    tags: ["auto lock", "hidden", "visibility", "background", "lock"],
    synonyms: ["document.hidden", "visibilitychange", "mission control"],
    section: "security",
    sectionLabel: "Security",
  },

  // ─── Key file generation ────────────────────────────────────────
  {
    key: "sshKeyType",
    label: "Key Type",
    description:
      "Algorithm for the generated SSH key pair. Ed25519 is modern, fast and recommended; RSA 4096-bit offers broader compatibility with older servers.",
    tags: [
      "ssh",
      "key",
      "keygen",
      "ed25519",
      "rsa",
      "generate",
      "public key",
      "private key",
    ],
    synonyms: ["ssh-keygen", "id_rsa", "id_ed25519", "key pair", ".pub"],
    values: [
      "ed25519",
      "Ed25519 (Recommended)",
      "rsa",
      "RSA 4096-bit (Broad compatibility)",
    ],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "databaseKeyLength",
    label: "Key Strength",
    description:
      "Bit length of the generated database encryption key file — 256-bit suits most uses, 512-bit gives extra margin for high-security environments.",
    tags: [
      "database",
      "key file",
      "keyfile",
      "encryption",
      "256-bit",
      "512-bit",
      "generate",
    ],
    synonyms: ["collection key", "key file instead of password", "keyfile"],
    values: ["32", "256-bit (Standard)", "64", "512-bit (High Security)"],
    section: "security",
    sectionLabel: "Security",
  },

  // ─── CredSSP / NLA defaults ─────────────────────────────────────
  {
    key: "credsspDefaults.oracleRemediation",
    label: "Encryption Oracle Remediation",
    description:
      "Controls whether connections are allowed to unpatched servers vulnerable to CVE-2018-0886.",
    tags: [...CREDSSP_TAGS, "oracle", "remediation", "cve", "patch"],
    synonyms: ["cve-2018-0886", "encryption oracle", "unpatched server"],
    values: [
      "force-updated",
      "Force Updated Clients",
      "mitigated",
      "Mitigated (recommended)",
      "vulnerable",
      "Vulnerable (allow all)",
    ],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.nlaMode",
    label: "Default NLA mode",
    description:
      "Network Level Authentication mode — Required rejects if NLA is unavailable, Preferred falls back to TLS, Disabled uses TLS only.",
    tags: [...CREDSSP_TAGS, "network level authentication", "mode", "tls"],
    synonyms: ["network level authentication", "nla fallback"],
    values: [
      "required",
      "Required (reject if NLA unavailable)",
      "preferred",
      "Preferred (fallback to TLS)",
      "disabled",
      "Disabled (TLS only)",
    ],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.tlsMinVersion",
    label: "Minimum TLS version",
    description:
      "Lowest TLS protocol version the client will accept — TLS 1.2 or higher is recommended.",
    tags: [...CREDSSP_TAGS, "tls", "version", "minimum", "ssl", "protocol"],
    synonyms: ["tls1.2", "tls1.3", "min tls", "legacy tls"],
    values: [
      "1.0",
      "TLS 1.0 (legacy, insecure)",
      "1.1",
      "TLS 1.1 (deprecated)",
      "1.2",
      "TLS 1.2 (recommended)",
      "1.3",
      "TLS 1.3 (strictest)",
    ],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.credsspVersion",
    label: "CredSSP TSRequest version",
    description:
      "CredSSP protocol version — higher versions add nonce binding and other mitigations against relay attacks.",
    tags: [...CREDSSP_TAGS, "tsrequest", "version", "nonce", "relay"],
    synonyms: ["ts request", "credssp version", "client nonce"],
    values: [
      "2",
      "Version 2 (legacy)",
      "3",
      "Version 3 (with client nonce)",
      "6",
      "Version 6 (latest, with nonce binding)",
    ],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.serverCertValidation",
    label: "Server certificate validation",
    description:
      "How the client handles untrusted server certificates — Validate rejects them, Warn prompts you, Ignore accepts all.",
    tags: [...CREDSSP_TAGS, "certificate", "validation", "untrusted", "tls"],
    synonyms: ["ignore certificate errors", "accept all certificates"],
    values: [
      "validate",
      "Validate (reject untrusted)",
      "warn",
      "Warn (prompt on untrusted)",
      "ignore",
      "Ignore (accept all certificates)",
    ],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.allowHybridEx",
    label: "Allow HYBRID_EX protocol (Early User Auth Result)",
    description:
      "Enable the HYBRID_EX extension that returns authentication results before full connection setup completes.",
    tags: [...CREDSSP_TAGS, "hybrid_ex", "hybrid", "early user auth"],
    synonyms: ["hybridex", "early user authentication"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.nlaFallbackToTls",
    label: "Allow NLA fallback to TLS on failure",
    description:
      "Fall back to plain TLS authentication when Network Level Authentication negotiation fails.",
    tags: [...CREDSSP_TAGS, "fallback", "tls", "failure"],
    synonyms: ["nla fallback", "downgrade to tls"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.enforceServerPublicKeyValidation",
    label: "Enforce server public key validation during CredSSP",
    description:
      "Verify the server's public key during the CredSSP handshake to prevent man-in-the-middle attacks.",
    tags: [...CREDSSP_TAGS, "public key", "validation", "mitm", "handshake"],
    synonyms: ["man in the middle", "pubkey binding", "channel binding"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.restrictedAdmin",
    label: "Restricted Admin mode (no credential delegation)",
    description:
      "Connect without forwarding credentials to the remote server — prevents credential theft on compromised hosts.",
    tags: [...CREDSSP_TAGS, "restricted admin", "delegation", "credential"],
    synonyms: ["restrictedadmin", "no credential delegation", "pass the hash"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.remoteCredentialGuard",
    label: "Remote Credential Guard (Kerberos delegation)",
    description:
      "Kerberos-based credential delegation that keeps credentials on the local machine and never exposes them to the remote host.",
    tags: [...CREDSSP_TAGS, "credential guard", "kerberos", "delegation"],
    synonyms: ["remotecredentialguard", "credguard"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.ntlmEnabled",
    label: "NTLM",
    description:
      "NT LAN Manager authentication — widely supported legacy protocol for Windows credential exchange.",
    tags: [...CREDSSP_TAGS, "ntlm", "auth package", "windows", "legacy"],
    synonyms: ["nt lan manager", "authentication package"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.kerberosEnabled",
    label: "Kerberos",
    description:
      "Kerberos ticket-based authentication — requires a domain controller and is more secure than NTLM.",
    tags: [
      ...CREDSSP_TAGS,
      "kerberos",
      "auth package",
      "domain",
      "ticket",
      "spn",
    ],
    synonyms: ["domain controller", "krb5", "authentication package"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.pku2uEnabled",
    label: "PKU2U",
    description:
      "Public Key User-to-User protocol — allows peer-to-peer authentication without a domain controller.",
    tags: [...CREDSSP_TAGS, "pku2u", "auth package", "peer to peer"],
    synonyms: ["public key user to user", "authentication package"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "credsspDefaults.sspiPackageList",
    label: "SSPI package list override",
    description:
      "Advanced: manually specify the SSPI authentication package order — overrides the toggles above. Prefix a package with ! to exclude it.",
    tags: [...CREDSSP_TAGS, "sspi", "package list", "override", "advanced"],
    synonyms: ["!kerberos", "!pku2u", "package order"],
    section: "security",
    sectionLabel: "Security",
  },

  // ─── Password reveal ────────────────────────────────────────────
  {
    key: "passwordReveal.enabled",
    label: "Enable password reveal icon on all password fields",
    description:
      "Show an eye icon next to password fields that lets you temporarily view the password in plain text.",
    tags: ["password", "reveal", "eye", "show", "hide", "mask", "unmask"],
    synonyms: ["show password", "peek password", "eye icon"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "passwordReveal.mode",
    label: "Reveal mode",
    description:
      "Toggle shows and hides on click; Hold reveals only while the mouse button is held down.",
    tags: ["password", "reveal", "mode", "toggle", "hold", "click"],
    synonyms: ["press and hold", "click to reveal"],
    values: [
      "toggle",
      "Toggle (click to show/hide)",
      "hold",
      "Hold (hold mouse to reveal)",
    ],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "passwordReveal.autoHideSeconds",
    label: "Auto-hide after",
    description:
      "Automatically re-mask the password after this many seconds — set to 0 to keep it visible until manually hidden.",
    tags: ["password", "reveal", "auto hide", "timeout", "seconds", "mask"],
    synonyms: ["re-mask", "hide after"],
    values: ["0", "60", "s", "seconds"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "passwordReveal.showByDefault",
    label: "Show passwords by default (not recommended)",
    description:
      "Start with passwords visible instead of masked — this is a security risk and not recommended.",
    tags: ["password", "reveal", "default", "visible", "risk"],
    synonyms: ["always show passwords", "unmasked by default"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "passwordReveal.maskIcon",
    label: "Dim eye icon when password is hidden",
    description:
      "Reduce the eye icon opacity when the password is masked, providing a visual cue of the current state.",
    tags: ["password", "reveal", "icon", "opacity", "dim", "eye"],
    synonyms: ["fade eye icon"],
    section: "security",
    sectionLabel: "Security",
  },

  // ─── 2FA / TOTP defaults ────────────────────────────────────────
  {
    key: "totpEnabled",
    label: "Enable TOTP functionality",
    description:
      "Generate TOTP codes for connections that have a shared secret configured.",
    tags: [
      "2fa",
      "totp",
      "authenticator",
      "two factor",
      "mfa",
      "otp",
      "one-time password",
    ],
    synonyms: ["google authenticator", "authy", "2-factor", "second factor"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "totpIssuer",
    label: "Default issuer",
    description:
      "Issuer name shown in authenticator apps when scanning the QR code — typically your organization or app name.",
    tags: ["2fa", "totp", "issuer", "qr code", "authenticator", "label"],
    synonyms: ["otpauth issuer", "qr label"],
    values: ["sortOfRemoteNG"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "totpDigits",
    label: "Default digits",
    description:
      "Number of digits in each generated TOTP code — 6 is standard, 8 provides extra security.",
    tags: ["2fa", "totp", "digits", "length", "code", "otp"],
    synonyms: ["6 digit code", "8 digit code"],
    values: ["6", "6 digits", "8", "8 digits"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "totpPeriod",
    label: "Default period",
    description:
      "Time interval in seconds before the TOTP code rotates to a new value — 30 seconds is the most common setting.",
    tags: ["2fa", "totp", "period", "interval", "refresh", "seconds", "otp"],
    synonyms: ["code rotation", "time step"],
    values: ["15", "15 seconds", "30", "30 seconds", "60", "60 seconds"],
    section: "security",
    sectionLabel: "Security",
  },
  {
    key: "totpAlgorithm",
    label: "Default algorithm",
    description:
      "Hash algorithm used to generate TOTP codes — SHA-1 is widely compatible, SHA-256 and SHA-512 are more secure but less supported.",
    tags: ["2fa", "totp", "algorithm", "sha", "hash", "hmac", "otp"],
    synonyms: ["hmac-sha1", "sha1", "sha256", "sha512"],
    values: ["sha1", "SHA-1", "sha256", "SHA-256", "sha512", "SHA-512"],
    section: "security",
    sectionLabel: "Security",
  },
];
