import type { SettingSearchEntry } from "./types";

/**
 * Search index entries for the `sshTerminal` settings tab.
 *
 * Every `key` must match a `settingKey` / `data-setting-key` rendered by that
 * tab's section components — `tests/settings/settingsSearchDrift.test.ts`
 * enforces the join in both directions.
 *
 * Almost every label in this tab is rendered through `t(key, fallback)`, so the
 * entries carry `labelKey` / `descriptionKey`: the matcher searches the resolved
 * translation as well as the English text below, which is what makes the tab
 * findable in a non-English locale without touching any locale file.
 *
 * `values` carries both halves of every `{ value, label }` option pair. Most of
 * this tab's option lists are `.map()`s over imported constants (`BellStyles`,
 * `SSHVersions`, `CharacterSets`, `TerminalBackgroundTypes`, …), which the drift
 * guard cannot read and therefore does not check — they are transcribed here by
 * hand so that searching a value the user can see on screen actually works.
 */
export const SSH_TERMINAL_SEARCH_ENTRIES: SettingSearchEntry[] = [
  // ─── Terminal Dimensions ────────────────────────────────────────
  {
    key: "useCustomDimensions",
    label: "Use custom dimensions",
    labelKey: "settings.sshTerminal.useCustomDimensions",
    description: "Override automatic terminal size detection",
    descriptionKey: "settings.sshTerminal.useCustomDimensionsDesc",
    tags: ["dimensions", "size", "custom", "terminal", "override"],
    synonyms: ["terminal size", "window size"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "columns",
    label: "Columns",
    labelKey: "settings.sshTerminal.columns",
    description: "Number of character columns in the terminal. Standard is 80.",
    tags: ["columns", "width", "cols", "terminal", "dimensions"],
    synonyms: ["80 columns", "cols"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "rows",
    label: "Rows",
    labelKey: "settings.sshTerminal.rows",
    description: "Number of character rows in the terminal. Standard is 24.",
    tags: ["rows", "height", "lines", "terminal", "dimensions"],
    synonyms: ["24 rows"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Font Configuration ─────────────────────────────────────────
  {
    key: "useCustomFont",
    label: "Use custom font",
    labelKey: "settings.sshTerminal.useCustomFont",
    description:
      "Override default terminal font settings — specify a custom font family, size, weight, and style",
    descriptionKey: "settings.sshTerminal.useCustomFontDesc",
    tags: ["font", "custom", "typeface", "override", "terminal"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "fontFamily",
    label: "Font family",
    labelKey: "settings.sshTerminal.fontFamily",
    description:
      "CSS font family stack used for the terminal — use monospace fonts for best results.",
    tags: ["font", "family", "typeface", "monospace", "terminal"],
    synonyms: ["consolas", "monaco", "monospace", "cascadia", "fira code"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "fontSize",
    label: "Font size",
    labelKey: "settings.sshTerminal.fontSize",
    description: "Font size in pixels for the terminal text.",
    tags: ["font", "size", "pixels", "text", "terminal"],
    synonyms: ["text size", "px"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "fontWeight",
    label: "Font weight",
    labelKey: "settings.sshTerminal.fontWeight",
    description:
      "Font weight — controls how bold or light the terminal text appears.",
    tags: ["font", "weight", "bold", "light", "text"],
    values: [
      "lighter",
      "Lighter",
      "normal",
      "Normal",
      "bold",
      "Bold",
      "bolder",
      "Bolder",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "fontStyle",
    label: "Font style",
    labelKey: "settings.sshTerminal.fontStyle",
    description: "Font style — normal, italic, or oblique.",
    tags: ["font", "style", "italic", "oblique", "text"],
    values: ["normal", "Normal", "italic", "Italic", "oblique", "Oblique"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "lineHeight",
    label: "Line height",
    labelKey: "settings.sshTerminal.lineHeight",
    description: "Multiplier applied to font size to determine line height.",
    tags: ["line height", "leading", "spacing", "font", "text"],
    synonyms: ["line spacing", "leading"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "letterSpacing",
    label: "Letter spacing",
    labelKey: "settings.sshTerminal.letterSpacing",
    description: "Extra horizontal spacing between characters in pixels.",
    tags: ["letter spacing", "tracking", "kerning", "font", "text"],
    synonyms: ["tracking", "character spacing"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Color Settings ─────────────────────────────────────────────
  {
    key: "allowTerminalAnsiColors",
    label: "Allow terminal to specify ANSI colors",
    labelKey: "settings.sshTerminal.allowAnsi",
    description: "Let remote applications set the 16 standard colors",
    descriptionKey: "settings.sshTerminal.allowAnsiDesc",
    tags: ["ansi", "color", "palette", "16 colors", "terminal"],
    synonyms: ["colours", "ansi colours"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "allowXterm256Colors",
    label: "Allow xterm 256-color mode",
    labelKey: "settings.sshTerminal.allowXterm256",
    description: "Enable extended 256-color palette support",
    descriptionKey: "settings.sshTerminal.allowXterm256Desc",
    tags: ["xterm", "256 color", "palette", "color", "terminal"],
    synonyms: ["256 colours", "xterm-256color"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "allow24BitColors",
    label: "Allow 24-bit true colors",
    labelKey: "settings.sshTerminal.allow24Bit",
    description: "Enable full RGB color support (16 million colors)",
    descriptionKey: "settings.sshTerminal.allow24BitDesc",
    tags: ["24-bit", "true color", "rgb", "color", "truecolor"],
    synonyms: ["truecolor", "16 million colors", "24 bit colour"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Backgrounds, Fading & Overlays ─────────────────────────────
  {
    key: "bgEnabled",
    label: "Enable custom background",
    labelKey: "settings.sshTerminal.bg.enable",
    description:
      "Render backgrounds, fading edges, and overlay effects behind the terminal",
    descriptionKey: "settings.sshTerminal.bg.enableDesc",
    tags: ["background", "custom", "wallpaper", "effects", "terminal"],
    synonyms: ["terminal background"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgType",
    label: "Background type",
    labelKey: "settings.sshTerminal.bg.bgType",
    description:
      "Choose the kind of background: a solid color, a gradient, a static image, or an animated effect.",
    tags: ["background", "type", "solid", "gradient", "image", "animated"],
    values: [
      "none",
      "None",
      "solid",
      "Solid",
      "gradient",
      "Gradient",
      "image",
      "Image",
      "animated",
      "Animated",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgOpacity",
    label: "Background opacity",
    labelKey: "settings.sshTerminal.bg.bgOpacity",
    description:
      "Overall opacity of the background layer. Lower values make the background more transparent.",
    tags: ["background", "opacity", "transparency", "alpha"],
    synonyms: ["transparency"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgSolidColor",
    label: "Solid color",
    labelKey: "settings.sshTerminal.bg.solidColor",
    description: "The single fill color used for the terminal background.",
    tags: ["background", "solid", "color", "fill", "hex"],
    synonyms: ["solid colour", "background color"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgGradientDirection",
    label: "Direction",
    labelKey: "settings.sshTerminal.bg.direction",
    description:
      "The direction in which the gradient transitions between color stops.",
    tags: ["gradient", "direction", "radial", "conic", "background"],
    values: [
      "to-bottom",
      "to-right",
      "to-bottom-right",
      "to-bottom-left",
      "radial",
      "conic",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgGradientStops",
    label: "Gradient stops",
    labelKey: "settings.sshTerminal.bg.gradientStops",
    description:
      "Define color stops along the gradient. Each stop has a color and a position percentage.",
    tags: ["gradient", "stops", "color", "position", "background"],
    synonyms: ["add stop", "colour stops"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgImagePath",
    label: "Image path / URL",
    labelKey: "settings.sshTerminal.bg.imagePath",
    description:
      "Local file path or remote URL pointing to the background image.",
    tags: ["image", "path", "url", "background", "file", "picture"],
    synonyms: ["wallpaper", "background image"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgImageOpacity",
    label: "Image opacity",
    labelKey: "settings.sshTerminal.bg.imageOpacity",
    description:
      "Opacity of the background image. Lower values make the image more transparent.",
    tags: ["image", "opacity", "transparency", "background"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgImageBlur",
    label: "Blur",
    labelKey: "settings.sshTerminal.bg.imageBlur",
    description:
      "Gaussian blur radius in pixels applied to the background image.",
    tags: ["blur", "gaussian", "image", "background", "pixels"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgImageSize",
    label: "Size mode",
    labelKey: "settings.sshTerminal.bg.imageSize",
    description:
      "How the image is scaled to fit the terminal area. Cover fills the area; contain fits inside it.",
    tags: ["image", "size", "scale", "cover", "contain", "tile", "fill"],
    values: [
      "cover",
      "Cover",
      "contain",
      "Contain",
      "fill",
      "Fill",
      "tile",
      "Tile",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgImagePosition",
    label: "Position",
    labelKey: "settings.sshTerminal.bg.imagePosition",
    description:
      "CSS background-position value controlling where the image is anchored within the terminal.",
    tags: ["image", "position", "anchor", "background", "css"],
    synonyms: ["center center", "background position"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgAnimatedEffect",
    label: "Effect",
    labelKey: "settings.sshTerminal.bg.effect",
    description:
      "The animated visual effect rendered behind the terminal content.",
    tags: ["animated", "effect", "matrix", "starfield", "particles", "aurora"],
    synonyms: ["matrix rain", "animation"],
    values: [
      "matrix-rain",
      "Matrix Rain",
      "starfield",
      "Starfield",
      "particles",
      "Particles",
      "scanlines",
      "Scanlines",
      "noise",
      "Noise",
      "aurora",
      "Aurora",
      "rain",
      "Rain",
      "fireflies",
      "Fireflies",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgAnimSpeed",
    label: "Speed",
    labelKey: "settings.sshTerminal.bg.speed",
    description:
      "Playback speed multiplier for the animation. Higher values make the effect faster.",
    tags: ["animation", "speed", "multiplier", "background"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgAnimDensity",
    label: "Density",
    labelKey: "settings.sshTerminal.bg.density",
    description:
      "Density of animated elements on screen. Higher values produce a more populated effect.",
    tags: ["animation", "density", "particles", "background"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgAnimColor",
    label: "Color",
    labelKey: "settings.sshTerminal.bg.animColor",
    description: "Primary color used by the animated background effect.",
    tags: ["animation", "color", "background", "effect"],
    synonyms: ["animation colour"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgFadingEnabled",
    label: "Enable edge fading",
    labelKey: "settings.sshTerminal.bg.fadingEnable",
    description:
      "Gradually fade terminal edges to a transparent/colored border",
    descriptionKey: "settings.sshTerminal.bg.fadingEnableDesc",
    tags: ["fading", "edge", "fade", "border", "vignette"],
    synonyms: ["edge fading", "fade edges"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgFadingEdge",
    label: "Edge",
    labelKey: "settings.sshTerminal.bg.fadingEdge",
    description: "Which edges of the terminal to apply the fading effect to.",
    tags: ["fading", "edge", "top", "bottom", "left", "right"],
    values: [
      "none",
      "top",
      "bottom",
      "left",
      "right",
      "all",
      "top-bottom",
      "left-right",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgFadingSize",
    label: "Fade size",
    labelKey: "settings.sshTerminal.bg.fadingSize",
    description:
      "Width of the fading region in pixels from the terminal edge inward.",
    tags: ["fading", "size", "width", "pixels", "edge"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgFadingColor",
    label: "Fade color",
    labelKey: "settings.sshTerminal.bg.fadingColor",
    description:
      "The color the terminal edges fade into. Leave empty for transparent.",
    tags: ["fading", "color", "transparent", "edge"],
    synonyms: ["fade colour"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bgOverlays",
    label: "Overlays",
    labelKey: "settings.sshTerminal.bg.overlaysTitle",
    description:
      "Stack of effect layers composited over the terminal — vignette, scanlines, noise, CRT, grid, color and gradient washes, each with its own opacity and blend mode.",
    tags: ["overlay", "vignette", "scanlines", "noise", "crt", "grid", "blend"],
    synonyms: ["overlay stack", "blend mode", "crt effect", "scan lines"],
    values: [
      "color",
      "Color",
      "gradient",
      "Gradient",
      "vignette",
      "Vignette",
      "scanlines",
      "Scanlines",
      "noise",
      "Noise",
      "crt",
      "Crt",
      "grid",
      "Grid",
      "normal",
      "multiply",
      "screen",
      "overlay",
      "darken",
      "lighten",
      "color-dodge",
      "color-burn",
      "soft-light",
      "hard-light",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Character Set ──────────────────────────────────────────────
  {
    key: "characterSet",
    label: "Remote character set",
    labelKey: "settings.sshTerminal.remoteCharset",
    description:
      "The character encoding used by the remote server. Must match the server's locale to display text correctly.",
    tags: ["charset", "character set", "encoding", "locale", "codepage"],
    synonyms: ["code page", "latin1", "cyrillic", "unicode"],
    values: [
      "UTF-8",
      "ISO-8859-1",
      "ISO-8859-2",
      "ISO-8859-3",
      "ISO-8859-4",
      "ISO-8859-5",
      "ISO-8859-6",
      "ISO-8859-7",
      "ISO-8859-8",
      "ISO-8859-9",
      "ISO-8859-10",
      "ISO-8859-11",
      "ISO-8859-13",
      "ISO-8859-14",
      "ISO-8859-15",
      "ISO-8859-16",
      "Windows-1250",
      "Windows-1251",
      "Windows-1252",
      "Windows-1253",
      "Windows-1254",
      "Windows-1255",
      "Windows-1256",
      "Windows-1257",
      "Windows-1258",
      "KOI8-R",
      "KOI8-U",
      "GB2312",
      "GBK",
      "GB18030",
      "Big5",
      "Big5-HKSCS",
      "EUC-JP",
      "Shift_JIS",
      "ISO-2022-JP",
      "EUC-KR",
      "ISO-2022-KR",
      "EUC-TW",
      "TIS-620",
      "VISCII",
      "IBM437",
      "IBM850",
      "IBM852",
      "IBM855",
      "IBM857",
      "IBM860",
      "IBM861",
      "IBM862",
      "IBM863",
      "IBM864",
      "IBM865",
      "IBM866",
      "IBM869",
      "CP1006",
      "MacRoman",
      "MacCentralEuropean",
      "MacIceland",
      "MacCroatian",
      "MacTurkish",
      "MacGreek",
      "MacCyrillic",
      "MacUkrainian",
      "MacHebrew",
      "MacArabic",
      "MacThai",
      "MacJapanese",
      "MacChineseSimp",
      "MacChineseTrad",
      "MacKorean",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "unicodeAmbiguousWidth",
    label: "Unicode ambiguous width",
    labelKey: "settings.sshTerminal.unicodeWidth",
    description:
      "How wide ambiguous-width Unicode characters are rendered. East Asian locales typically use wide (2 cells).",
    tags: ["unicode", "ambiguous", "width", "cjk", "east asian", "cells"],
    synonyms: ["cjk width", "double width"],
    values: ["narrow", "Narrow (1 cell)", "wide", "Wide (2 cells)"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Line Handling ──────────────────────────────────────────────
  {
    key: "implicitCrInLf",
    label: "Implicit CR in every LF",
    labelKey: "settings.sshTerminal.implicitCrInLf",
    description: "Automatically add carriage return when receiving line feed",
    descriptionKey: "settings.sshTerminal.implicitCrInLfDesc",
    tags: ["cr", "lf", "carriage return", "line feed", "newline"],
    synonyms: ["crlf", "carriage return", "line endings"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "implicitLfInCr",
    label: "Implicit LF in every CR",
    labelKey: "settings.sshTerminal.implicitLfInCr",
    description: "Automatically add line feed when receiving carriage return",
    descriptionKey: "settings.sshTerminal.implicitLfInCrDesc",
    tags: ["lf", "cr", "line feed", "carriage return", "newline"],
    synonyms: ["crlf", "line endings"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "autoWrap",
    label: "Auto wrap mode",
    labelKey: "settings.sshTerminal.autoWrap",
    description: "Automatically wrap text at terminal edge",
    descriptionKey: "settings.sshTerminal.autoWrapDesc",
    tags: ["wrap", "auto wrap", "line wrap", "text", "terminal"],
    synonyms: ["word wrap", "line wrapping"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Line Discipline ────────────────────────────────────────────
  {
    key: "localEcho",
    label: "Local echo",
    labelKey: "settings.sshTerminal.localEcho",
    description:
      "Whether typed characters are echoed locally. Auto lets the server decide; Force On always echoes.",
    tags: ["echo", "local echo", "line discipline", "typing"],
    values: [
      "auto",
      "Auto (let server decide)",
      "on",
      "Force On",
      "off",
      "Force Off",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "localLineEditing",
    label: "Local line editing",
    labelKey: "settings.sshTerminal.localLineEditing",
    description:
      "Buffer input locally and send it all at once when Enter is pressed. Auto lets the server decide.",
    tags: ["line editing", "local", "buffer", "line discipline", "input"],
    synonyms: ["line buffering", "cooked mode"],
    values: [
      "auto",
      "Auto (let server decide)",
      "on",
      "Force On",
      "off",
      "Force Off",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Keyboard ───────────────────────────────────────────────────
  {
    key: "disableKeypadMode",
    label: "Disable keypad application mode",
    labelKey: "settings.sshTerminal.disableKeypadMode",
    description: "Force numeric keypad to always send numbers",
    descriptionKey: "settings.sshTerminal.disableKeypadModeDesc",
    tags: ["keypad", "numpad", "application mode", "keyboard", "numeric"],
    synonyms: ["numpad", "numeric keypad"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "disableApplicationCursorKeys",
    label: "Disable application cursor keys",
    labelKey: "settings.sshTerminal.disableAppCursorKeys",
    description: "Force cursor keys to always send ANSI sequences",
    descriptionKey: "settings.sshTerminal.disableAppCursorKeysDesc",
    tags: ["cursor keys", "arrow keys", "ansi", "escape", "keyboard"],
    synonyms: ["arrow keys", "escape sequences"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Scrollback & Selection ─────────────────────────────────────
  {
    key: "scrollbackLines",
    label: "Scrollback lines",
    labelKey: "settings.sshTerminal.scrollbackLines",
    description:
      "Maximum number of lines kept in the scrollback buffer. Higher values use more memory.",
    tags: ["scrollback", "buffer", "history", "lines", "memory"],
    synonyms: ["scroll back", "history buffer"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "scrollOnOutput",
    label: "Scroll on output",
    labelKey: "settings.sshTerminal.scrollOnOutput",
    description: "Automatically scroll to bottom when new output appears",
    descriptionKey: "settings.sshTerminal.scrollOnOutputDesc",
    tags: ["scroll", "output", "auto scroll", "bottom", "follow"],
    synonyms: ["autoscroll", "follow output"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "scrollOnKeystroke",
    label: "Scroll on keystroke",
    labelKey: "settings.sshTerminal.scrollOnKeystroke",
    description: "Automatically scroll to bottom when typing",
    descriptionKey: "settings.sshTerminal.scrollOnKeystrokeDesc",
    tags: ["scroll", "keystroke", "typing", "auto scroll", "bottom"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "copyOnSelect",
    label: "Copy on select",
    labelKey: "settings.sshTerminal.copyOnSelect",
    description: "Automatically copy selected text to clipboard",
    descriptionKey: "settings.sshTerminal.copyOnSelectDesc",
    tags: ["copy", "select", "clipboard", "selection", "mouse"],
    synonyms: ["auto copy", "copy on selection"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "pasteOnRightClick",
    label: "Paste on right-click",
    labelKey: "settings.sshTerminal.pasteOnRightClick",
    description: "Paste clipboard content when right-clicking",
    descriptionKey: "settings.sshTerminal.pasteOnRightClickDesc",
    tags: ["paste", "right click", "clipboard", "mouse", "context menu"],
    synonyms: ["middle click paste", "right button"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "wordSeparators",
    label: "Word separators",
    labelKey: "settings.sshTerminal.wordSeparators",
    description:
      "Characters that define word boundaries when double-clicking to select text in the terminal.",
    tags: ["word", "separator", "boundary", "double click", "selection"],
    synonyms: ["word boundaries", "double click select"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Bell Settings ──────────────────────────────────────────────
  {
    key: "bellStyle",
    label: "Bell style",
    labelKey: "settings.sshTerminal.bellStyle",
    description:
      "How the terminal bell is signaled — visually, audibly, or via a system notification.",
    tags: ["bell", "beep", "alert", "sound", "visual bell", "notification"],
    synonyms: ["terminal bell", "ctrl-g", "bel", "audible bell"],
    values: [
      "none",
      "None (disabled)",
      "system",
      "System default",
      "visual",
      "Visual bell (flash terminal)",
      "flash-window",
      "Flash window",
      "pc-speaker",
      "Beep using PC speaker",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "bellOveruseProtection",
    label: "Enable bell overuse protection",
    labelKey: "settings.sshTerminal.enableBellOveruse",
    description: "Silence the bell if it rings too frequently",
    descriptionKey: "settings.sshTerminal.bellOveruseDesc",
    tags: ["bell", "overuse", "protection", "silence", "throttle", "spam"],
    synonyms: ["bell spam", "bell throttling"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "maxBells",
    label: "Max bells",
    labelKey: "settings.sshTerminal.maxBells",
    description:
      "Number of bell rings within the time window before overuse protection kicks in.",
    tags: ["bell", "max", "count", "limit", "overuse"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "timeWindow",
    label: "Time window",
    labelKey: "settings.sshTerminal.timeWindow",
    description: "Sliding window in seconds used to count bell rings.",
    tags: ["bell", "time window", "seconds", "sliding", "overuse"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "silenceDuration",
    label: "Silence duration",
    labelKey: "settings.sshTerminal.silenceDuration",
    description: "How long the bell stays silenced after overuse is detected.",
    tags: ["bell", "silence", "duration", "mute", "seconds", "overuse"],
    synonyms: ["mute duration"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "blinkWindowOnActivity",
    label: "Blink window on activity",
    labelKey: "settings.sshTerminal.blinkOnActivity",
    description:
      "Flash the taskbar when SSH output arrives while the window is not focused",
    descriptionKey: "settings.sshTerminal.blinkOnActivityDesc",
    tags: ["blink", "window", "activity", "taskbar", "flash", "notification"],
    synonyms: ["window alert", "bounce icon"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "taskbarFlash",
    label: "Taskbar flashing",
    labelKey: "settings.sshTerminal.taskbarFlash",
    description:
      "Style of taskbar flash used to notify of activity in an unfocused terminal.",
    tags: ["taskbar", "flash", "highlight", "notification", "activity"],
    synonyms: ["dock bounce", "flash until focused"],
    values: [
      "disabled",
      "Disabled",
      "flashing",
      "Flash until focused",
      "steady",
      "Steady highlight",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── SSH Protocol Settings ──────────────────────────────────────
  {
    key: "sshVersion",
    label: "SSH version",
    labelKey: "settings.sshTerminal.sshVersion",
    description:
      "SSH protocol version to use. SSH-2 is the standard; 'SSH3' is the experimental HTTP/3-over-QUIC transport.",
    tags: ["ssh", "version", "protocol", "ssh-1", "ssh-2", "ssh3", "quic"],
    synonyms: ["ssh1", "ssh2", "http/3", "quic"],
    values: [
      "auto",
      "Auto (negotiate)",
      "1",
      "SSH-1 (legacy, insecure)",
      "2",
      "SSH-2 (standard)",
      "3",
      "SSH3 (HTTP/3 over QUIC, experimental)",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "enableCompression",
    label: "Enable SSH compression",
    labelKey: "settings.sshTerminal.enableCompression",
    description:
      "Compress data over the SSH connection (useful for slow links)",
    descriptionKey: "settings.sshTerminal.enableCompressionDesc",
    tags: ["compression", "zlib", "bandwidth", "ssh", "slow link"],
    synonyms: ["zlib", "compress"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "compressionLevel",
    label: "Compression level",
    labelKey: "settings.sshTerminal.compressionLevel",
    description:
      "Compression strength from 1 (fastest, least compression) to 9 (slowest, best compression).",
    tags: ["compression", "level", "zlib", "strength", "1", "9"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Low-level TCP Options ──────────────────────────────────────
  {
    key: "tcpNoDelay",
    label: "Disable Nagle algorithm (TCP_NODELAY)",
    labelKey: "settings.sshTerminal.tcpNoDelay",
    description: "Send data immediately without buffering small packets",
    descriptionKey: "settings.sshTerminal.tcpNoDelayDesc",
    tags: ["tcp", "nodelay", "nagle", "latency", "socket", "packets"],
    synonyms: ["tcp nodelay", "nagle algorithm"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "sshTcpKeepAlive",
    label: "Enable TCP keepalive",
    labelKey: "settings.sshTerminal.tcpKeepAlive",
    description:
      "Send TCP keepalive probes to detect dead connections, with a configurable SO_KEEPALIVE option, probe interval, and probe count",
    descriptionKey: "settings.sshTerminal.tcpKeepAliveDesc",
    tags: ["tcp", "keepalive", "keep-alive", "probe", "interval", "dead"],
    synonyms: [
      "keep alive",
      "so_keepalive",
      "keepalive interval",
      "keepalive probes",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "ipProtocol",
    label: "IP protocol",
    labelKey: "settings.sshTerminal.ipProtocol",
    description:
      "Preferred IP protocol version. Auto will try IPv4 first, then fall back to IPv6.",
    tags: ["ip", "protocol", "ipv4", "ipv6", "network", "address family"],
    synonyms: ["ip version", "address family"],
    values: ["auto", "Auto (IPv4/IPv6)", "ipv4", "IPV4", "ipv6", "IPV6"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "connectionTimeout",
    label: "Connection timeout",
    labelKey: "settings.sshTerminal.connectionTimeout",
    description:
      "Maximum time in seconds to wait for a TCP connection to be established before giving up.",
    tags: ["connection", "timeout", "connect", "seconds", "tcp"],
    synonyms: ["connect timeout"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Advanced SSH Options ───────────────────────────────────────
  {
    key: "preferredCiphers",
    label: "Preferred Ciphers",
    labelKey: "settings.sshTerminal.preferredCiphers",
    description:
      "Ordered list of SSH transport ciphers offered during key exchange. Items are tried in order of preference.",
    tags: ["cipher", "encryption", "aes", "chacha20", "ctr", "gcm", "cbc"],
    synonyms: ["encryption algorithms", "symmetric cipher"],
    values: [
      "chacha20-poly1305@openssh.com",
      "aes256-gcm@openssh.com",
      "aes128-gcm@openssh.com",
      "aes256-ctr",
      "aes192-ctr",
      "aes128-ctr",
      "aes256-cbc",
      "aes192-cbc",
      "aes128-cbc",
      "3des-cbc",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "preferredMACs",
    label: "Preferred MACs",
    labelKey: "settings.sshTerminal.preferredMACs",
    description:
      "Ordered list of message authentication codes offered during key exchange. Encrypt-then-MAC variants are preferred.",
    tags: ["mac", "hmac", "umac", "sha2", "integrity", "etm", "md5"],
    synonyms: ["message authentication code", "encrypt then mac"],
    values: [
      "hmac-sha2-256-etm@openssh.com",
      "hmac-sha2-512-etm@openssh.com",
      "umac-128-etm@openssh.com",
      "umac-64-etm@openssh.com",
      "hmac-sha2-256",
      "hmac-sha2-512",
      "umac-128@openssh.com",
      "umac-64@openssh.com",
      "hmac-sha1",
      "hmac-md5",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "preferredKeyExchanges",
    label: "Preferred Key Exchanges",
    labelKey: "settings.sshTerminal.preferredKEX",
    description:
      "Ordered list of key exchange algorithms offered to the server. Items are tried in order of preference.",
    tags: ["kex", "key exchange", "curve25519", "ecdh", "diffie-hellman"],
    synonyms: ["kex algorithms", "dh group", "post quantum", "sntrup761"],
    values: [
      "sntrup761x25519-sha512@openssh.com",
      "curve25519-sha256",
      "curve25519-sha256@libssh.org",
      "ecdh-sha2-nistp256",
      "ecdh-sha2-nistp384",
      "ecdh-sha2-nistp521",
      "diffie-hellman-group16-sha512",
      "diffie-hellman-group18-sha512",
      "diffie-hellman-group-exchange-sha256",
      "diffie-hellman-group14-sha256",
      "diffie-hellman-group14-sha1",
      "diffie-hellman-group1-sha1",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "preferredHostKeyAlgorithms",
    label: "Preferred Host Key Algorithms",
    labelKey: "settings.sshTerminal.preferredHostKeys",
    description:
      "Ordered list of host key algorithms accepted when verifying the server's identity.",
    tags: ["host key", "ed25519", "rsa", "ecdsa", "dss", "certificate"],
    synonyms: ["hostkey", "server key", "host key algorithms"],
    values: [
      "ssh-ed25519",
      "ssh-ed25519-cert-v01@openssh.com",
      "rsa-sha2-512",
      "rsa-sha2-512-cert-v01@openssh.com",
      "rsa-sha2-256",
      "rsa-sha2-256-cert-v01@openssh.com",
      "ecdsa-sha2-nistp256",
      "ecdsa-sha2-nistp384",
      "ecdsa-sha2-nistp521",
      "ssh-rsa",
      "ssh-dss",
    ],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },

  // ─── Miscellaneous ──────────────────────────────────────────────
  {
    key: "answerbackString",
    label: "Answerback string",
    labelKey: "settings.sshTerminal.answerback",
    description:
      "Terminal identification string sent to the remote host in response to an ENQ character.",
    tags: ["answerback", "enq", "identification", "terminal", "string"],
    synonyms: ["enq", "terminal id"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "localPrinting",
    label: "Enable local printing",
    labelKey: "settings.sshTerminal.localPrinting",
    description: "Allow print commands from terminal",
    descriptionKey: "settings.sshTerminal.localPrintingDesc",
    tags: ["printing", "printer", "local", "escape sequence", "print"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
  {
    key: "remoteControlledPrinting",
    label: "Enable remote-controlled printing",
    labelKey: "settings.sshTerminal.remotePrinting",
    description: "Allow remote host to trigger printing",
    descriptionKey: "settings.sshTerminal.remotePrintingDesc",
    tags: ["printing", "printer", "remote", "escape sequence", "print"],
    section: "sshTerminal",
    sectionLabel: "SSH Terminal",
  },
];
