import type { SettingSearchEntry } from "./types";

/**
 * Search index entries for the `theme` settings tab.
 *
 * Every `key` must match a `settingKey` / `data-setting-key` rendered by that
 * tab's section components — `tests/settings/settingsSearchDrift.test.ts`
 * enforces the join in both directions.
 */

/** `Themes` (`src/types/settings/settings.ts`) as the picker renders them. */
const THEME_VALUES = [
  "dark",
  "Dark",
  "light",
  "Light",
  "auto",
  "Auto",
  "darkest",
  "Darkest",
  "oled",
  "Oled",
  "OLED",
  "semilight",
  "Semilight",
] as const;

/** `ColorSchemes` — the accent swatch grid. */
const COLOR_SCHEME_VALUES = [
  "red",
  "rose",
  "pink",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "slate",
  "grey",
  "custom",
] as const;

/** `ALL_LOADING_ELEMENT_TYPES` — the loader variants the browser cycles. */
const LOADER_TYPE_VALUES = [
  "ring",
  "Ring",
  "dotPulse",
  "Dot Pulse",
  "cometTrails",
  "Comet Trails",
  "hologram",
  "Hologram",
  "particleStorm",
  "Particle Storm",
  "wavyDensity",
  "Wavy Density",
  "doubleHelix",
  "Double Helix",
  "lissajous",
  "Lissajous",
  "ripplingSpiral",
  "Rippling Spiral",
  "pulsingBands",
  "Pulsing Bands",
  "auroraBloom",
  "Aurora Bloom",
  "rippleSphere",
  "Ripple Sphere",
  "fibonacciSphere",
  "Fibonacci Sphere",
  "plasmaNoise",
  "Plasma Noise",
  "orbitalShells",
  "Orbital Shells",
  "vortex",
  "Vortex",
  "tvStatic",
  "TV Static",
  "phyllotaxis",
  "Phyllotaxis",
  "icosahedron",
  "Icosahedron",
] as const;

export const THEME_SEARCH_ENTRIES: SettingSearchEntry[] = [
  // ─── Appearance ─────────────────────────────────────────────────
  {
    key: "theme",
    label: "Theme",
    labelKey: "settings.theme",
    description:
      "Base color theme that controls the overall look and feel of the application.",
    descriptionKey: "themeSettings.baseThemeTooltip",
    tags: [
      "theme",
      "dark mode",
      "light mode",
      "dark theme",
      "light theme",
      "appearance",
      "colors",
      "skin",
      "night mode",
    ],
    synonyms: ["colour theme", "look and feel", "amoled", "black theme"],
    values: [...THEME_VALUES],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "colorScheme",
    label: "Color Scheme",
    labelKey: "themeSettings.colorScheme",
    description:
      "Preset color scheme that defines the primary accent colors used throughout the UI.",
    descriptionKey: "themeSettings.colorSchemeTooltip",
    tags: ["colors", "palette", "accent", "scheme", "swatch", "hue"],
    synonyms: ["colour scheme", "accent palette", "tint"],
    values: [...COLOR_SCHEME_VALUES],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "useCustomAccent",
    label: "Custom Accent",
    labelKey: "themeSettings.customAccent",
    description: "Replace the preset scheme with any color you pick.",
    descriptionKey: "themeSettings.customAccentDescription",
    tags: ["accent", "custom", "color", "override", "brand"],
    synonyms: ["custom colour", "own accent color"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "primaryAccentColor",
    label: "Accent Color",
    labelKey: "themeSettings.accentColor",
    description:
      "The custom color used as the primary accent throughout the UI when Custom Accent is enabled.",
    descriptionKey: "themeSettings.accentColorTooltip",
    tags: ["color", "accent", "tint", "primary", "hex", "picker"],
    synonyms: ["accent colour", "primary color", "hex color"],
    values: ["#3b82f6", "hex"],
    section: "theme",
    sectionLabel: "Theme",
  },

  // ─── Background glow ────────────────────────────────────────────
  {
    key: "backgroundGlowEnabled",
    label: "Enable background glow effect",
    labelKey: "themeSettings.enableBackgroundGlow",
    description: "Add a soft radial glow behind the main content area.",
    descriptionKey: "themeSettings.enableBackgroundGlowDescription",
    tags: ["glow", "ambient", "effect", "background", "radial", "bloom"],
    synonyms: ["background light", "halo", "ambient glow"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "backgroundGlowFollowsColorScheme",
    label: "Glow follows color scheme",
    labelKey: "themeSettings.glowFollowsColorScheme",
    description: "Auto-tint the glow to match the selected color scheme.",
    descriptionKey: "themeSettings.glowFollowsColorSchemeDescription",
    tags: ["glow", "color scheme", "auto", "tint", "match", "follow"],
    synonyms: ["auto glow colour", "glow tint"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "backgroundGlowColor",
    label: "Glow Color",
    labelKey: "themeSettings.glowColor",
    description:
      "The color of the background glow effect. Disabled when 'Glow follows color scheme' is on.",
    descriptionKey: "themeSettings.glowColorTooltip",
    tags: ["glow", "color", "background", "hex"],
    synonyms: ["glow colour", "glow tint"],
    values: ["#2563eb", "hex"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "backgroundGlowOpacity",
    label: "Glow Opacity",
    labelKey: "themeSettings.glowOpacity",
    description:
      "How visible the glow effect is (0 = invisible, 1 = fully opaque).",
    descriptionKey: "themeSettings.glowOpacityTooltip",
    tags: ["glow", "opacity", "alpha", "visibility", "intensity"],
    synonyms: ["glow strength", "glow alpha"],
    values: ["0", "1"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "backgroundGlowRadius",
    label: "Glow Radius",
    labelKey: "themeSettings.glowRadius",
    description: "The size of the glow circle in pixels.",
    descriptionKey: "themeSettings.glowRadiusTooltip",
    tags: ["glow", "radius", "size", "px", "pixels"],
    synonyms: ["glow size", "glow spread"],
    values: ["200", "1200", "px"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "backgroundGlowBlur",
    label: "Glow Blur",
    labelKey: "themeSettings.glowBlur",
    description: "How much the glow is blurred at the edges in pixels.",
    descriptionKey: "themeSettings.glowBlurTooltip",
    tags: ["glow", "blur", "soften", "edges", "px", "pixels"],
    synonyms: ["glow softness", "feather"],
    values: ["40", "320", "px"],
    section: "theme",
    sectionLabel: "Theme",
  },

  // ─── Window transparency ────────────────────────────────────────
  {
    key: "windowTransparencyEnabled",
    label: "Enable window transparency",
    labelKey: "themeSettings.enableTransparency",
    description:
      "Make the application window semi-transparent so the desktop shows through. Experimental.",
    descriptionKey: "themeSettings.enableTransparencyDescription",
    tags: [
      "transparent",
      "transparency",
      "opacity",
      "glass",
      "blur",
      "acrylic",
      "mica",
      "experimental",
      "see through",
    ],
    synonyms: ["translucent window", "window opacity", "frosted glass"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "windowTransparencyOpacity",
    label: "Opacity Level",
    labelKey: "themeSettings.opacityLevel",
    description:
      "Controls how transparent the window is (0 = fully transparent, 1 = fully opaque).",
    descriptionKey: "themeSettings.opacityLevelTooltip",
    tags: ["opacity", "alpha", "transparent", "transparency", "level"],
    synonyms: ["window alpha", "translucency level"],
    values: ["0", "1"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "showTransparencyToggle",
    label: "Show transparency toggle in title bar",
    labelKey: "themeSettings.showTransparencyToggle",
    description: "Add a quick-toggle button to the window title bar.",
    descriptionKey: "themeSettings.showTransparencyToggleDescription",
    tags: ["title bar", "titlebar", "toggle", "transparency", "shortcut"],
    synonyms: ["quick toggle", "window chrome button"],
    section: "theme",
    sectionLabel: "Theme",
  },

  // ─── Animations ─────────────────────────────────────────────────
  {
    key: "animationsEnabled",
    label: "Enable animations and transitions",
    labelKey: "settings.theme.enableAnimations",
    description: "Master switch for every UI animation and transition.",
    descriptionKey: "themeSettings.animationsDescription",
    tags: ["animation", "animations", "motion", "transitions", "effects"],
    synonyms: ["ui animation", "disable animations"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "reduceMotion",
    label: "Reduce motion (minimal animations)",
    labelKey: "settings.theme.reduceMotion",
    description:
      "Use subtle animations only — better for motion sensitivity and accessibility.",
    descriptionKey: "themeSettings.reduceMotionDescription",
    tags: [
      "accessibility",
      "a11y",
      "motion",
      "reduce",
      "vestibular",
      "prefers-reduced-motion",
    ],
    synonyms: ["motion sickness", "less animation"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "enableTabGroupAnimations",
    label: "Animate the Tab Group Manager",
    labelKey: "settings.theme.tabGroupAnimations",
    description:
      "Fade and slide groups as they are added, removed, searched, or filtered.",
    descriptionKey: "themeSettings.tabGroupAnimationsDescription",
    tags: ["tab group", "animation", "fade", "slide", "manager", "filter"],
    synonyms: ["tab group manager animation"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "animationDuration",
    label: "Animation duration",
    labelKey: "settings.theme.animationDuration",
    description:
      "Base duration for animations in milliseconds; lower values feel snappier.",
    descriptionKey: "themeSettings.animationDurationTooltip",
    tags: ["animation", "duration", "speed", "ms", "milliseconds", "timing"],
    synonyms: ["animation speed", "transition duration"],
    values: ["50", "500", "ms"],
    section: "theme",
    sectionLabel: "Theme",
  },

  // ─── Loading element ────────────────────────────────────────────
  {
    key: "loadingElement.defaultType",
    label: "Loader type",
    description:
      "The global loading element variant used everywhere the app shows a spinner.",
    tags: ["loader", "loading", "spinner", "throbber", "variant", "animation"],
    synonyms: ["loading indicator", "busy indicator", "progress spinner"],
    values: [...LOADER_TYPE_VALUES],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.preset",
    label: "Loader preset",
    description:
      "Apply a bundled parameter preset to the selected loader, or keep the current custom configuration.",
    tags: ["loader", "preset", "loading", "spinner", "custom"],
    synonyms: ["loading preset", "spinner preset"],
    values: ["__custom__", "Custom (current)"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.variantParameters",
    label: "Loader parameters",
    description:
      "Per-variant tuning for the selected loader — arm counts, speeds, densities, colors and other schema-driven fields.",
    tags: ["loader", "parameters", "tuning", "config", "variant", "advanced"],
    synonyms: ["loader settings", "spinner parameters"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.followsAccentColor",
    label: "Follow accent color",
    description:
      "Use the active theme accent color for the loader instead of a custom color.",
    tags: ["loader", "accent", "color", "follow", "theme"],
    synonyms: ["loader accent colour"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.customColor",
    label: "Loader custom color",
    description:
      "Color used for the loading element when 'Follow accent color' is off.",
    tags: ["loader", "color", "custom", "hex"],
    synonyms: ["loader colour", "spinner color"],
    values: ["#00f0ff", "hex"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.sizeScale",
    label: "Loader size scale",
    description:
      "Global multiplier applied on top of the size each call site requests. 1 = no change, 0.5 = half, 2 = double.",
    tags: ["loader", "size", "scale", "multiplier", "zoom"],
    synonyms: ["spinner size", "loader scale"],
    values: ["0.5", "1", "2"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.glowIntensity",
    label: "Loader glow intensity",
    description:
      "Global drop-shadow halo applied on top of the variant's own glow. 0 disables the extra glow entirely; 3 is heavy bloom.",
    tags: ["loader", "glow", "intensity", "bloom", "halo", "drop shadow"],
    synonyms: ["spinner glow"],
    values: ["0", "3"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.glowColor",
    label: "Loader glow color",
    description:
      "Color of the drop-shadow halo. Leave empty to follow the loader color.",
    tags: ["loader", "glow", "color", "halo", "hex"],
    synonyms: ["glow colour", "match loader"],
    values: ["#00f0ff", "Match loader", "hex"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.renderMode",
    label: "Loader render mode",
    description:
      "Force DOM or canvas rendering, or let the loader pick automatically based on size and complexity.",
    tags: ["loader", "render", "dom", "canvas", "auto", "gpu", "performance"],
    synonyms: ["rendering mode", "draw mode"],
    values: ["auto", "Auto", "dom", "DOM", "canvas", "Canvas"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.reducedMotionMode",
    label: "Loader reduced motion",
    description:
      "How loaders behave when reduced motion is active — Auto follows the OS preference, Static freezes a single frame, Pause stops the animation entirely.",
    tags: [
      "loader",
      "reduced motion",
      "accessibility",
      "a11y",
      "static",
      "pause",
    ],
    synonyms: ["prefers-reduced-motion", "freeze animation"],
    values: [
      "auto",
      "Auto (follow OS)",
      "static",
      "Static frame",
      "pause",
      "Pause animation",
    ],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.pauseWhenOffScreen",
    label: "Pause when off-screen",
    description:
      "Suspend loader animation when it is scrolled out of view, saving CPU and GPU.",
    tags: ["loader", "pause", "offscreen", "viewport", "cpu", "gpu", "battery"],
    synonyms: ["suspend when hidden", "scroll out of view"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.pauseWhenWindowHidden",
    label: "Pause when window is hidden",
    description:
      "Suspend loader animation when the application window is minimized or otherwise hidden.",
    tags: [
      "loader",
      "pause",
      "minimized",
      "hidden",
      "background",
      "cpu",
      "battery",
    ],
    synonyms: ["minimised", "window hidden"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.precomputed.outputSizePx",
    label: "Fallback asset output size",
    description:
      "Pixel dimensions of the generated animated WebP fallback assets.",
    tags: ["loader", "fallback", "webp", "size", "px", "precomputed", "asset"],
    synonyms: ["asset resolution", "output resolution"],
    values: [
      "48",
      "48 px",
      "64",
      "64 px",
      "96",
      "96 px",
      "128",
      "128 px",
      "192",
      "192 px",
    ],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.precomputed.frameRate",
    label: "Fallback asset frame rate",
    description:
      "Frames per second baked into each precomputed animated WebP asset.",
    tags: ["loader", "fallback", "fps", "frame rate", "webp", "precomputed"],
    synonyms: ["frames per second", "framerate"],
    values: ["24", "24 fps", "30", "30 fps", "60", "60 fps"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.precomputed.durationSeconds",
    label: "Fallback asset duration",
    description:
      "Loop length in seconds. Longer loops capture more animation but increase the asset size.",
    tags: ["loader", "fallback", "duration", "loop", "seconds", "precomputed"],
    synonyms: ["loop length"],
    values: ["0.5", "6", "s", "seconds"],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.precomputed.mode",
    label: "Fallback mode",
    description:
      "When precomputed assets should be used instead of the live loader.",
    tags: ["loader", "fallback", "mode", "precomputed", "low power"],
    synonyms: ["asset fallback"],
    values: [
      "never",
      "Never",
      "whenUnavailable",
      "When unavailable",
      "always",
      "Always",
    ],
    section: "theme",
    sectionLabel: "Theme",
  },
  {
    key: "loadingElement.precomputed.generate",
    label: "Generate fallback assets",
    description:
      "Generate all, generate only missing, or clear the precomputed animated WebP loader assets.",
    tags: [
      "loader",
      "generate",
      "precompute",
      "webp",
      "clear",
      "regenerate",
      "assets",
    ],
    synonyms: ["generate all", "generate missing", "clear all"],
    values: ["Generate all", "Generate missing", "Clear all"],
    section: "theme",
    sectionLabel: "Theme",
  },

  // ─── Custom CSS ─────────────────────────────────────────────────
  {
    key: "customCss",
    label: "Custom CSS",
    labelKey: "settings.theme.customCss",
    description:
      "Custom CSS rules that override any application style for advanced personalization.",
    descriptionKey: "themeSettings.customCssTooltip",
    tags: ["css", "style", "stylesheet", "custom", "override", "userstyle"],
    synonyms: ["user css", "custom styles", "userstyles"],
    section: "theme",
    sectionLabel: "Theme",
  },
];
