import type { ConnectionEditorSearchDescriptor } from "../../connection/editor/editorRegistry";

const protocols = ["winrm"] as const;

export const POWERSHELL_REMOTING_CONNECTION_EDITOR_SEARCH_DESCRIPTOR = {
  id: "powershell-remoting-options",
  tabId: "protocol",
  label: "PowerShell Remoting settings",
  keywords: ["powershell", "remoting", "psrp", "wsman", "winrm", "winrs"],
  copy: [
    "PowerShell Remoting keeps the persisted winrm protocol key for compatibility.",
    "Unavailable backend capabilities remain disabled and fail closed.",
  ],
  connectionOnly: true,
  fields: [
    {
      id: "powershell-endpoint",
      label: "Transport",
      keywords: ["endpoint", "WSMan", "PowerShell over SSH"],
      optionText: ["WSMan (WinRS process shell)", "PowerShell over SSH"],
      valuePaths: ["powerShellRemoting.transport"],
      protocols,
      protocolSubtabId: "connection",
    },
    {
      id: "powershell-wsman-scheme",
      label: "WSMan scheme",
      optionText: ["HTTPS (recommended)", "HTTP"],
      valuePaths: ["powerShellRemoting.wsman.scheme"],
      protocols,
      protocolSubtabId: "connection",
    },
    {
      id: "powershell-wsman-port",
      label: "Port",
      keywords: ["5985", "5986"],
      valuePaths: ["powerShellRemoting.wsman.port"],
      protocols,
      protocolSubtabId: "connection",
    },
    {
      id: "powershell-wsman-path",
      label: "WSMan path",
      keywords: ["/wsman"],
      valuePaths: ["powerShellRemoting.wsman.path"],
      protocols,
      protocolSubtabId: "connection",
    },
    {
      id: "powershell-connection-uri",
      label: "Connection URI override",
      keywords: ["canonical endpoint", "URL"],
      valuePaths: ["powerShellRemoting.wsman.connectionUri"],
      protocols,
      protocolSubtabId: "connection",
    },
    {
      id: "powershell-configuration",
      label: "PowerShell configuration",
      keywords: ["configuration name", "microsoft.powershell"],
      valuePaths: ["powerShellRemoting.wsman.configurationName"],
      protocols,
      protocolSubtabId: "connection",
    },
    {
      id: "powershell-credential-source",
      label: "Credential source",
      optionText: [
        "Prompt on connect",
        "Saved encrypted credential",
        "External vault",
      ],
      valuePaths: ["powerShellRemoting.credential.source"],
      protocols,
      protocolSubtabId: "authentication",
    },
    {
      id: "powershell-authentication-method",
      label: "Authentication method",
      keywords: ["Negotiate", "Kerberos", "NTLM", "Basic", "CredSSP"],
      valuePaths: ["powerShellRemoting.wsman.authMethod"],
      protocols,
      protocolSubtabId: "authentication",
    },
    {
      id: "powershell-username",
      label: "Username",
      valuePaths: ["powerShellRemoting.credential.username"],
      protocols,
      protocolSubtabId: "authentication",
    },
    {
      id: "powershell-domain",
      label: "Domain",
      valuePaths: ["powerShellRemoting.credential.domain"],
      protocols,
      protocolSubtabId: "authentication",
    },
    {
      id: "powershell-saved-credential",
      label: "Saved credential",
      keywords: ["encrypted credential", "credential reference"],
      valuePaths: ["powerShellRemoting.credential.savedCredentialId"],
      protocols,
      protocolSubtabId: "authentication",
    },
    {
      id: "powershell-tls-trust",
      label: "Server certificate trust",
      keywords: ["system trust", "TOFU", "pinned fingerprint"],
      valuePaths: ["powerShellRemoting.wsman.tls.trustMode"],
      protocols,
      protocolSubtabId: "security",
    },
    {
      id: "powershell-certificate-fingerprint",
      label: "Pinned certificate fingerprint",
      valuePaths: ["powerShellRemoting.wsman.tls.pinnedFingerprint"],
      protocols,
      protocolSubtabId: "security",
    },
    {
      id: "powershell-network-path",
      label: "Network Path",
      keywords: ["proxy", "route", "fail closed", "backend adapter"],
      copy: [
        "Configured PowerShell routes are blocked until a backend adapter is available.",
      ],
      valuePaths: [
        "powerShellRemoting.networkPath",
        "powerShellRemoting.wsman.proxy",
      ],
      protocols,
      protocolSubtabId: "network-path",
    },
    {
      id: "powershell-ssh-settings",
      label: "PowerShell over SSH",
      keywords: ["subsystem", "host key", "agent", "private key"],
      valuePaths: ["powerShellRemoting.ssh"],
      protocols,
      protocolSubtabId: "advanced",
    },
    {
      id: "powershell-session",
      label: "Session",
      keywords: ["timeout", "reconnect", "buffering", "received data"],
      valuePaths: ["powerShellRemoting.session"],
      protocols,
      protocolSubtabId: "advanced",
    },
    {
      id: "powershell-windows-tools",
      label: "Windows management tools",
      keywords: ["WMI", "separate WinRM settings"],
      valuePaths: ["powerShellRemoting.windowsTools"],
      protocols,
      protocolSubtabId: "advanced",
    },
  ],
} as const satisfies ConnectionEditorSearchDescriptor;
