import type { ConnectionIconKey } from "./connectionIconCatalog";

/** Suggestions only. Existing saved custom icon choices are never overwritten. */
export const HOSTED_DASHBOARD_ICON_SUGGESTIONS = {
  namecheap: "namecheap",
  "network-solutions": "network-solutions",
  time4vps: "time4vps",
  contabo: "contabo",
  chatgpt: "bot",
  claude: "claude",
  openrouter: "openrouter",
  "gitlab-com": "gitlab-ci",
  "gitlab-self-hosted": "gitlab-ci",
  "google-account": "google",
  "google-cloud-console": "googlecloud",
  "google-analytics": "google-analytics",
  "google-business-profile": "google",
  "google-search-console": "google-search-console",
  "google-ads": "google-ads",
  facebook: "facebook",
  instagram: "instagram",
  "hpe-greenlake": "hpe",
  adobe: "adobe",
  youtube: "youtube",
  zoom: "zoom",
  icloud: "icloud",
  ovhcloud: "ovh",
  ptisp: "ptisp",
  marcaria: "marcaria",
  freedns: "freedns",
  "registro-br": "registro-br",
  sqlpad: "sqlpad",
  "eaton-ups": "eaton",
  gmail: "gmail",
  "outlook-online": "microsoft",
  "exchange-owa": "exchange",
  ddwrt: "ddwrt",
  freshtomato: "freshtomato",
} as const satisfies Readonly<Record<string, ConnectionIconKey>>;
