import type { ConnectionIconKey } from "./connectionIconCatalog";

/** Display suggestions only; never replace a saved/custom icon on selection. */
export const PORTAL_APPLICATION_ICON_SUGGESTIONS = {
  "youtube-studio": "youtube",
  "google-ad-manager": "google",
  "google-adsense": "google",
  "google-forms": "google",
  "google-gemini": "bot",
  "google-workspace-admin": "google",
  "google-play-store": "android",
  "google-developers": "google",
  "google-play-console": "android",
  "cegid-primavera": "primavera",
  "autoridade-tributaria": "building-government",
  "seguranca-social-direta": "people",
  "irn-online": "building-government",
  "e-redes": "lightning",
  "meo-particulares": "meo",
  "meo-empresas": "meo",
  "vodafone-portugal": "vodafone",
  "digi-portugal": "digi",
  "imt-online": "vehicle",
  "via-verde": "vehicle",
  "uzo-particulares": "uzo",
  "apple-account": "apple",
  "apple-developer": "apple",
  "register-com": "network-solutions",
  "no-ip": "noip",
  "microsoft-account": "microsoft",
  "microsoft-developer": "microsoft",
  "hpe-support": "hpe",
  notion: "file-text",
  zulip: "zulip",
  arlo: "camera",
  "uptime-kuma": "activity",
  steam: "web-application",
  autodesk: "autodesk",
  kimi: "bot",
  lovable: "code",
  npm: "package",
  pypi: "python",
  reddit: "web-application",
  tesla: "vehicle",
  ebay: "web-application",
  x: "web-application",
  wazuh: "wazuh",
  zabbix: "activity",
  opnsense: "opnsense",
} as const satisfies Readonly<Record<string, ConnectionIconKey>>;
