// @generated by scripts/sync-js-deps.mjs from package.json and package-lock.json.
// Do not edit manually; run `npm run about:js-deps:generate`.

use crate::types::{DependencyCategory, DependencyInfo};
use std::collections::HashMap;

#[rustfmt::skip]
const PRODUCTION_DEPS: &[(&str, &str, &str, &str)] = &[
    ("@tauri-apps/api", "2.11.1", "Apache-2.0 OR MIT", "Tauri Integration"),
    ("@tauri-apps/plugin-dialog", "2.7.2", "MIT OR Apache-2.0", "Tauri Integration"),
    ("@tauri-apps/plugin-fs", "2.5.1", "MIT OR Apache-2.0", "Tauri Integration"),
    ("@xterm/addon-fit", "0.11.0", "MIT", "Terminal Emulation"),
    ("@xterm/addon-web-links", "0.12.0", "MIT", "Terminal Emulation"),
    ("@xterm/xterm", "6.0.0", "MIT", "Terminal Emulation"),
    ("gifenc", "1.0.3", "MIT", "Media"),
    ("i18next", "26.3.6", "MIT", "Internationalization"),
    ("i18next-browser-languagedetector", "8.2.1", "MIT", "Internationalization"),
    ("idb", "8.0.3", "ISC", "Storage"),
    ("ipaddr.js", "2.5.0", "MIT", "Networking"),
    ("jsqr", "1.4.0", "Apache-2.0", "Cryptography & Auth"),
    ("lucide-react", "1.31.0", "ISC", "React & UI"),
    ("next", "16.3.0", "MIT", "Next.js"),
    ("qrcode", "1.5.4", "MIT", "Cryptography & Auth"),
    ("react", "19.2.8", "MIT", "React & UI"),
    ("react-dom", "19.2.8", "MIT", "React & UI"),
    ("react-i18next", "17.0.11", "MIT", "React & UI"),
    ("webssh2-frontend", "1.0.3", "MIT", "Remote Desktop & SSH"),
];

#[rustfmt::skip]
const DEV_DEPS: &[(&str, &str, &str, &str)] = &[
    ("@eslint/js", "10.0.1", "MIT", "Linting"),
    ("@next/eslint-plugin-next", "16.3.0", "MIT", "Next.js"),
    ("@tailwindcss/postcss", "4.3.3", "MIT", "CSS & Styling"),
    ("@tauri-apps/cli", "2.11.4", "Apache-2.0 OR MIT", "Tauri Integration"),
    ("@testing-library/dom", "10.4.1", "MIT", "Testing"),
    ("@testing-library/jest-dom", "6.9.1", "MIT", "Testing"),
    ("@testing-library/react", "16.3.2", "MIT", "Testing"),
    ("@types/node", "24.13.3", "MIT", "Type Definitions"),
    ("@types/qrcode", "1.5.6", "MIT", "Type Definitions"),
    ("@types/react", "19.2.18", "MIT", "Type Definitions"),
    ("@types/react-dom", "19.2.4", "MIT", "Type Definitions"),
    ("@vitejs/plugin-react", "6.0.5", "MIT", "Build Tooling"),
    ("@vitest/coverage-v8", "4.1.6", "MIT", "Testing"),
    ("@wdio/cli", "9.27.1", "MIT", "Testing"),
    ("@wdio/local-runner", "9.27.1", "MIT", "Testing"),
    ("@wdio/mocha-framework", "9.29.1", "MIT", "Testing"),
    ("@wdio/spec-reporter", "9.27.1", "MIT", "Testing"),
    ("@wdio/tauri-service", "1.2.0", "MIT", "Testing"),
    ("@wdio/types", "9.27.1", "MIT", "Testing"),
    ("@webgpu/types", "0.1.71", "BSD-3-Clause", "TypeScript"),
    ("autoprefixer", "10.5.4", "MIT", "CSS & Styling"),
    ("eslint", "10.8.1", "MIT", "Linting"),
    ("eslint-plugin-react-hooks", "7.1.1", "MIT", "Linting"),
    ("eslint-plugin-react-refresh", "0.5.4", "MIT", "Linting"),
    ("expect-webdriverio", "5.6.5", "MIT", "Testing"),
    ("fake-indexeddb", "6.2.5", "Apache-2.0", "Testing"),
    ("globals", "17.9.0", "MIT", "Linting"),
    ("jsdom", "29.1.1", "MIT", "Testing"),
    ("postcss", "8.5.26", "MIT", "CSS & Styling"),
    ("prettier", "3.8.3", "MIT", "Formatting"),
    ("tailwindcss", "4.3.3", "MIT", "CSS & Styling"),
    ("turbo", "2.10.9", "MIT", "Monorepo"),
    ("typescript", "6.0.3", "Apache-2.0", "TypeScript"),
    ("typescript-eslint", "8.67.0", "MIT", "TypeScript"),
    ("vite", "8.2.1", "MIT", "Build Tooling"),
    ("vitest", "4.1.6", "MIT", "Testing"),
    ("webdriverio", "9.27.1", "MIT", "Testing"),
];

fn to_dependency_info(
    (name, version, license, category): &(&str, &str, &str, &str),
) -> DependencyInfo {
    DependencyInfo {
        name: (*name).to_string(),
        version: (*version).to_string(),
        license: (*license).to_string(),
        authors: vec![],
        repository: String::new(),
        description: String::new(),
        category: (*category).to_string(),
    }
}

pub fn get_all_js_deps() -> Vec<DependencyInfo> {
    PRODUCTION_DEPS
        .iter()
        .chain(DEV_DEPS.iter())
        .map(to_dependency_info)
        .collect()
}

pub fn get_deps_by_category() -> Vec<DependencyCategory> {
    let mut map: HashMap<String, Vec<DependencyInfo>> = HashMap::new();
    for dep in get_all_js_deps() {
        map.entry(dep.category.clone()).or_default().push(dep);
    }
    let mut categories: Vec<DependencyCategory> = map
        .into_iter()
        .map(|(name, dependencies)| DependencyCategory {
            description: format!("{} dependencies", name),
            name,
            dependencies,
        })
        .collect();
    categories.sort_by(|left, right| left.name.cmp(&right.name));
    categories
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn generated_catalog_entries_are_unique_and_populated() {
        let dependencies = get_all_js_deps();
        assert_eq!(dependencies.len(), PRODUCTION_DEPS.len() + DEV_DEPS.len());

        let mut names = HashSet::new();
        for dependency in dependencies {
            assert!(
                names.insert(dependency.name.clone()),
                "duplicate {}",
                dependency.name
            );
            assert!(
                !dependency.version.is_empty(),
                "missing version for {}",
                dependency.name
            );
            assert!(
                !dependency.license.is_empty(),
                "missing license for {}",
                dependency.name
            );
            assert!(
                !dependency.category.is_empty(),
                "missing category for {}",
                dependency.name
            );
        }
    }
}
