use crate::types::{DependencyCategory, DependencyInfo, WorkspaceCrateInfo};
use std::collections::HashMap;

/// (crate_name, description, category, command_count)
static CRATES: &[(&str, &str, &str, u32)] = &[
    ("sorng-core", "Core types, traits and shared utilities", "Core", 0),
    ("sorng-auth", "Authentication and authorization services", "Security", 25),
    ("sorng-storage", "Persistent storage and configuration management", "Core", 18),
    ("sorng-network", "Network scanning, discovery and diagnostics", "Networking", 30),
    ("sorng-ssh", "SSH client connections and session management", "Remote Protocols", 35),
    ("sorng-rdp", "RDP client connections and session management", "Remote Protocols", 28),
    ("sorng-protocols", "Multi-protocol connection abstractions", "Remote Protocols", 12),
    ("sorng-vpn", "VPN connection management and profiles", "Networking", 20),
    ("sorng-cloud", "Cloud provider integration abstractions", "Cloud", 10),
    ("sorng-aws", "Amazon Web Services integration", "Cloud", 45),
    ("sorng-remote-mgmt", "Remote system management and monitoring", "Management", 22),
    ("sorng-gpo", "Group Policy Object management", "Management", 15),
    ("sorng-ard", "Apple Remote Desktop integration", "Remote Protocols", 12),
    ("sorng-telnet", "Telnet client connections", "Remote Protocols", 10),
    ("sorng-ftp", "FTP client connections", "File Transfer", 15),
    ("sorng-sftp", "SFTP client connections", "File Transfer", 18),
    ("sorng-vnc", "VNC client connections", "Remote Protocols", 14),
    ("sorng-rustdesk", "RustDesk integration", "Remote Protocols", 10),
    ("sorng-bitwarden", "Bitwarden password manager integration", "Password Managers", 20),
    ("sorng-keepass", "KeePass database integration", "Password Managers", 18),
    ("sorng-scp", "SCP file transfer", "File Transfer", 8),
    ("sorng-mysql", "MySQL database client", "Database", 22),
    ("sorng-postgres", "PostgreSQL database client", "Database", 22),
    ("sorng-mssql", "Microsoft SQL Server client", "Database", 20),
    ("sorng-sqlite", "SQLite database management", "Database", 15),
    ("sorng-mongodb", "MongoDB client", "Database", 18),
    ("sorng-redis", "Redis client and management", "Database", 16),
    ("sorng-passbolt", "Passbolt password manager integration", "Password Managers", 12),
    ("sorng-ai-agent", "AI agent orchestration and tooling", "AI & Automation", 15),
    ("sorng-powershell", "PowerShell remote execution", "Management", 12),
    ("sorng-1password", "1Password integration", "Password Managers", 14),
    ("sorng-lastpass", "LastPass integration", "Password Managers", 12),
    ("sorng-google-passwords", "Google Password Manager integration", "Password Managers", 10),
    ("sorng-dashlane", "Dashlane integration", "Password Managers", 10),
    ("sorng-winmgmt", "Windows management (WMI, registry, services)", "Management", 35),
    ("sorng-serial", "Serial port communication", "Remote Protocols", 10),
    ("sorng-hyperv", "Hyper-V virtual machine management", "Virtualization", 25),
    ("sorng-meshcentral", "MeshCentral remote management integration", "Remote Protocols", 15),
    ("sorng-openvpn", "OpenVPN configuration and management", "Networking", 12),
    ("sorng-vmware", "VMware vSphere/ESXi integration", "Virtualization", 30),
    ("sorng-proxmox", "Proxmox VE management", "Virtualization", 35),
    ("sorng-idrac", "Dell iDRAC/BMC management", "Hardware Management", 25),
    ("sorng-totp", "TOTP/HOTP two-factor authentication", "Security", 10),
    ("sorng-mremoteng", "mRemoteNG connection file import/export", "Interoperability", 8),
    ("sorng-termserv", "Terminal Services/RDS management", "Management", 15),
    ("sorng-whatsapp", "WhatsApp notification integration", "Notifications", 8),
    ("sorng-telegram", "Telegram bot notification integration", "Notifications", 10),
    ("sorng-dropbox", "Dropbox cloud storage synchronization", "Cloud Storage", 12),
    ("sorng-nextcloud", "Nextcloud integration", "Cloud Storage", 14),
    ("sorng-gdrive", "Google Drive integration", "Cloud Storage", 12),
    ("sorng-onedrive", "OneDrive integration", "Cloud Storage", 12),
    ("sorng-recording", "Session recording and playback", "Core", 15),
    ("sorng-gcp", "Google Cloud Platform integration", "Cloud", 30),
    ("sorng-azure", "Microsoft Azure integration", "Cloud", 35),
    ("sorng-exchange", "Microsoft Exchange management", "Email & Messaging", 20),
    ("sorng-smtp", "SMTP email sending and testing", "Email & Messaging", 10),
    ("sorng-llm", "Large language model provider integration", "AI & Automation", 12),
    ("sorng-ai-assist", "AI-assisted connection and script assistance", "AI & Automation", 10),
    ("sorng-terminal-themes", "Terminal color themes and customization", "UI & Theming", 12),
    ("sorng-extensions", "Extension/plugin system management", "Core", 18),
    ("sorng-collaboration", "Real-time collaboration and sharing", "Collaboration", 15),
    ("sorng-gateway", "Connection gateway/jump host management", "Networking", 15),
    ("sorng-biometrics", "Biometric authentication (Windows Hello, etc.)", "Security", 8),
    ("sorng-vault", "HashiCorp Vault secrets management", "Security", 18),
    ("sorng-p2p", "Peer-to-peer connection management", "Networking", 10),
    ("sorng-tailscale", "Tailscale mesh VPN integration", "Networking", 12),
    ("sorng-zerotier", "ZeroTier network integration", "Networking", 10),
    ("sorng-wireguard", "WireGuard VPN management", "Networking", 14),
    ("sorng-dns", "DNS client, resolver and management", "Networking", 18),
    ("sorng-k8s", "Kubernetes cluster management", "Containers", 40),
    ("sorng-docker", "Docker container management", "Containers", 35),
    ("sorng-ansible", "Ansible playbook execution and management", "Infrastructure as Code", 15),
    ("sorng-terraform", "Terraform state and execution management", "Infrastructure as Code", 15),
    ("sorng-i18n", "Internationalization and locale management", "Core", 12),
    ("sorng-command-palette", "Command palette / quick action launcher", "UI & Theming", 8),
    ("sorng-fonts", "Font management and terminal font handling", "UI & Theming", 6),
    ("sorng-secure-clip", "Secure clipboard management", "Security", 6),
    ("sorng-budibase", "Budibase low-code platform integration", "Integrations", 10),
    ("sorng-osticket", "osTicket helpdesk integration", "Integrations", 10),
    ("sorng-jira", "Jira project management integration", "Integrations", 12),
    ("sorng-letsencrypt", "Let's Encrypt certificate management", "Security", 12),
    ("sorng-ssh-agent", "SSH agent management and key forwarding", "Security", 10),
    ("sorng-warpgate", "Warpgate bastion host integration", "Networking", 10),
    ("sorng-ssh-scripts", "SSH script execution and automation", "Management", 15),
    ("sorng-mcp", "Model Context Protocol server integration", "AI & Automation", 20),
    ("sorng-snmp", "SNMP network device monitoring", "Networking", 18),
    ("sorng-bmc-common", "BMC/IPMI common utilities", "Hardware Management", 10),
    ("sorng-ilo", "HP iLO management", "Hardware Management", 20),
    ("sorng-lenovo", "Lenovo XClarity/IMM management", "Hardware Management", 18),
    ("sorng-supermicro", "Supermicro IPMI management", "Hardware Management", 15),
    ("sorng-synology", "Synology NAS management", "Hardware Management", 20),
    ("sorng-notifications", "Notification routing and management", "Notifications", 12),
    ("sorng-filters", "Connection list filtering and smart groups", "Core", 8),
    ("sorng-hooks", "Event hooks and automation triggers", "Core", 10),
    ("sorng-scheduler", "Task scheduling and job management", "Management", 12),
    ("sorng-credentials", "Credential storage and retrieval", "Security", 15),
    ("sorng-topology", "Network topology visualization", "Networking", 10),
    ("sorng-replay", "Session replay viewer", "Core", 8),
    ("sorng-marketplace", "Extension marketplace integration", "Core", 10),
    ("sorng-dashboard", "Dashboard widget management", "UI & Theming", 12),
    ("sorng-updater", "Application auto-update management", "Core", 8),
    ("sorng-rdpfile", "RDP file parsing and generation", "Interoperability", 10),
    ("sorng-portable", "Portable mode configuration", "Core", 6),
    ("sorng-docker-compose", "Docker Compose stack management", "Containers", 18),
    ("sorng-lxd", "LXD/Incus container management", "Containers", 15),
    ("sorng-netbird", "NetBird mesh VPN integration", "Networking", 10),
    ("sorng-teleport", "Teleport access management integration", "Networking", 12),
    ("sorng-vmware-desktop", "VMware Workstation/Fusion management", "Virtualization", 20),
    ("sorng-spice", "SPICE remote display protocol", "Remote Protocols", 10),
    ("sorng-nx", "NoMachine NX protocol integration", "Remote Protocols", 10),
    ("sorng-xdmcp", "XDMCP (X Display Manager) integration", "Remote Protocols", 8),
    ("sorng-x2go", "X2Go remote desktop integration", "Remote Protocols", 10),
    ("sorng-nginx", "Nginx web server management", "Web Servers", 30),
    ("sorng-traefik", "Traefik reverse proxy management", "Web Servers", 25),
    ("sorng-haproxy", "HAProxy load balancer management", "Web Servers", 22),
    ("sorng-apache", "Apache HTTP Server management", "Web Servers", 28),
    ("sorng-caddy", "Caddy web server management", "Web Servers", 20),
    ("sorng-nginx-proxy-mgr", "Nginx Proxy Manager integration", "Web Servers", 18),
    ("sorng-postfix", "Postfix mail server management", "Email & Messaging", 25),
    ("sorng-gpg-agent", "GPG agent and key management", "Security", 12),
    ("sorng-yubikey", "YubiKey hardware token management", "Security", 10),
    ("sorng-opendkim", "OpenDKIM email signing management", "Email & Messaging", 15),
    ("sorng-cyrus-sasl", "Cyrus SASL authentication management", "Email & Messaging", 12),
    ("sorng-dovecot", "Dovecot IMAP/POP3 server management", "Email & Messaging", 22),
    ("sorng-ddns", "Dynamic DNS management", "Networking", 10),
    ("sorng-netmgr", "Network interface management", "Networking", 15),
    ("sorng-netutils", "Network utility tools (ping, traceroute, etc.)", "Networking", 12),
    ("sorng-clamav", "ClamAV antivirus management", "Security", 12),
    ("sorng-rspamd", "Rspamd spam filter management", "Email & Messaging", 15),
    ("sorng-roundcube", "Roundcube webmail management", "Email & Messaging", 12),
    ("sorng-spamassassin", "SpamAssassin filter management", "Email & Messaging", 14),
    ("sorng-proc", "Process monitoring and management", "System Administration", 30),
    ("sorng-procmail", "Procmail filter management", "Email & Messaging", 10),
    ("sorng-mailcow", "Mailcow mail server suite management", "Email & Messaging", 18),
    ("sorng-amavis", "Amavis content filter management", "Email & Messaging", 12),
    ("sorng-remote-backup", "Remote backup management", "Management", 15),
    ("sorng-fail2ban", "Fail2ban intrusion prevention management", "Security", 18),
    ("sorng-cron", "Cron job scheduling management", "System Administration", 20),
    ("sorng-bootloader", "Bootloader configuration management", "System Administration", 15),
    ("sorng-time-ntp", "Time synchronization and NTP management", "System Administration", 18),
    ("sorng-os-detect", "Operating system detection and identification", "System Administration", 10),
    ("sorng-kernel", "Linux kernel parameter management", "System Administration", 25),
    ("sorng-pam", "PAM authentication module management", "System Administration", 20),
    ("sorng-cpanel", "cPanel/WHM hosting panel management", "Web Servers", 30),
    ("sorng-php", "PHP runtime and extension management", "Web Servers", 35),
    ("sorng-port-knock", "Port knocking and SPA authentication", "Security", 54),
];

pub fn get_all_workspace_crates() -> Vec<WorkspaceCrateInfo> {
    CRATES
        .iter()
        .map(|(name, description, category, commands)| WorkspaceCrateInfo {
            name: name.to_string(),
            description: description.to_string(),
            category: category.to_string(),
            command_count: *commands,
        })
        .collect()
}

pub fn get_crates_by_category() -> Vec<DependencyCategory> {
    let crates = get_all_workspace_crates();
    let mut map: HashMap<String, Vec<DependencyInfo>> = HashMap::new();
    for c in &crates {
        map.entry(c.category.clone())
            .or_default()
            .push(DependencyInfo {
                name: c.name.clone(),
                version: String::new(),
                license: "MIT".to_string(),
                authors: vec!["Mariana M".to_string()],
                repository: String::new(),
                description: c.description.clone(),
                category: c.category.clone(),
            });
    }
    let mut cats: Vec<DependencyCategory> = map
        .into_iter()
        .map(|(name, dependencies)| DependencyCategory {
            name: name.clone(),
            description: format!("{} crates", name),
            dependencies,
        })
        .collect();
    cats.sort_by(|a, b| a.name.cmp(&b.name));
    cats
}
