import {
  ChartNoAxesCombined,
  ChartPie,
  CreditCard,
  ReceiptText,
  Workflow,
} from "lucide-react";

import {
  apachesuperset,
  cegid,
  dolibarr,
  erpnext,
  matomo,
  metabase,
  microsoftdynamics365,
  odoo,
  oracle,
  phc,
  plausibleanalytics,
  primavera,
  redash,
  sap,
} from "../brand";
import { createRoleIcon } from "../createRoleIcon";
import { defineIcon } from "./types";

/** Business endpoints share the existing web-applications category. */
export const BUSINESS_APPLICATION_ICONS = [
  defineIcon(
    "pos",
    "Point of sale (POS)",
    "web-applications",
    createRoleIcon("PointOfSale", "desktop", CreditCard),
    [
      "pos",
      "generic pos",
      "point of sale",
      "checkout",
      "cash register",
      "retail",
      "payment terminal",
    ],
  ),
  defineIcon("erp", "ERP", "web-applications", Workflow, [
    "erp",
    "generic erp",
    "enterprise resource planning",
    "business management",
    "accounting",
    "inventory",
  ]),
  defineIcon(
    "invoice-server",
    "Invoice server",
    "web-applications",
    createRoleIcon("InvoiceServer", "server", ReceiptText),
    [
      "invoice server",
      "invoices",
      "invoicing",
      "billing server",
      "accounting",
      "fatura",
    ],
  ),
  defineIcon(
    "business-analytics-server",
    "Business analytics server",
    "web-applications",
    createRoleIcon("BusinessAnalyticsServer", "server", ChartPie),
    [
      "business analytics server",
      "business intelligence",
      "bi server",
      "reporting",
      "dashboard",
      "analytics sevrer",
    ],
  ),
  defineIcon(
    "analytics-server",
    "Analytics server",
    "web-applications",
    createRoleIcon("AnalyticsServer", "server", ChartNoAxesCombined),
    [
      "analytics server",
      "analytics sevrer",
      "data analytics",
      "metrics",
      "reporting",
      "statistics",
    ],
  ),
  defineIcon("odoo", "Odoo", "web-applications", odoo, [
    "odoo",
    "erp",
    "crm",
    "business applications",
    "accounting",
    "inventory",
  ]),
  defineIcon("metabase", "Metabase", "web-applications", metabase, [
    "metabase",
    "business intelligence",
    "bi",
    "analytics",
    "dashboards",
    "reporting",
  ]),
  defineIcon(
    "apache-superset",
    "Apache Superset",
    "web-applications",
    apachesuperset,
    [
      "apache superset",
      "superset",
      "business intelligence",
      "analytics",
      "dashboards",
      "sql",
    ],
  ),
  defineIcon("redash", "Redash", "web-applications", redash, [
    "redash",
    "analytics",
    "business intelligence",
    "dashboards",
    "sql",
    "queries",
  ]),
  defineIcon("matomo", "Matomo", "web-applications", matomo, [
    "matomo",
    "piwik",
    "web analytics",
    "analytics",
    "website statistics",
    "privacy",
  ]),
  defineIcon("plausible", "Plausible", "web-applications", plausibleanalytics, [
    "plausible",
    "plausible analytics",
    "web analytics",
    "website statistics",
    "privacy",
  ]),
  defineIcon("sap", "SAP", "web-applications", sap, [
    "sap",
    "erp",
    "enterprise resource planning",
    "s4hana",
    "s 4hana",
    "business one",
  ]),
  defineIcon(
    "oracle-erp",
    "Oracle ERP",
    "web-applications",
    oracle,
    [
      "oracle erp",
      "oracle",
      "enterprise resource planning",
      "fusion",
      "ebusiness suite",
      "financials",
    ],
    "Oracle ERP connection icon using the historical Oracle brand mark.",
  ),
  defineIcon("erpnext", "ERPNext", "web-applications", erpnext, [
    "erpnext",
    "erp next",
    "frappe",
    "erp",
    "accounting",
    "business management",
  ]),
  defineIcon("dolibarr", "Dolibarr", "web-applications", dolibarr, [
    "dolibarr",
    "erp",
    "crm",
    "business management",
    "billing",
    "accounting",
  ]),
  defineIcon(
    "microsoft-dynamics365",
    "Microsoft Dynamics 365",
    "web-applications",
    microsoftdynamics365,
    [
      "microsoft dynamics365",
      "microsoft dynamics 365",
      "dynamics365",
      "dynamics 365",
      "d365",
      "erp",
      "crm",
      "business central",
    ],
    "Microsoft Dynamics 365 connection icon using the historical Dynamics 365 brand mark.",
  ),
  defineIcon(
    "metabase-server",
    "Metabase server",
    "web-applications",
    createRoleIcon("MetabaseServer", "server", metabase),
    [
      "metabase server",
      "metabase",
      "business intelligence",
      "analytics server",
      "dashboards",
    ],
  ),
  defineIcon(
    "apache-superset-server",
    "Apache Superset server",
    "web-applications",
    createRoleIcon("ApacheSupersetServer", "server", apachesuperset),
    [
      "apache superset server",
      "superset server",
      "superset",
      "business intelligence",
      "analytics server",
    ],
  ),
  defineIcon(
    "redash-server",
    "Redash server",
    "web-applications",
    createRoleIcon("RedashServer", "server", redash),
    [
      "redash server",
      "redash",
      "analytics server",
      "business intelligence",
      "sql",
      "dashboards",
    ],
  ),
  defineIcon(
    "matomo-server",
    "Matomo server",
    "web-applications",
    createRoleIcon("MatomoServer", "server", matomo),
    [
      "matomo server",
      "matomo",
      "web analytics server",
      "analytics server",
      "piwik",
      "privacy",
    ],
  ),
  defineIcon(
    "plausible-server",
    "Plausible server",
    "web-applications",
    createRoleIcon("PlausibleServer", "server", plausibleanalytics),
    [
      "plausible server",
      "plausible analytics",
      "web analytics server",
      "analytics server",
      "privacy",
    ],
  ),
  defineIcon(
    "phc",
    "PHC",
    "web-applications",
    phc,
    [
      "phc",
      "cegid phc",
      "phc software",
      "erp",
      "accounting",
      "business management",
    ],
    "PHC connection icon using the PHC lettering from the publisher's Cegid PHC mark.",
  ),
  defineIcon("cegid", "Cegid", "web-applications", cegid, [
    "cegid",
    "erp",
    "business management",
    "accounting",
    "retail",
    "payroll",
  ]),
  defineIcon(
    "primavera",
    "Cegid Primavera",
    "web-applications",
    primavera,
    [
      "primavera",
      "cegid primavera",
      "primavera erp",
      "erp",
      "accounting",
      "business management",
    ],
    "Cegid Primavera ERP with an app-authored PR identifier; not an official Cegid Primavera logo.",
  ),
] as const;
