import {
  Cloud,
  CloudCog,
  CloudDownload,
  CloudLightning,
  CloudUpload,
} from "lucide-react";

import {
  alibabacloud,
  aws,
  azure,
  digitalocean,
  googlecloud,
  hetzner,
  ibm,
  linode,
  oracle,
  ovh,
  redhat,
  tencentcloud,
  heroku,
  scaleway,
} from "../brand";
import { createRoleIcon } from "../createRoleIcon";
import { defineIcon } from "./types";

export const CLOUD_ICONS = [
  defineIcon(
    "aws",
    "AWS",
    "cloud",
    aws,
    ["aws", "amazon web services", "amazon cloud", "cloud provider", "plain"],
    "AWS cloud-provider choice using the app's existing AWS/cloud identifier, not a newly sourced official product mark.",
  ),
  defineIcon(
    "oracle",
    "Oracle",
    "cloud",
    oracle,
    ["oracle", "oracle cloud", "oci", "cloud provider", "plain brand"],
    "Oracle cloud-provider choice using the plain Oracle parent brand mark, not an ERP-specific icon.",
  ),
  defineIcon(
    "redhat-cloud-brand",
    "Red Hat cloud brand",
    "cloud",
    redhat,
    [
      "redhat",
      "red hat",
      "red hat cloud",
      "openshift",
      "cloud provider",
      "plain brand",
    ],
    "Cloud-provider choice using the plain Red Hat parent brand mark, not a separate cloud-product logo.",
  ),
  defineIcon("heroku", "Heroku", "cloud", heroku, ["heroku", "cloud", "paas"]),
  defineIcon("scaleway", "Scaleway", "cloud", scaleway, [
    "scaleway",
    "cloud",
    "hosting",
  ]),
  defineIcon("cloud", "Cloud", "cloud", Cloud, ["azure", "gcp", "provider"]),
  defineIcon("cloud-cog", "Managed cloud", "cloud", CloudCog, [
    "cloud admin",
    "service",
  ]),
  defineIcon("cloud-upload", "Cloud upload", "cloud", CloudUpload, [
    "upload",
    "sync",
  ]),
  defineIcon("cloud-download", "Cloud download", "cloud", CloudDownload, [
    "download",
    "sync",
  ]),
  defineIcon("cloud-lightning", "Cloud compute", "cloud", CloudLightning, [
    "compute",
    "serverless",
  ]),
  defineIcon("googlecloud", "Google Cloud", "cloud", googlecloud, [
    "gcp",
    "google cloud",
    "cloud platform",
  ]),
  defineIcon("azure", "Microsoft Azure", "cloud", azure, [
    "azure",
    "microsoft cloud",
    "cloud platform",
  ]),
  defineIcon(
    "hetzner-cloud",
    "Hetzner Cloud",
    "cloud",
    createRoleIcon("HetznerCloud", "cloud", hetzner),
    ["hetzner", "hetzenr", "hetznercloud", "cloud hosting", "vps"],
  ),
  defineIcon(
    "ovh-cloud",
    "OVHcloud",
    "cloud",
    createRoleIcon("OVHCloud", "cloud", ovh),
    ["ovh", "ovhcloud", "ovh cloud", "hosting", "vps"],
  ),
  defineIcon(
    "digitalocean-cloud",
    "DigitalOcean",
    "cloud",
    createRoleIcon("DigitalOceanCloud", "cloud", digitalocean),
    ["digitalocean", "digital ocean", "droplet", "cloud"],
  ),
  defineIcon(
    "oracle-cloud",
    "Oracle Cloud",
    "cloud",
    createRoleIcon("OracleCloud", "cloud", oracle),
    ["oracle", "oraclecloud", "oci", "cloud infrastructure"],
  ),
  defineIcon(
    "alibaba-cloud",
    "Alibaba Cloud",
    "cloud",
    createRoleIcon("AlibabaCloud", "cloud", alibabacloud),
    ["alibaba", "alibabacloud", "aliyun", "ecs"],
  ),
  defineIcon("tencent-cloud", "Tencent Cloud", "cloud", tencentcloud, [
    "tencent",
    "tencentcloud",
    "qcloud",
    "cloud",
  ]),
  defineIcon(
    "ibm-cloud",
    "IBM Cloud",
    "cloud",
    createRoleIcon("IBMCloud", "cloud", ibm),
    ["ibm", "ibmcloud", "bluemix", "softlayer"],
  ),
  defineIcon(
    "redhat-cloud",
    "Red Hat cloud",
    "cloud",
    createRoleIcon("RedHatCloud", "cloud", redhat),
    ["redhat", "red hat", "openshift", "cloud"],
  ),
  defineIcon(
    "linode",
    "Linode",
    "cloud",
    linode,
    ["linode", "akamai", "cloud", "vps"],
    "Linode connection icon using the historical Linode cube mark, not the current Akamai logo.",
  ),
  defineIcon("ibm", "IBM", "cloud", ibm, [
    "ibm",
    "international business machines",
    "power",
    "mainframe",
  ]),
  defineIcon("hetzner", "Hetzner", "cloud", hetzner, [
    "hetzner",
    "hosting",
    "cloud",
    "provider",
    "plain",
  ]),
  defineIcon("ovh", "OVH", "cloud", ovh, [
    "ovh",
    "ovhcloud",
    "ovh cloud",
    "hosting",
    "provider",
    "plain",
  ]),
  defineIcon("digitalocean", "DigitalOcean", "cloud", digitalocean, [
    "digitalocean",
    "digital ocean",
    "cloud",
    "hosting",
    "provider",
    "plain",
  ]),
  defineIcon("alibabacloud", "Alibaba Cloud", "cloud", alibabacloud, [
    "alibabacloud",
    "alibaba cloud",
    "aliyun",
    "cloud",
    "provider",
    "plain",
  ]),
] as const;
