import {
  AtSign,
  Bell,
  FolderTree,
  LifeBuoy,
  Mail,
  Mailbox,
  MailPlus,
  MessageSquare,
  MessagesSquare,
  Network,
  Send,
} from "lucide-react";

import {
  dovecot,
  element,
  mailcow,
  matrix,
  mattermost,
  microsoftexchangemodern,
  osticket,
  postfix,
  rocketdotchat,
  slack,
  zulip,
} from "../brand";
import { createRoleIcon } from "../createRoleIcon";
import { defineIcon } from "./types";

export const COMMUNICATION_ICONS = [
  defineIcon("mail", "Mail", "communication", Mail, ["exchange", "email"]),
  defineIcon("mailbox", "Mailbox", "communication", Mailbox, [
    "mailcow",
    "email",
  ]),
  defineIcon("message", "Message", "communication", MessageSquare, [
    "chat",
    "comment",
  ]),
  defineIcon("messages", "Messages", "communication", MessagesSquare, [
    "chat",
    "conversation",
  ]),
  defineIcon("send", "Send", "communication", Send, ["message", "outbound"]),
  defineIcon("bell", "Notification", "communication", Bell, [
    "alert",
    "notification",
  ]),
  defineIcon("life-buoy", "Support", "communication", LifeBuoy, [
    "osticket",
    "helpdesk",
  ]),
  defineIcon("at-sign", "Account", "communication", AtSign, [
    "email",
    "identity",
  ]),
  defineIcon(
    "active-directory",
    "Active Directory",
    "communication",
    createRoleIcon("ActiveDirectory", "server", Network),
    [
      "active directory",
      "activedirectory",
      "microsoft ad",
      "ad ds",
      "domain controller",
      "ldap",
    ],
    "Active Directory service icon using an app server/directory hierarchy symbol, not an official Microsoft product logo.",
  ),
  defineIcon(
    "postfix",
    "Postfix",
    "communication",
    postfix,
    ["postfix", "postfix mail", "mail transfer agent", "smtp", "mta"],
    "Postfix connection icon: app-authored PF/mail-flow identifier, not an official project logo.",
  ),
  defineIcon(
    "mail-server",
    "Mail server",
    "communication",
    createRoleIcon("MailServer", "server", Mail),
    [
      "mail server",
      "generic mail server",
      "mailserver",
      "email server",
      "smtp",
      "imap",
      "pop3",
    ],
  ),
  defineIcon("dovecot", "Dovecot", "communication", dovecot, [
    "dovecot",
    "dove cot",
    "imap",
    "pop3",
    "mail server",
  ]),
  defineIcon(
    "active-directory-server",
    "Active Directory server",
    "communication",
    createRoleIcon("ActiveDirectoryServer", "server", FolderTree),
    [
      "ad server",
      "ad-server",
      "active directory server",
      "activedirectoryserver",
      "domain controller",
      "ad ds",
    ],
    "App-authored server with directory-tree geometry, not an official Microsoft product logo.",
  ),
  defineIcon(
    "exchange-server",
    "Microsoft Exchange server",
    "communication",
    createRoleIcon("ExchangeServer", "server", microsoftexchangemodern),
    ["exchange server", "exchange-server", "microsoft exchange", "email"],
  ),
  defineIcon(
    "mta-server",
    "MTA server",
    "communication",
    createRoleIcon("MTAServer", "server", MailPlus),
    [
      "mta server",
      "mta-server",
      "mail transfer agent",
      "smtp relay",
      "outbound mail",
    ],
  ),
  defineIcon("slack", "Slack", "communication", slack, [
    "slack",
    "chat",
    "collaboration",
  ]),
  defineIcon("mattermost", "Mattermost", "communication", mattermost, [
    "mattermost",
    "open source chat",
    "chat server",
    "self hosted",
  ]),
  defineIcon("rocket-chat", "Rocket.Chat", "communication", rocketdotchat, [
    "rocket chat",
    "rocketchat",
    "rocket.chat",
    "open source chat server",
  ]),
  defineIcon("matrix", "Matrix", "communication", matrix, [
    "matrix",
    "synapse",
    "federated chat",
    "matrix server",
  ]),
  defineIcon("zulip", "Zulip", "communication", zulip, [
    "zulip",
    "open source chat",
    "chat server",
  ]),
  defineIcon("element", "Element", "communication", element, [
    "element",
    "matrix client",
    "chat",
    "messaging",
  ]),
  defineIcon(
    "mailcow",
    "Mailcow",
    "communication",
    mailcow,
    ["mailcow", "mail cow", "mail server", "smtp"],
    "Mailcow using an app-authored cow/mail identifier, not an official project logo.",
  ),
  defineIcon(
    "mailcow-server",
    "Mailcow server",
    "communication",
    createRoleIcon("MailcowServer", "server", mailcow),
    ["mailcow server", "mailcow", "mail server", "docker mail"],
    "Mailcow server using an app-authored cow/mail identifier, not an official project logo.",
  ),
  defineIcon(
    "osticket",
    "osTicket",
    "communication",
    osticket,
    ["osticket", "os ticket", "helpdesk", "support ticket"],
    "osTicket using an app-authored ticket identifier, not an official project logo.",
  ),
] as const;
