import {
  apachecassandra,
  apachecouchdb,
  clickhouse,
  cockroachlabs,
  influxdb,
  mariadb,
  microsoftsqlserver,
  mongodb,
  mysql,
  neo4j,
  oracle,
  postgresql,
  redis,
  sqlite,
} from "../brand";
import { createRoleIcon } from "../createRoleIcon";
import { defineIcon } from "./types";

/** Bare database brands and explicit hosted/storage roles remain separate choices. */
export const DATABASE_SERVER_ICONS = [
  defineIcon("sqlite", "SQLite", "databases", sqlite, [
    "sqlite",
    "sqlite3",
    "sqlite database",
    "embedded database",
    "sql",
  ]),
  defineIcon(
    "sqlite-database",
    "SQLite database",
    "databases",
    createRoleIcon("SQLiteDatabase", "database", sqlite),
    ["sqlite database", "sqlite storage", "embedded database", "database file"],
  ),
  defineIcon(
    "sqlite-server",
    "SQLite-backed server",
    "databases",
    createRoleIcon("SQLiteServer", "server", sqlite),
    [
      "sqlite server",
      "sqlite backed server",
      "embedded database",
      "application host",
    ],
    "Host running SQLite-backed applications; SQLite itself is embedded, not a standalone network database service.",
  ),
  defineIcon(
    "cockroachdb",
    "CockroachDB",
    "databases",
    cockroachlabs,
    [
      "cockroachdb",
      "cockroach db",
      "cockroach labs",
      "distributed sql",
      "database",
    ],
    "CockroachDB choice using the Cockroach Labs brand mark.",
  ),
  defineIcon(
    "cockroachdb-server",
    "CockroachDB server",
    "databases",
    createRoleIcon("CockroachDBServer", "server", cockroachlabs),
    [
      "cockroachdb server",
      "cockroach db server",
      "distributed sql",
      "database server",
    ],
    "CockroachDB server with the Cockroach Labs mark in an app-authored server frame.",
  ),
  defineIcon("clickhouse", "ClickHouse", "databases", clickhouse, [
    "clickhouse",
    "click house",
    "analytics database",
    "columnar",
    "olap",
  ]),
  defineIcon(
    "clickhouse-server",
    "ClickHouse server",
    "databases",
    createRoleIcon("ClickHouseServer", "server", clickhouse),
    [
      "clickhouse server",
      "click house server",
      "analytics database server",
      "columnar",
    ],
  ),
  defineIcon("cassandra", "Apache Cassandra", "databases", apachecassandra, [
    "cassandra",
    "apache cassandra",
    "wide column",
    "nosql database",
  ]),
  defineIcon(
    "cassandra-server",
    "Apache Cassandra server",
    "databases",
    createRoleIcon("CassandraServer", "server", apachecassandra),
    ["cassandra server", "apache cassandra server", "nosql database server"],
  ),
  defineIcon("couchdb", "Apache CouchDB", "databases", apachecouchdb, [
    "couchdb",
    "couch db",
    "apache couchdb",
    "document database",
    "nosql",
  ]),
  defineIcon(
    "couchdb-server",
    "Apache CouchDB server",
    "databases",
    createRoleIcon("CouchDBServer", "server", apachecouchdb),
    [
      "couchdb server",
      "couch db server",
      "apache couchdb server",
      "document database server",
    ],
  ),
  defineIcon("neo4j", "Neo4j", "databases", neo4j, [
    "neo4j",
    "neo 4j",
    "graph database",
    "cypher",
  ]),
  defineIcon(
    "neo4j-server",
    "Neo4j server",
    "databases",
    createRoleIcon("Neo4jServer", "server", neo4j),
    ["neo4j server", "neo 4j server", "graph database server"],
  ),
  defineIcon("influxdb", "InfluxDB", "databases", influxdb, [
    "influxdb",
    "influx db",
    "time series database",
    "telemetry",
  ]),
  defineIcon(
    "influxdb-server",
    "InfluxDB server",
    "databases",
    createRoleIcon("InfluxDBServer", "server", influxdb),
    ["influxdb server", "influx db server", "time series database server"],
  ),
  defineIcon(
    "oracle-db",
    "Oracle Database",
    "databases",
    oracle,
    ["oracle db", "oracle database", "oracle sql", "relational database"],
    "Oracle Database choice using the plain Oracle parent brand mark, distinct from the ERP and cloud-provider choices.",
  ),
  defineIcon(
    "oracle-db-server",
    "Oracle Database server",
    "databases",
    createRoleIcon("OracleDatabaseServer", "server", oracle),
    [
      "oracle db server",
      "oracle database server",
      "oracle server",
      "relational database server",
    ],
    "Oracle Database server with the Oracle parent brand mark in an app-authored server frame.",
  ),
  defineIcon(
    "mysql-server",
    "MySQL server",
    "databases",
    createRoleIcon("MySQLServer", "server", mysql),
    ["mysql server", "mysql database server", "sql server"],
  ),
  defineIcon(
    "mariadb-server",
    "MariaDB server",
    "databases",
    createRoleIcon("MariaDBServer", "server", mariadb),
    ["mariadb server", "maria db server", "sql server"],
  ),
  defineIcon(
    "postgresql-server",
    "PostgreSQL server",
    "databases",
    createRoleIcon("PostgreSQLServer", "server", postgresql),
    [
      "postgresql server",
      "postgres server",
      "postgresql database server",
      "postegres server",
    ],
  ),
  defineIcon(
    "mongodb-server",
    "MongoDB server",
    "databases",
    createRoleIcon("MongoDBServer", "server", mongodb),
    ["mongodb server", "mongo server", "document database server"],
  ),
  defineIcon(
    "redis-server",
    "Redis server",
    "databases",
    createRoleIcon("RedisServer", "server", redis),
    ["redis server", "redis database server", "cache server", "key value"],
  ),
  defineIcon(
    "mssql-server",
    "Microsoft SQL Server host",
    "databases",
    createRoleIcon("MSSQLServer", "server", microsoftsqlserver),
    [
      "mssql server",
      "ms sql server",
      "microsoft sql server",
      "sql server host",
    ],
  ),
] as const;
