import {
  Activity,
  BarChart3,
  Bot,
  BotMessageSquare,
  BrainCircuit,
  Bug,
  ChartNoAxesCombined,
  Code2,
  FileCode2,
  Gauge,
  GitBranch,
  GitCommit,
  MonitorCog,
  Package,
  PanelTop,
  Settings,
  SquareKanban,
  TestTube2,
  Webhook,
  Workflow,
  Wrench,
} from "lucide-react";

import {
  ansible,
  azuredevops,
  buildkite,
  circleci,
  drone,
  elasticsearch,
  git,
  gitea,
  github,
  githubactions,
  gitlab,
  jenkins,
  jira,
  meshcentral,
  minio,
  n8n,
  nodered,
  prometheus,
  puppet,
  rundeck,
  splunk,
  teamcity,
  travisci,
} from "../brand";
import { createRoleIcon } from "../createRoleIcon";
import { defineIcon } from "./types";
import { LLM_VARIANT_ICONS } from "./llmVariants";
import { DEVELOPER_TOOL_ICONS } from "./developerToolIcons";

import { SCRIPT_LANGUAGE_ICONS } from "./scriptLanguages";

export const DEVOPS_MONITORING_ICONS = [
  defineIcon("activity", "Activity", "devops-monitoring", Activity, [
    "prometheus",
    "monitoring",
    "health",
  ]),
  defineIcon("bar-chart", "Dashboard", "devops-monitoring", BarChart3, [
    "grafana",
    "metrics",
    "chart",
  ]),
  defineIcon("chart", "Analytics", "devops-monitoring", ChartNoAxesCombined, [
    "analytics",
    "trend",
  ]),
  defineIcon("gauge", "Performance", "devops-monitoring", Gauge, [
    "speed",
    "metrics",
  ]),
  defineIcon("workflow", "Automation", "devops-monitoring", Workflow, [
    "ansible",
    "pipeline",
  ]),
  defineIcon("git-branch", "Git branch", "devops-monitoring", GitBranch, [
    "git",
    "source control",
  ]),
  defineIcon("git-commit", "Git commit", "devops-monitoring", GitCommit, [
    "git",
    "revision",
  ]),
  defineIcon("package", "Package", "devops-monitoring", Package, [
    "artifact",
    "deployment",
  ]),
  defineIcon("wrench", "Tools", "devops-monitoring", Wrench, [
    "maintenance",
    "admin",
  ]),
  defineIcon("settings", "Settings", "devops-monitoring", Settings, [
    "configuration",
    "admin",
  ]),
  defineIcon("code", "Code", "devops-monitoring", Code2, [
    "development",
    "source",
  ]),
  defineIcon("file-code", "Code file", "devops-monitoring", FileCode2, [
    "php",
    "script",
  ]),
  defineIcon("bug", "Issue", "devops-monitoring", Bug, ["debug", "problem"]),
  defineIcon("test-tube", "Test", "devops-monitoring", TestTube2, [
    "qa",
    "lab",
    "test",
    "testing",
    "test icon",
    "test tube",
    "experiment",
  ]),
  defineIcon("kanban", "Kanban", "devops-monitoring", SquareKanban, [
    "jira",
    "tasks",
  ]),
  defineIcon("panel", "Control panel", "devops-monitoring", PanelTop, [
    "cpanel",
    "dashboard",
    "control panel",
    "admin panel",
    "control console",
  ]),
  defineIcon("bot", "Automation bot", "devops-monitoring", Bot, [
    "agent",
    "automation",
  ]),
  defineIcon("webhook", "Webhook", "devops-monitoring", Webhook, [
    "event",
    "integration",
  ]),
  defineIcon("github", "GitHub", "devops-monitoring", github, [
    "github",
    "git hub",
    "source control",
    "repository",
  ]),
  defineIcon("git", "Git", "devops-monitoring", git, [
    "git",
    "source control",
    "repository",
    "version control",
  ]),
  defineIcon(
    "git-server",
    "Git server",
    "devops-monitoring",
    createRoleIcon("GitServer", "server", git),
    ["git server", "git", "repository", "self hosted"],
  ),
  defineIcon("drone-ci", "Drone CI", "devops-monitoring", drone, [
    "drone",
    "droneci",
    "drone ci",
    "continuous integration",
  ]),
  defineIcon(
    "drone-ci-server",
    "Drone CI server",
    "devops-monitoring",
    createRoleIcon("DroneCIServer", "server", drone),
    ["drone", "droneci", "drone ci", "ci server", "pipeline"],
  ),
  defineIcon(
    "rmm",
    "Remote monitoring and management",
    "devops-monitoring",
    MonitorCog,
    ["rmm", "remote monitoring", "remote management", "endpoint management"],
  ),
  defineIcon(
    "rmm-server",
    "RMM server",
    "devops-monitoring",
    createRoleIcon("RMMServer", "server", MonitorCog),
    ["rmm", "rmm server", "remote monitoring", "remote management"],
  ),
  defineIcon(
    "meshcentral",
    "MeshCentral",
    "devops-monitoring",
    meshcentral,
    ["meshcentral", "mesh central", "rmm", "remote management"],
    "MeshCentral connection icon: app-authored mesh/M identifier, not an official project logo.",
  ),
  defineIcon("llm", "Large language model", "devops-monitoring", BrainCircuit, [
    "llm",
    "large language model",
    "language model",
    "ai",
    "inference",
  ]),
  defineIcon(
    "llm-server",
    "LLM server",
    "devops-monitoring",
    createRoleIcon("LLMServer", "server", BrainCircuit),
    ["llm server", "llm", "inference server", "ollama", "vllm"],
  ),
  defineIcon("ai-agent", "AI agent", "devops-monitoring", BotMessageSquare, [
    "ai agent",
    "aiagent",
    "artificial intelligence",
    "assistant",
    "agent",
  ]),
  defineIcon(
    "agent-server",
    "Agent server",
    "devops-monitoring",
    createRoleIcon("AgentServer", "server", BotMessageSquare),
    ["agent server", "ai agent", "agent host", "automation"],
  ),
  defineIcon("jenkins", "Jenkins", "devops-monitoring", jenkins, [
    "jenkins",
    "ci",
    "continuous integration",
    "build",
  ]),
  defineIcon(
    "jenkins-server",
    "Jenkins build server",
    "devops-monitoring",
    createRoleIcon("JenkinsServer", "server", jenkins),
    ["jenkins", "jenkins server", "build server", "ci"],
  ),
  defineIcon(
    "github-actions",
    "GitHub Actions",
    "devops-monitoring",
    githubactions,
    ["github actions", "githubactions", "ci", "workflow"],
  ),
  defineIcon(
    "github-actions-server",
    "GitHub Actions runner",
    "devops-monitoring",
    createRoleIcon("GitHubActionsServer", "server", githubactions),
    [
      "github actions",
      "githubactions",
      "runner",
      "build server",
      "self hosted",
    ],
  ),
  defineIcon("gitlab-ci", "GitLab CI", "devops-monitoring", gitlab, [
    "gitlab ci",
    "gitlabci",
    "pipeline",
    "continuous integration",
  ]),
  defineIcon(
    "gitlab-ci-server",
    "GitLab CI runner",
    "devops-monitoring",
    createRoleIcon("GitLabCIServer", "server", gitlab),
    ["gitlab ci", "gitlabci", "runner", "build server"],
  ),
  defineIcon("teamcity", "TeamCity", "devops-monitoring", teamcity, [
    "teamcity",
    "team city",
    "jetbrains",
    "ci",
  ]),
  defineIcon(
    "teamcity-server",
    "TeamCity build server",
    "devops-monitoring",
    createRoleIcon("TeamCityServer", "server", teamcity),
    ["teamcity", "team city", "jetbrains", "build server"],
  ),
  defineIcon("circleci", "CircleCI", "devops-monitoring", circleci, [
    "circleci",
    "circle ci",
    "ci",
    "pipeline",
  ]),
  defineIcon(
    "circleci-server",
    "CircleCI build server",
    "devops-monitoring",
    createRoleIcon("CircleCIServer", "server", circleci),
    ["circleci", "circle ci", "build server", "runner"],
  ),
  defineIcon("travisci", "Travis CI", "devops-monitoring", travisci, [
    "travisci",
    "travis ci",
    "ci",
    "build",
  ]),
  defineIcon(
    "travisci-server",
    "Travis CI build server",
    "devops-monitoring",
    createRoleIcon("TravisCIServer", "server", travisci),
    ["travisci", "travis ci", "build server", "worker"],
  ),
  defineIcon("buildkite", "Buildkite", "devops-monitoring", buildkite, [
    "buildkite",
    "build kite",
    "ci",
    "pipeline",
  ]),
  defineIcon(
    "buildkite-server",
    "Buildkite agent server",
    "devops-monitoring",
    createRoleIcon("BuildkiteServer", "server", buildkite),
    ["buildkite", "build kite", "build server", "agent"],
  ),
  defineIcon("azure-devops", "Azure DevOps", "devops-monitoring", azuredevops, [
    "azure devops",
    "azuredevops",
    "ado",
    "pipelines",
    "tfs",
  ]),
  defineIcon(
    "azure-devops-server",
    "Azure DevOps build server",
    "devops-monitoring",
    createRoleIcon("AzureDevOpsServer", "server", azuredevops),
    ["azure devops", "azuredevops", "build server", "pipelines", "tfs"],
  ),
  defineIcon("ansible", "Ansible", "devops-monitoring", ansible, [
    "ansible",
    "automation",
    "configuration management",
    "playbook",
  ]),
  defineIcon("n8n", "n8n", "devops-monitoring", n8n, [
    "n8n",
    "automation",
    "workflow",
  ]),
  defineIcon("node-red", "Node-RED", "devops-monitoring", nodered, [
    "node red",
    "node-red",
    "nodered",
    "automation",
    "iot",
  ]),
  defineIcon("rundeck", "Rundeck", "devops-monitoring", rundeck, [
    "rundeck",
    "runbook",
    "automation",
    "job scheduler",
  ]),
  defineIcon("puppet", "Puppet", "devops-monitoring", puppet, [
    "puppet",
    "configuration management",
    "automation",
  ]),
  defineIcon("gitea", "Gitea", "devops-monitoring", gitea, [
    "gitea",
    "git hosting",
    "source control",
    "self hosted",
  ]),
  defineIcon("minio", "MinIO", "devops-monitoring", minio, [
    "minio",
    "min io",
    "s3",
    "object storage",
  ]),
  defineIcon("prometheus", "Prometheus", "devops-monitoring", prometheus, [
    "prometheus",
    "prometherus",
    "metrics",
    "monitoring",
  ]),
  defineIcon(
    "prometheus-server",
    "Prometheus server",
    "devops-monitoring",
    createRoleIcon("PrometheusServer", "server", prometheus),
    ["prometheus server", "prometherus server", "prometheus", "metrics"],
  ),
  defineIcon(
    "elasticsearch",
    "Elasticsearch",
    "devops-monitoring",
    elasticsearch,
    [
      "elasticsearch",
      "selasticsearch",
      "elastic search",
      "search engine",
      "elk",
    ],
  ),
  defineIcon(
    "elasticsearch-server",
    "Elasticsearch server",
    "devops-monitoring",
    createRoleIcon("ElasticsearchServer", "server", elasticsearch),
    [
      "elasticsearch server",
      "selasticsearch server",
      "elasticsearch",
      "search cluster",
    ],
  ),
  defineIcon("jira", "Jira", "devops-monitoring", jira, [
    "jira",
    "atlassian",
    "issue tracking",
    "project management",
  ]),
  defineIcon("splunk", "Splunk", "devops-monitoring", splunk, [
    "splunk",
    "logs",
    "monitoring",
    "siem",
    "observability",
  ]),
  ...LLM_VARIANT_ICONS,
  ...DEVELOPER_TOOL_ICONS,
  ...SCRIPT_LANGUAGE_ICONS,
] as const;
