import {
  cloudflare,
  gandi,
  godaddy,
  namecheap,
  porkbun,
  namesilo,
  spaceship,
  dominios,
  dnsptIdentifier,
  amen,
  freenom,
  networksolutionsIdentifier,
  noip,
} from "../brand";
import { defineIcon } from "./types";
import { createLucideIcon } from "lucide-react";

/** Registrars, the .PT registry, and DNS services. Saved keys are unchanged. */
export const DOMAIN_REGISTRAR_ICONS = [
  defineIcon(
    "dynamic-dns",
    "Dynamic DNS",
    "domain-registrars",
    createLucideIcon("DynamicDnsService", [
      ["circle", { cx: "8", cy: "8", r: "6", key: "domain" }],
      [
        "path",
        {
          d: "M2 8h12M8 2c-3 3-3 9 0 12 3-3 3-9 0-12M17 9h4v4M21 9l-5 5M7 18a8 8 0 0 0 13 2M7 18v4M7 18h4",
          key: "update",
        },
      ],
    ]),
    [
      "dynamic dns",
      "dynamicdns",
      "ddns",
      "hostname",
      "ip update",
      "dns service",
    ],
    "Generic dynamic-DNS service icon; not a provider logo.",
  ),
  defineIcon("porkbun", "Porkbun", "domain-registrars", porkbun, [
    "porkbun",
    "porkbun.com",
    "pork bun",
    "domain registrar",
    "dns",
  ]),
  defineIcon("namecheap", "Namecheap", "domain-registrars", namecheap, [
    "namecheap",
    "namecheap.com",
    "name cheap",
    "domain registrar",
    "dns",
  ]),
  defineIcon("godaddy", "GoDaddy", "domain-registrars", godaddy, [
    "godaddy",
    "godaddy.com",
    "go daddy",
    "domain registrar",
    "dns",
  ]),
  defineIcon("gandi", "Gandi", "domain-registrars", gandi, [
    "gandi",
    "gandi.net",
    "domain registrar",
    "dns",
  ]),
  defineIcon("cloudflare", "Cloudflare", "domain-registrars", cloudflare, [
    "cloudflare",
    "cloudflare.com",
    "cloud flare",
    "domain registrar",
    "dns",
    "cdn",
  ]),
  defineIcon(
    "noip",
    "No-IP / Dynamic DNS",
    "domain-registrars",
    noip,
    [
      "noip",
      "noip.com",
      "no-ip",
      "no-ip.com",
      "no ip",
      "dynamic dns",
      "ddns",
      "hostname",
    ],
    "No-IP compact publisher mark traced from its raster into monochrome vector contours; not an original publisher SVG.",
  ),
  defineIcon(
    "dns-pt",
    "DNS.PT / .PT",
    "domain-registrars",
    dnsptIdentifier,
    [
      "dns.pt",
      "dns pt",
      "dnspt",
      "pt.pt",
      ".pt",
      "portugal",
      "domain registry",
      "dns",
    ],
    "DNS.PT app-authored .PT identifier; not an official logo.",
  ),
  defineIcon(
    "dominios-pt",
    "Domínios.pt",
    "domain-registrars",
    dominios,
    [
      "dominios.pt",
      "domínios.pt",
      "dominios",
      "domínios",
      "portugal",
      "domain registrar",
      "hosting",
    ],
    "Domínios.pt leading d extracted from the publisher wordmark and scaled in monochrome.",
  ),
  defineIcon(
    "amen-pt",
    "Amen.pt",
    "domain-registrars",
    amen,
    ["amen.pt", "amen", "amen pt", "portugal", "domain registrar", "hosting"],
    "Amen.pt compact publisher emblem, traced from its raster header into monochrome vector paths; not an original publisher SVG.",
  ),
  defineIcon(
    "freenom",
    "Freenom",
    "domain-registrars",
    freenom,
    ["freenom", "freenom.com", "free nom", "domain registrar", "dns", "legacy"],
    "Freenom historical mark from a pinned community collection; not a claim of current service availability.",
  ),
  defineIcon("namesilo", "NameSilo", "domain-registrars", namesilo, [
    "namesilo",
    "namesilo.com",
    "name silo",
    "domain registrar",
    "dns",
  ]),
  defineIcon(
    "network-solutions",
    "Network Solutions",
    "domain-registrars",
    networksolutionsIdentifier,
    [
      "network solutions",
      "networksolutions",
      "networksolutions.com",
      "domain registrar",
      "dns",
      "hosting",
    ],
    "Network Solutions app-authored initials identifier; not an official logo.",
  ),
  defineIcon("spaceship", "Spaceship", "domain-registrars", spaceship, [
    "spaceship",
    "spaceship.com",
    "spaceship registrar",
    "domain registrar",
    "dns",
    "hosting",
  ]),
] as const;
