import {
  Asterisk,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowLeftRight,
  Ban,
  BatteryCharging,
  Bookmark,
  BriefcaseBusiness,
  Building2,
  Circle,
  CircleDot,
  CircleDashed,
  CircleCheck,
  Clover,
  Clock3,
  CreditCard,
  ChartPie,
  createLucideIcon,
  Cross,
  Diamond,
  DiamondPlus,
  Flag,
  Heart,
  HeartCrack,
  Hexagon,
  Landmark,
  Moon,
  MailPlus,
  Octagon,
  Orbit,
  Pentagon,
  Power,
  RectangleHorizontal,
  RectangleVertical,
  Square,
  SquareDashed,
  Sparkles,
  Star,
  Sun,
  Tag,
  Triangle,
  TriangleRight,
  Target,
  UsersRound,
  Zap,
} from "lucide-react";

import { defineIcon } from "./types";
import { ORGANIZATION_MARKER_ICONS } from "./organizationMarkers";
import { FRUIT_ICONS } from "./fruits";
import { BUILDING_TYPE_ICONS } from "./buildingTypes";

const FilledHeart = createLucideIcon("FilledHeart", [
  [
    "path",
    {
      d: "M12 21 3.5 12.5a5.5 5.5 0 0 1 7.8-7.8l.7.7.7-.7a5.5 5.5 0 0 1 7.8 7.8Z",
      fill: "currentColor",
      stroke: "none",
      key: "heart",
    },
  ],
]);
const FilledStar = createLucideIcon("FilledStar", [
  [
    "path",
    {
      d: "m12 2 3.1 6.3 6.9 1-5 4.9 1.2 6.8-6.2-3.3-6.2 3.3L7 14.2 2 9.3l6.9-1Z",
      fill: "currentColor",
      stroke: "none",
      key: "star",
    },
  ],
]);
const FilledCircle = createLucideIcon("FilledCircle", [
  [
    "circle",
    {
      cx: "12",
      cy: "12",
      r: "9",
      fill: "currentColor",
      stroke: "none",
      key: "circle",
    },
  ],
]);
const FilledSquare = createLucideIcon("FilledSquare", [
  [
    "rect",
    {
      x: "3",
      y: "3",
      width: "18",
      height: "18",
      rx: "2",
      fill: "currentColor",
      stroke: "none",
      key: "square",
    },
  ],
]);
const FilledTriangle = createLucideIcon("FilledTriangle", [
  [
    "path",
    {
      d: "m12 3 10 18H2Z",
      fill: "currentColor",
      stroke: "none",
      key: "triangle",
    },
  ],
]);
const FilledDiamond = createLucideIcon("FilledDiamond", [
  [
    "path",
    {
      d: "m12 2 10 10-10 10L2 12Z",
      fill: "currentColor",
      stroke: "none",
      key: "diamond",
    },
  ],
]);

export const GENERIC_SHAPE_ICONS = [
  defineIcon("star", "Star", "generic-shapes", Star, ["favorite", "important"]),
  defineIcon("heart", "Heart", "generic-shapes", Heart, [
    "favorite",
    "health",
    "emoji",
    "love",
    "❤️",
    "♥",
  ]),
  defineIcon("circle", "Circle", "generic-shapes", Circle, ["shape"]),
  defineIcon("circle-dot", "Dot", "generic-shapes", CircleDot, [
    "status",
    "shape",
  ]),
  defineIcon("square", "Square", "generic-shapes", Square, ["shape"]),
  defineIcon("triangle", "Triangle", "generic-shapes", Triangle, [
    "shape",
    "warning",
  ]),
  defineIcon("diamond", "Diamond", "generic-shapes", Diamond, ["shape"]),
  defineIcon("hexagon", "Hexagon", "generic-shapes", Hexagon, ["shape"]),
  defineIcon("bookmark", "Bookmark", "generic-shapes", Bookmark, [
    "saved",
    "marker",
  ]),
  defineIcon("tag", "Tag", "generic-shapes", Tag, ["label", "organize"]),
  defineIcon("flag", "Flag", "generic-shapes", Flag, ["marker", "important"]),
  defineIcon("pentagon", "Pentagon", "generic-shapes", Pentagon, [
    "shape",
    "polygon",
    "five sides",
  ]),
  defineIcon("octagon", "Octagon", "generic-shapes", Octagon, [
    "shape",
    "polygon",
    "eight sides",
  ]),
  defineIcon(
    "rectangle-horizontal",
    "Horizontal rectangle",
    "generic-shapes",
    RectangleHorizontal,
    ["shape", "wide", "landscape"],
  ),
  defineIcon(
    "rectangle-vertical",
    "Vertical rectangle",
    "generic-shapes",
    RectangleVertical,
    ["shape", "tall", "portrait"],
  ),
  defineIcon(
    "triangle-right",
    "Right triangle",
    "generic-shapes",
    TriangleRight,
    ["shape", "angle", "triangle"],
  ),
  defineIcon("circle-dashed", "Dashed circle", "generic-shapes", CircleDashed, [
    "shape",
    "dashed",
    "outline",
  ]),
  defineIcon("square-dashed", "Dashed square", "generic-shapes", SquareDashed, [
    "shape",
    "dashed",
    "outline",
  ]),
  defineIcon("diamond-plus", "Diamond plus", "generic-shapes", DiamondPlus, [
    "shape",
    "diamond",
    "plus",
  ]),
  defineIcon("asterisk-shape", "Asterisk shape", "generic-shapes", Asterisk, [
    "shape",
    "starburst",
    "asterisk",
  ]),
  defineIcon("cross", "Cross", "generic-shapes", Cross, [
    "shape",
    "plus",
    "cross",
  ]),
  defineIcon("target", "Target", "generic-shapes", Target, [
    "shape",
    "bullseye",
    "rings",
  ]),
  defineIcon("orbit", "Orbit", "generic-shapes", Orbit, [
    "shape",
    "ellipse",
    "orbital",
  ]),
  defineIcon("building", "Building", "generic-shapes", Building2, [
    "building",
    "buildings",
    "premises",
    "site",
    "facility",
    "headquarters",
  ]),
  defineIcon("office", "Office", "generic-shapes", BriefcaseBusiness, [
    "office",
    "workplace",
    "business",
    "branch",
    "department",
  ]),
  defineIcon("people", "People", "generic-shapes", UsersRound, [
    "people",
    "persons",
    "users",
    "user group",
    "team",
    "staff",
    "employees",
  ]),
  defineIcon("corporate", "Corporate", "generic-shapes", Landmark, [
    "corporate",
    "generic corporate",
    "company",
    "enterprise",
    "organization",
    "headquarters",
    "business",
  ]),
  defineIcon("heart-filled", "Filled heart", "generic-shapes", FilledHeart, [
    "heart filled",
    "filled heart",
    "solid",
    "love",
    "emoji",
    "❤️",
    "♥",
  ]),
  defineIcon("heart-broken", "Broken heart", "generic-shapes", HeartCrack, [
    "heart broken",
    "broken heart",
    "heartbreak",
    "sad",
    "💔",
  ]),
  defineIcon("star-filled", "Filled star", "generic-shapes", FilledStar, [
    "star filled",
    "filled star",
    "solid",
    "favorite",
    "★",
    "⭐",
  ]),
  defineIcon("circle-filled", "Filled circle", "generic-shapes", FilledCircle, [
    "circle filled",
    "filled circle",
    "solid",
    "dot",
    "●",
  ]),
  defineIcon("square-filled", "Filled square", "generic-shapes", FilledSquare, [
    "square filled",
    "filled square",
    "solid",
    "block",
    "■",
  ]),
  defineIcon(
    "triangle-filled",
    "Filled triangle",
    "generic-shapes",
    FilledTriangle,
    ["triangle filled", "filled triangle", "solid", "▲"],
  ),
  defineIcon(
    "diamond-filled",
    "Filled diamond",
    "generic-shapes",
    FilledDiamond,
    ["diamond filled", "filled diamond", "solid", "◆"],
  ),
  defineIcon("arrow-up", "Up arrow", "generic-shapes", ArrowUp, [
    "arrow up",
    "up arrow",
    "north",
    "direction",
    "⬆️",
  ]),
  defineIcon("arrow-down", "Down arrow", "generic-shapes", ArrowDown, [
    "arrow down",
    "down arrow",
    "south",
    "direction",
    "⬇️",
  ]),
  defineIcon("arrow-left", "Left arrow", "generic-shapes", ArrowLeft, [
    "arrow left",
    "left arrow",
    "west",
    "direction",
    "⬅️",
  ]),
  defineIcon("arrow-right", "Right arrow", "generic-shapes", ArrowRight, [
    "arrow right",
    "right arrow",
    "east",
    "direction",
    "➡️",
  ]),
  defineIcon("lightning", "Lightning", "generic-shapes", Zap, [
    "lightning",
    "bolt",
    "electric",
    "power",
    "⚡",
  ]),
  defineIcon("check-circle", "Check circle", "generic-shapes", CircleCheck, [
    "check circle",
    "checkmark",
    "approved",
    "complete",
    "success",
    "✅",
  ]),
  defineIcon("prohibited", "Prohibited", "generic-shapes", Ban, [
    "prohibited",
    "forbidden",
    "blocked",
    "ban",
    "no entry",
    "🚫",
  ]),
  defineIcon("clover", "Clover", "generic-shapes", Clover, [
    "clover",
    "luck",
    "lucky",
    "four leaf",
    "🍀",
  ]),
  defineIcon("sparkles", "Sparkles", "generic-shapes", Sparkles, [
    "sparkles",
    "shine",
    "magic",
    "new",
    "✨",
  ]),
  defineIcon("sun", "Sun", "generic-shapes", Sun, [
    "sun",
    "day",
    "sunlight",
    "weather",
    "☀️",
  ]),
  defineIcon("moon", "Moon", "generic-shapes", Moon, [
    "moon",
    "night",
    "crescent",
    "🌙",
  ]),
  defineIcon("clock", "Clock", "generic-shapes", Clock3, [
    "clock",
    "time",
    "time server",
    "time clock",
    "schedule",
    "plain",
  ]),
  defineIcon(
    "battery-charging",
    "Charging battery",
    "generic-shapes",
    BatteryCharging,
    [
      "battery charging",
      "charging battery",
      "ups",
      "backup power",
      "battery",
      "plain",
    ],
  ),
  defineIcon("power", "Power", "generic-shapes", Power, [
    "power",
    "on off",
    "power control",
    "pdu",
    "electric",
    "plain",
  ]),
  defineIcon("transfer", "Transfer", "generic-shapes", ArrowLeftRight, [
    "transfer",
    "exchange",
    "traffic",
    "proxy tunnel",
    "wired router",
    "bidirectional",
    "plain",
  ]),
  defineIcon("mail-plus", "Mail relay", "generic-shapes", MailPlus, [
    "mail plus",
    "mail relay",
    "mta",
    "mail transfer agent",
    "email",
    "plain",
  ]),
  defineIcon("payment-card", "Payment card", "generic-shapes", CreditCard, [
    "payment card",
    "credit card",
    "pos",
    "point of sale",
    "payment",
    "plain",
  ]),
  defineIcon("pie-chart", "Pie chart", "generic-shapes", ChartPie, [
    "pie chart",
    "business analytics",
    "business intelligence",
    "analytics",
    "reporting",
    "plain",
  ]),
  ...ORGANIZATION_MARKER_ICONS,
  ...BUILDING_TYPE_ICONS,
  ...FRUIT_ICONS,
] as const;
