import {
  hostinger,
  ionos,
  netcup,
  upcloud,
  wpengine,
  wix,
  rackspace,
  contabo,
  vultr,
  exoscale,
  hostgatorIdentifier,
  ptispIdentifier,
  ptservidorIdentifier,
  webtugaIdentifier,
  time4vpsIdentifier,
  bluehost,
} from "../brand";
import { defineIcon } from "./types";

/** Primary hosting category. Mixed-service entries also carry domain aliases. */
export const HOSTING_PROVIDER_ICONS = [
  defineIcon("contabo", "Contabo", "hosting-providers", contabo, [
    "contabo",
    "contabo.com",
    "hosting",
    "vps",
    "dedicated server",
  ]),
  defineIcon("vultr", "Vultr", "hosting-providers", vultr, [
    "vultr",
    "vultr.com",
    "cloud",
    "hosting",
    "vps",
  ]),
  defineIcon("exoscale", "Exoscale", "hosting-providers", exoscale, [
    "exoscale",
    "exoscale.com",
    "exo scale",
    "cloud",
    "hosting",
  ]),
  defineIcon(
    "hostgator",
    "HostGator",
    "hosting-providers",
    hostgatorIdentifier,
    ["hostgator", "hostgator.com", "host gator", "hosting", "domain registrar"],
    "HostGator app-authored initials identifier; not an official logo.",
  ),
  defineIcon("ionos", "IONOS", "hosting-providers", ionos, [
    "ionos",
    "ionos.com",
    "1and1",
    "1 1",
    "domain registrar",
    "dns",
    "hosting",
  ]),
  defineIcon(
    "ptisp",
    "PTisp",
    "hosting-providers",
    ptispIdentifier,
    [
      "ptisp",
      "ptisp.pt",
      "ptisp.com",
      "pt isp",
      "portugal",
      "alojamento",
      "hosting",
      "vps",
    ],
    "PTisp app-authored initials identifier; not an official logo.",
  ),
  defineIcon(
    "ptservidor",
    "PTServidor",
    "hosting-providers",
    ptservidorIdentifier,
    [
      "ptservidor",
      "ptservidor.pt",
      "pt servidor",
      "portugal",
      "alojamento",
      "hosting",
    ],
    "PTServidor app-authored initials identifier; not an official logo.",
  ),
  defineIcon(
    "webtuga",
    "WebTuga",
    "hosting-providers",
    webtugaIdentifier,
    [
      "webtuga",
      "webtuga.pt",
      "webtuga.com",
      "web tuga",
      "portugal",
      "alojamento",
      "hosting",
    ],
    "WebTuga app-authored initials identifier; not an official logo.",
  ),
  defineIcon(
    "time4vps",
    "Time4VPS",
    "hosting-providers",
    time4vpsIdentifier,
    ["time4vps", "time4vps.com", "time 4 vps", "vps", "hosting"],
    "Time4VPS app-authored clock-and-four identifier; not an official logo.",
  ),
  defineIcon("hostinger", "Hostinger", "hosting-providers", hostinger, [
    "hostinger",
    "hostinger.com",
    "hostinger.pt",
    "hosting",
    "domain registrar",
  ]),
  defineIcon("netcup", "netcup", "hosting-providers", netcup, [
    "netcup",
    "netcup.com",
    "netcup.de",
    "net cup",
    "hosting",
    "vps",
  ]),
  defineIcon("upcloud", "UpCloud", "hosting-providers", upcloud, [
    "upcloud",
    "upcloud.com",
    "up cloud",
    "cloud",
    "hosting",
    "vps",
  ]),
  defineIcon("wpengine", "WP Engine", "hosting-providers", wpengine, [
    "wpengine",
    "wpengine.com",
    "wp engine",
    "wordpress",
    "hosting",
  ]),
  defineIcon(
    "bluehost",
    "Bluehost",
    "hosting-providers",
    bluehost,
    [
      "bluehost",
      "bluehost.com",
      "blue host",
      "wordpress",
      "hosting",
      "domain registrar",
    ],
    "Bluehost 2019 grid emblem from the attributed historical SVG; monochrome, without the wordmark.",
  ),
  defineIcon(
    "rackspace",
    "Rackspace",
    "hosting-providers",
    rackspace,
    ["rackspace", "rackspace.com", "rack space", "hosting", "cloud", "managed"],
    "Rackspace leading r extracted from the publisher wordmark, uniformly scaled in monochrome.",
  ),
  defineIcon("wix", "Wix", "hosting-providers", wix, [
    "wix",
    "wix.com",
    "website builder",
    "site builder",
    "hosting",
    "domain registrar",
  ]),
] as const;
