import {
  ArrowLeftRight,
  Cable,
  Clock3,
  createLucideIcon,
  DoorOpen,
  Globe,
  Link,
  Network,
  Radar,
  Radio,
  RadioTower,
  Route,
  Router,
  Share2,
  Waypoints,
  Wifi,
} from "lucide-react";
import { NETWORK_VARIANT_ICONS } from "./networkVariants";

import {
  apple,
  bind,
  cisco,
  ddwrt,
  freshtomato,
  microsoft,
  netbox,
  openldap,
  openvpn,
  samba,
  wireguard,
} from "../brand";
import { createRoleIcon } from "../createRoleIcon";
import { defineIcon } from "./types";
import { VPN_TYPE_ICONS } from "./vpnTypes";

const RackRouter = createLucideIcon("RackRouter", [
  [
    "rect",
    { x: "2", y: "6", width: "20", height: "12", rx: "1", key: "rack-chassis" },
  ],
  [
    "path",
    {
      d: "M5 6v12M19 6v12M3.5 9h.01M20.5 9h.01M3.5 15h.01M20.5 15h.01",
      key: "rack-mounts",
    },
  ],
  ["path", { d: "M8 10h8m-2-2 2 2-2 2M16 14H8m2-2-2 2 2 2", key: "routing" }],
]);
const EdgeRouter = createLucideIcon("EdgeRouter", [
  ["path", { d: "m2 8 4-4h12l4 4v12H2V8ZM2 8h20", key: "edge-chassis" }],
  ["path", { d: "M6 12h12m-2-2 2 2-2 2M18 17H6m2-2-2 2 2 2", key: "routing" }],
]);
const WirelessRouter = createLucideIcon("WirelessRouter", [
  [
    "rect",
    {
      x: "2",
      y: "13",
      width: "20",
      height: "8",
      rx: "2",
      key: "wireless-chassis",
    },
  ],
  [
    "path",
    {
      d: "M5 17h.01M8 17h.01M11 17h.01M5 6a10 10 0 0 1 14 0M8 9a6 6 0 0 1 8 0M11 11.5h2",
      key: "wifi-status",
    },
  ],
]);

export const NETWORK_ICONS = [
  defineIcon("globe", "Web", "network", Globe, ["http", "https", "internet"]),
  defineIcon("network", "Network", "network", Network, [
    "lan",
    "topology",
    "netbox",
  ]),
  defineIcon("router", "Router", "network", Router, [
    "gateway",
    "appliance",
    "draytek",
  ]),
  defineIcon("wifi", "Wireless", "network", Wifi, ["wifi", "wlan"]),
  defineIcon("cable", "Wired connection", "network", Cable, [
    "ethernet",
    "wired",
    "serial",
    "rs-232",
    "com port",
    "tty",
    "console cable",
  ]),
  defineIcon("waypoints", "Route", "network", Waypoints, [
    "proxy",
    "traefik",
    "path",
  ]),
  defineIcon("radio-tower", "Radio tower", "network", RadioTower, [
    "wireless",
    "signal",
  ]),
  defineIcon("route", "Network route", "network", Route, ["routing", "path"]),
  defineIcon("link", "Link", "network", Link, ["connection", "chain"]),
  defineIcon("share", "Shared network", "network", Share2, ["share", "smb"]),
  defineIcon("radio", "Radio", "network", Radio, ["wol", "signal"]),
  defineIcon(
    "freshtomato",
    "FreshTomato",
    "network",
    freshtomato,
    [
      "freshtomato",
      "fresh tomato",
      "tomato firmware",
      "router firmware",
      "broadcom",
    ],
    "FreshTomato firmware connection icon: app-authored tomato identifier, not an official project logo.",
  ),
  defineIcon(
    "dns-server",
    "DNS server",
    "network",
    createRoleIcon("DNSServer", "server", Globe),
    ["dns server", "domain name", "resolver", "bind", "unbound"],
  ),
  defineIcon(
    "time-server",
    "Time server",
    "network",
    createRoleIcon("TimeServer", "server", Clock3),
    ["time server", "ntp", "sntp", "chrony", "clock synchronization"],
  ),
  defineIcon(
    "isp-router",
    "ISP router",
    "network",
    createRoleIcon("ISPRouter", "router", Globe),
    ["isp router", "internet provider", "broadband", "wan", "cpe"],
  ),
  defineIcon("gateway", "Gateway", "network", DoorOpen, [
    "gateway",
    "network gateway",
    "edge",
    "ingress",
    "egress",
  ]),
  defineIcon("openvpn", "OpenVPN", "network", openvpn, [
    "openvpn",
    "open vpn",
    "vpn",
    "tunnel",
  ]),
  defineIcon(
    "openvpn-server",
    "OpenVPN server",
    "network",
    createRoleIcon("OpenVPNServer", "server", openvpn),
    ["openvpn", "open vpn", "vpn server", "tunnel"],
  ),
  defineIcon("wireguard", "WireGuard", "network", wireguard, [
    "wireguard",
    "wire guard",
    "vpn",
    "wg",
  ]),
  defineIcon(
    "wireguard-server",
    "WireGuard server",
    "network",
    createRoleIcon("WireGuardServer", "server", wireguard),
    ["wireguard", "wire guard", "vpn server", "wg"],
  ),
  defineIcon(
    "bind-server",
    "BIND DNS server",
    "network",
    createRoleIcon("BINDServer", "server", bind),
    ["bind", "bind server", "bind9", "isc", "dns server", "named"],
    "BIND DNS server using an app-authored B/DNS identifier, not an official ISC logo.",
  ),
  defineIcon("netbox", "NetBox", "network", netbox, [
    "netbox",
    "net box",
    "ipam",
    "dcim",
    "network source of truth",
  ]),
  defineIcon(
    "openldap",
    "OpenLDAP",
    "network",
    openldap,
    ["openldap", "open ldap", "directory server", "ldap"],
    "OpenLDAP using an app-authored linked-directory identifier, not an official project logo.",
  ),
  defineIcon(
    "samba",
    "Samba",
    "network",
    samba,
    ["samba", "smb", "cifs", "file sharing", "domain"],
    "Samba using an app-authored shared-directory identifier, not an official project logo.",
  ),
  defineIcon(
    "custom-vpn",
    "Custom VPN",
    "network",
    createRoleIcon("CustomVPN", "vpn", Cable),
    ["custom vpn", "generic vpn", "vpn tunnel", "private network"],
  ),
  defineIcon(
    "apple-vpn",
    "Apple VPN",
    "network",
    createRoleIcon("AppleVPN", "vpn", apple),
    ["apple vpn", "mac vpn", "macos vpn", "ios vpn"],
    "Apple brand mark in an app-authored VPN shield/tunnel frame, not an official Apple VPN product logo.",
  ),
  defineIcon(
    "microsoft-vpn",
    "Microsoft VPN",
    "network",
    createRoleIcon("MicrosoftVPN", "vpn", microsoft),
    ["microsoft vpn", "windows vpn", "rras", "sstp"],
    "Microsoft brand mark in an app-authored VPN shield/tunnel frame, not an official Microsoft VPN product logo.",
  ),
  defineIcon(
    "cisco-vpn",
    "Cisco VPN",
    "network",
    createRoleIcon("CiscoVPN", "vpn", cisco),
    ["cisco vpn", "anyconnect", "secure client", "vpn"],
    "Cisco brand mark in an app-authored VPN shield/tunnel frame, not the Cisco Secure Client application logo.",
  ),
  defineIcon(
    "proxy-tunnel",
    "Proxy tunnel",
    "network",
    createRoleIcon("ProxyTunnel", "vpn", ArrowLeftRight),
    ["proxy tunnel", "tunnel", "socks", "http connect", "ssh tunnel"],
  ),
  defineIcon(
    "wired-router",
    "Wired router",
    "network",
    createRoleIcon("WiredRouter", "wired-router", ArrowLeftRight),
    [
      "wired router",
      "generic router",
      "generic router variant",
      "network router",
      "ethernet router",
    ],
    "Generic wired-routing appliance with traffic arrows, not a firewall or vendor product logo.",
  ),
  defineIcon("snmp", "SNMP", "network", Radar, [
    "snmp",
    "generic snmp",
    "network monitoring",
    "polling",
    "management protocol",
  ]),
  defineIcon("router-rack", "Rack router", "network", RackRouter, [
    "rack router",
    "router rack",
    "rackmount",
    "rack mount",
    "routing",
    "appliance",
    "router variant",
  ]),
  defineIcon("router-edge", "Edge router", "network", EdgeRouter, [
    "edge router",
    "router edge",
    "border router",
    "gateway",
    "wan",
    "appliance",
    "router variant",
  ]),
  defineIcon("router-wireless", "Wireless router", "network", WirelessRouter, [
    "wireless router",
    "router wireless",
    "wifi router",
    "wlan",
    "broadband",
    "router variant",
  ]),
  defineIcon(
    "ddwrt",
    "DD-WRT",
    "network",
    ddwrt,
    ["ddwrt", "dd-wrt", "dd wrt", "router firmware", "open firmware"],
    "DD-WRT connection icon with an app-authored identifier; not an official DD-WRT logo.",
  ),
  defineIcon(
    "ddwrt-router",
    "DD-WRT router",
    "network",
    createRoleIcon("DdWrtRouter", "router", ddwrt),
    [
      "ddwrt router",
      "dd-wrt router",
      "dd wrt router",
      "firmware",
      "wireless router",
    ],
    "DD-WRT router with an app-authored identifier; not an official DD-WRT logo.",
  ),
  ...VPN_TYPE_ICONS,
  ...NETWORK_VARIANT_ICONS,
] as const;
