import {
  Banknote,
  CircuitBoard,
  Factory,
  GraduationCap,
  HardHat,
  Hospital,
  Hotel,
  Landmark,
  SatelliteDish,
  Scale,
  ShieldCheck,
  Store,
  Tractor,
  UtilityPole,
  UtensilsCrossed,
  Warehouse,
} from "lucide-react";

import { defineIcon } from "./types";

/** Sector markers use the existing generic-shapes category, not brand logos. */
export const ORGANIZATION_MARKER_ICONS = [
  defineIcon(
    "company-healthcare",
    "Healthcare company",
    "generic-shapes",
    Hospital,
    [
      "company healthcare",
      "healthcare",
      "health care",
      "hospital",
      "clinic",
      "medical",
      "industry",
    ],
  ),
  defineIcon(
    "company-education",
    "Education company",
    "generic-shapes",
    GraduationCap,
    [
      "company education",
      "education",
      "school",
      "university",
      "college",
      "training",
      "industry",
    ],
  ),
  defineIcon(
    "company-finance",
    "Finance and banking company",
    "generic-shapes",
    Banknote,
    [
      "company finance",
      "finance",
      "banking",
      "bank",
      "financial services",
      "payments",
      "industry",
    ],
  ),
  defineIcon(
    "company-insurance",
    "Insurance company",
    "generic-shapes",
    ShieldCheck,
    [
      "company insurance",
      "insurance",
      "insurer",
      "policy",
      "coverage",
      "industry",
    ],
  ),
  defineIcon("company-retail", "Retail company", "generic-shapes", Store, [
    "company retail",
    "retail",
    "shop",
    "store",
    "commerce",
    "merchant",
    "industry",
  ]),
  defineIcon(
    "company-manufacturing",
    "Manufacturing company",
    "generic-shapes",
    Factory,
    [
      "company manufacturing",
      "manufacturing",
      "factory",
      "industrial",
      "production",
      "industry",
    ],
  ),
  defineIcon(
    "company-construction",
    "Construction company",
    "generic-shapes",
    HardHat,
    [
      "company construction",
      "construction",
      "contractor",
      "builder",
      "engineering",
      "industry",
    ],
  ),
  defineIcon(
    "company-logistics",
    "Logistics and warehouse company",
    "generic-shapes",
    Warehouse,
    [
      "company logistics",
      "logistics",
      "warehouse",
      "warehousing",
      "distribution",
      "shipping",
      "supply chain",
      "industry",
    ],
  ),
  defineIcon(
    "company-hospitality",
    "Hospitality and hotel company",
    "generic-shapes",
    Hotel,
    [
      "company hospitality",
      "hospitality",
      "hotel",
      "lodging",
      "accommodation",
      "tourism",
      "industry",
    ],
  ),
  defineIcon(
    "company-restaurant",
    "Restaurant company",
    "generic-shapes",
    UtensilsCrossed,
    [
      "company restaurant",
      "restaurant",
      "dining",
      "food service",
      "catering",
      "industry",
    ],
  ),
  defineIcon(
    "company-agriculture",
    "Agriculture company",
    "generic-shapes",
    Tractor,
    [
      "company agriculture",
      "agriculture",
      "farming",
      "farm",
      "agribusiness",
      "industry",
    ],
  ),
  defineIcon(
    "company-government",
    "Government organization",
    "generic-shapes",
    Landmark,
    [
      "company government",
      "government",
      "public sector",
      "municipality",
      "civic",
      "agency",
      "industry",
    ],
  ),
  defineIcon("company-legal", "Legal company", "generic-shapes", Scale, [
    "company legal",
    "legal",
    "law",
    "law firm",
    "attorney",
    "justice",
    "industry",
  ]),
  defineIcon(
    "company-technology",
    "Technology and IT company",
    "generic-shapes",
    CircuitBoard,
    [
      "company technology",
      "technology",
      "it",
      "information technology",
      "software",
      "computing",
      "industry",
    ],
  ),
  defineIcon(
    "company-telecom",
    "Telecom company",
    "generic-shapes",
    SatelliteDish,
    [
      "company telecom",
      "telecom",
      "telecommunications",
      "carrier",
      "communications",
      "industry",
    ],
  ),
  defineIcon(
    "company-energy",
    "Energy and utilities company",
    "generic-shapes",
    UtilityPole,
    [
      "company energy",
      "energy",
      "utilities",
      "utility",
      "electricity",
      "power",
      "industry",
    ],
  ),
] as const;
