import {
  ArrowUpDown,
  CopyCheck,
  createLucideIcon,
  FolderLock,
  MonitorUp,
  SquareTerminal,
} from "lucide-react";

import {
  citrix,
  dameware,
  filezilla,
  microsoft,
  mremoteng,
  openssh,
  tightvnc,
  ultravnc,
} from "../brand";
import { createRoleIcon } from "../createRoleIcon";
import { defineIcon } from "./types";

const SerialConnector = createLucideIcon("SerialConnector", [
  ["path", { d: "M3 6h18l-2 12H5L3 6Z", key: "connector-shell" }],
  [
    "path",
    {
      d: "M7 10h.01M12 10h.01M17 10h.01M9.5 14h.01M14.5 14h.01",
      key: "connector-pins",
    },
  ],
  ["path", { d: "M1 11v2M23 11v2", key: "connector-mounts" }],
]);

/** Explicit remote tool choices; protocol defaults remain unchanged. */
export const REMOTE_TOOL_ICONS = [
  defineIcon("vnc", "VNC", "remote-protocols", MonitorUp, [
    "vnc",
    "generic vnc",
    "virtual network computing",
    "rfb",
    "remote framebuffer",
    "screen sharing",
  ]),
  defineIcon(
    "serial",
    "Serial connection",
    "remote-protocols",
    SerialConnector,
    [
      "serial",
      "serial connection",
      "serial connections",
      "rs232",
      "rs-232",
      "console cable",
      "com port",
      "uart",
    ],
  ),
  defineIcon(
    "serial-switch",
    "Serial to switch",
    "remote-protocols",
    createRoleIcon("SerialSwitch", "switch", SerialConnector),
    [
      "serial",
      "serial to switch",
      "serial switch",
      "console",
      "switch console",
      "rs232",
    ],
  ),
  defineIcon(
    "serial-router",
    "Serial to router",
    "remote-protocols",
    createRoleIcon("SerialRouter", "router", SerialConnector),
    [
      "serial",
      "serial to router",
      "serial router",
      "console",
      "router console",
      "rs232",
    ],
  ),
  defineIcon(
    "serial-hardware",
    "Serial to hardware",
    "remote-protocols",
    createRoleIcon("SerialHardware", "server", SerialConnector),
    [
      "serial",
      "serial to hardware",
      "serial hardware",
      "device console",
      "rs232",
      "console port",
    ],
  ),
  defineIcon("telnet", "Telnet", "remote-protocols", SquareTerminal, [
    "telnet",
    "terminal",
    "remote shell",
    "tcp 23",
    "plaintext",
  ]),
  defineIcon(
    "ftp-server",
    "FTP server",
    "remote-protocols",
    createRoleIcon("FtpServer", "server", ArrowUpDown),
    ["ftp server", "ftp", "file transfer protocol", "upload", "download"],
  ),
  defineIcon(
    "sftp-server",
    "SFTP server",
    "remote-protocols",
    createRoleIcon("SftpServer", "server", FolderLock),
    ["sftp server", "sftp", "ssh file transfer", "secure file transfer", "ssh"],
  ),
  defineIcon("scp", "SCP", "remote-protocols", CopyCheck, [
    "scp",
    "secure copy",
    "ssh",
    "file transfer",
  ]),
  defineIcon(
    "scp-server",
    "SCP server",
    "remote-protocols",
    createRoleIcon("ScpServer", "server", CopyCheck),
    ["scp server", "scp", "secure copy", "ssh", "file transfer"],
  ),
  defineIcon("filezilla", "FileZilla", "remote-protocols", filezilla, [
    "filezilla",
    "file zilla",
    "ftp",
    "sftp",
    "ftps",
    "file transfer client",
  ]),
  defineIcon(
    "openssh",
    "OpenSSH",
    "remote-protocols",
    openssh,
    ["openssh", "open ssh", "ssh", "secure shell", "sshd", "remote access"],
    "OpenSSH connection icon with an app-authored identifier; not an official OpenSSH logo.",
  ),
  defineIcon(
    "mremoteng",
    "mRemoteNG",
    "remote-protocols",
    mremoteng,
    [
      "mremoteng",
      "mremote ng",
      "mremote",
      "remote connection manager",
      "rdp",
      "ssh",
      "vnc",
    ],
    "mRemoteNG connection icon with an app-authored identifier; not an official mRemoteNG logo.",
  ),
  defineIcon(
    "ultravnc",
    "UltraVNC",
    "remote-protocols",
    ultravnc,
    [
      "ultravnc",
      "ultra vnc",
      "uvnc",
      "vnc",
      "remote framebuffer",
      "screen sharing",
    ],
    "UltraVNC connection icon using a monochrome adaptation of the publisher's eye symbol, not its full gradient and text logo.",
  ),
  defineIcon("tightvnc", "TightVNC", "remote-protocols", tightvnc, [
    "tightvnc",
    "tight vnc",
    "vnc",
    "remote framebuffer",
    "screen sharing",
  ]),
  defineIcon("citrix", "Citrix", "remote-protocols", citrix, [
    "citrix",
    "workspace",
    "ica",
    "hdx",
    "virtual apps",
    "virtual desktops",
  ]),
  defineIcon(
    "citrix-web",
    "Citrix web",
    "remote-protocols",
    createRoleIcon("CitrixWeb", "cloud", citrix),
    [
      "citrix web",
      "citrix",
      "workspace web",
      "storefront",
      "web access",
      "browser",
      "web interface",
    ],
  ),
  defineIcon(
    "microsoft-rd-gateway",
    "Microsoft Remote Desktop Gateway",
    "remote-protocols",
    createRoleIcon("MicrosoftRdGateway", "router", microsoft),
    [
      "microsoft remote desktop gateway",
      "microsoft remtoe desktop gateway",
      "microsoft rd gateway",
      "ms rd gateway",
      "rd gateway",
      "rdgateway",
      "rdg",
      "rdp gateway",
      "remote desktop services",
    ],
    "Remote Desktop Gateway with a gateway silhouette and the Microsoft brand mark, not a separate RD Gateway product logo.",
  ),
  defineIcon(
    "dameware",
    "Dameware",
    "remote-protocols",
    dameware,
    [
      "dameware",
      "dame ware",
      "solarwinds",
      "remote support",
      "remote control",
      "mini remote control",
    ],
    "Dameware identified by its SolarWinds publisher swoosh, traced from the official product site's header. Not a separate Dameware product logo.",
  ),
] as const;
