import { RadioTower } from "lucide-react";

import {
  altice,
  atandt,
  deutschetelekom,
  digi,
  hurricaneelectric,
  meo,
  movistar,
  nos,
  nowo,
  o2,
  orange,
  sfr,
  tele2,
  three,
  tmobile,
  uzo,
  viva,
  vodafone,
} from "../brand";
import { defineIcon } from "./types";

/** Carrier choices share the existing network category and stable key contract. */
export const TELECOM_ICONS = [
  defineIcon("telecom", "Telecom", "network", RadioTower, [
    "telecom",
    "generic telecom",
    "telecommunications",
    "carrier",
    "operator",
    "mobile network",
    "internet provider",
    "isp",
  ]),
  defineIcon("vodafone", "Vodafone", "network", vodafone, [
    "vodafone",
    "telecom",
    "mobile operator",
    "carrier",
    "broadband",
    "isp",
  ]),
  defineIcon(
    "deutsche-telekom",
    "Deutsche Telekom",
    "network",
    deutschetelekom,
    [
      "deutsche telekom",
      "deustch telekom",
      "deutschetelekom",
      "telekom",
      "telecom",
      "carrier",
    ],
  ),
  defineIcon("orange", "Orange", "network", orange, [
    "orange",
    "orange telecom",
    "telecom",
    "mobile operator",
    "carrier",
    "broadband",
  ]),
  defineIcon("o2", "O2", "network", o2, [
    "o2",
    "o 2",
    "telecom",
    "mobile operator",
    "carrier",
    "broadband",
  ]),
  defineIcon("att", "AT&T", "network", atandt, [
    "at&t",
    "at and t",
    "atandt",
    "att",
    "telecom",
    "carrier",
    "internet provider",
  ]),
  defineIcon("movistar", "Movistar", "network", movistar, [
    "movistar",
    "telefonica",
    "telecom",
    "mobile operator",
    "carrier",
    "broadband",
  ]),
  defineIcon(
    "t-mobile",
    "T-Mobile",
    "network",
    tmobile,
    [
      "t-mobile",
      "t mobile",
      "tmobile",
      "telecom",
      "mobile operator",
      "carrier",
    ],
    "T-Mobile connection icon using the historical T-Mobile brand mark.",
  ),
  defineIcon(
    "meo",
    "MEO",
    "network",
    meo,
    ["meo", "telecom", "mobile operator", "broadband", "internet provider"],
    "MEO connection icon with an app-authored identifier; not an official MEO logo.",
  ),
  defineIcon("nos", "NOS", "network", nos, [
    "nos",
    "nos telecom",
    "telecom",
    "mobile operator",
    "broadband",
    "carrier",
  ]),
  defineIcon("digi", "DIGI", "network", digi, [
    "digi",
    "digi telecom",
    "telecom",
    "mobile operator",
    "broadband",
    "carrier",
  ]),
  defineIcon(
    "viva",
    "VIVA",
    "network",
    viva,
    ["viva", "telecom", "carrier", "operator", "neutral identifier"],
    "Neutral VIVA telecom identifier authored by the app; not an official logo and not assigned to a particular regional provider.",
  ),
  defineIcon(
    "uzo",
    "UZO",
    "network",
    uzo,
    ["uzo", "telecom", "mobile operator", "broadband", "internet provider"],
    "UZO connection icon with an app-authored identifier; not an official UZO logo.",
  ),
  defineIcon("tele2", "Tele2", "network", tele2, [
    "tele2",
    "tele 2",
    "telecom",
    "mobile operator",
    "broadband",
    "carrier",
  ]),
  defineIcon("sfr", "SFR", "network", sfr, [
    "sfr",
    "telecom",
    "mobile operator",
    "broadband",
    "internet provider",
  ]),
  defineIcon(
    "altice",
    "Altice",
    "network",
    altice,
    ["altice", "altice europe", "telecom", "carrier", "broadband"],
    "Altice connection icon using an archived official Altice Europe mark.",
  ),
  defineIcon("three", "Three", "network", three, [
    "three",
    "3",
    "three telecom",
    "telecom",
    "mobile operator",
    "carrier",
  ]),
  defineIcon(
    "hurricane-electric",
    "Hurricane Electric",
    "network",
    hurricaneelectric,
    [
      "hurricane electric",
      "hurricane eletric",
      "hurricaneelectric",
      "he",
      "he net",
      "transit",
      "ipv6",
      "internet provider",
    ],
    "Hurricane Electric connection icon with an app-authored HE identifier; not an official Hurricane Electric logo.",
  ),
  defineIcon(
    "nowo",
    "NOWO",
    "network",
    nowo,
    ["nowo", "telecom", "mobile operator", "broadband", "internet provider"],
    "NOWO connection icon using the NOWO lettering from the publisher's DIGI/NOWO mark.",
  ),
] as const;
