import {
  Antenna,
  Cable,
  createLucideIcon,
  HardDriveDownload,
  Merge,
  Settings,
  Zap,
} from "lucide-react";

import {
  acer,
  amcrest,
  apc,
  apple,
  aristaIdentifier,
  asus,
  avaya,
  axis,
  brother,
  canon,
  cisco,
  clevo,
  cyberpower,
  dahua,
  dell,
  draytek,
  eaton,
  epson,
  fujitsu,
  hanwha,
  hikvision,
  hp,
  hpe,
  huawei,
  intel,
  junipernetworks,
  kyocera,
  lenovo,
  leveloneIdentifier,
  lg,
  mikrotik,
  msi,
  qnap,
  razer,
  reolink,
  riello,
  samsung,
  schneiderelectric,
  supermicro,
  synology,
  toshiba,
  tplink,
  tripplite,
  truenas,
  ubiquiti,
  ugreen,
  uniview,
  vertiv,
  windows,
  xerox,
} from "../brand";
import { createRoleIcon } from "../createRoleIcon";
import { defineIcon } from "./types";

/**
 * Vendor and hardware icons. Seeded with generic Lucide entries so the category
 * is never empty; brand marks (Cisco, HP, Dell, TP-Link, ...) are appended by
 * later work without touching the entries below.
 */
const CeilingAccessPoint = createLucideIcon("CeilingAccessPoint", [
  ["circle", { cx: "12", cy: "12", r: "10", key: "ceiling-disc" }],
  ["circle", { cx: "12", cy: "12", r: "5", key: "radio-ring" }],
  ["path", { d: "M10 19h4", key: "status" }],
]);
const WallAccessPoint = createLucideIcon("WallAccessPoint", [
  [
    "rect",
    { x: "6", y: "2", width: "12", height: "20", rx: "2", key: "wall-unit" },
  ],
  [
    "path",
    {
      d: "M9 8a5 5 0 0 1 6 0M11 11h2M6 16h12M9 19h.01M15 19h.01",
      key: "wifi-ports",
    },
  ],
]);

export const VENDORS_HARDWARE_ICONS = [
  defineIcon("switch", "Network switch", "vendors-hardware", Merge, [
    "switch",
    "ethernet switch",
    "lan switch",
    "port",
    "patch panel",
  ]),
  defineIcon("access-point", "Access point", "vendors-hardware", Antenna, [
    "access point",
    "ap",
    "wifi",
    "wireless",
    "wlan",
  ]),
  defineIcon("nas", "NAS", "vendors-hardware", HardDriveDownload, [
    "nas",
    "network attached storage",
    "file storage",
    "qnap",
    "array",
  ]),
  defineIcon(
    "synology-nas",
    "Synology NAS",
    "vendors-hardware",
    createRoleIcon("SynologyNAS", "nas", synology),
    ["synology", "nas", "diskstation", "dsm"],
  ),
  defineIcon(
    "dell-server",
    "Dell server",
    "vendors-hardware",
    createRoleIcon("DellServer", "server", dell),
    ["dell", "server", "poweredge", "idrac"],
  ),
  defineIcon(
    "supermicro-server",
    "Supermicro server",
    "vendors-hardware",
    createRoleIcon("SupermicroServer", "server", supermicro),
    ["supermicro", "super micro", "server", "bmc"],
  ),
  defineIcon(
    "cisco-access-point",
    "Cisco access point",
    "vendors-hardware",
    createRoleIcon("CiscoAccessPoint", "access-point", cisco),
    ["cisco", "cisco ap", "access point", "wireless", "wifi"],
  ),
  defineIcon(
    "tplink-access-point",
    "TP-Link access point",
    "vendors-hardware",
    createRoleIcon("TPLinkAccessPoint", "access-point", tplink),
    ["tplink", "tp-link ap", "tplink ap", "access point", "omada"],
  ),
  defineIcon(
    "asus-access-point",
    "ASUS access point",
    "vendors-hardware",
    createRoleIcon("AsusAccessPoint", "access-point", asus),
    ["asus", "asus ap", "access point", "aimesh", "wifi"],
  ),
  defineIcon(
    "hpe-switch",
    "HPE switch",
    "vendors-hardware",
    createRoleIcon("HPESwitch", "switch", hpe),
    ["hpe", "hp enterprise", "switch", "aruba", "procurve"],
  ),
  defineIcon(
    "levelone-switch",
    "LevelOne switch",
    "vendors-hardware",
    createRoleIcon("LevelOneSwitch", "switch", leveloneIdentifier),
    ["levelone", "level one", "level1", "switch"],
    "LevelOne switch with an app-authored L1 identifier; not an official brand logo.",
  ),
  defineIcon(
    "arista-switch",
    "Arista switch",
    "vendors-hardware",
    createRoleIcon("AristaSwitch", "switch", aristaIdentifier),
    ["arista", "switch", "eos", "network"],
    "Arista switch with an app-authored A/network identifier; not an official brand logo.",
  ),
  defineIcon(
    "hp-printer",
    "HP printer",
    "vendors-hardware",
    createRoleIcon("HpPrinter", "printer", hp),
    ["hp", "printer", "printers", "laserjet", "officejet"],
  ),
  defineIcon(
    "brother-printer",
    "Brother printer",
    "vendors-hardware",
    createRoleIcon("BrotherPrinter", "printer", brother),
    ["brother", "printer", "printers", "laser"],
    "Brother printer with an app-authored device identifier; not an official Brother logo.",
  ),
  defineIcon(
    "kyocera-printer",
    "Kyocera printer",
    "vendors-hardware",
    createRoleIcon("KyoceraPrinter", "printer", kyocera),
    ["kyocera", "printer", "printers", "ecosys", "taskalfa"],
  ),
  defineIcon(
    "epson-printer",
    "Epson printer",
    "vendors-hardware",
    createRoleIcon("EpsonPrinter", "printer", epson),
    ["epson", "printer", "printers", "ecotank"],
  ),
  defineIcon(
    "xerox-printer",
    "Xerox printer",
    "vendors-hardware",
    createRoleIcon("XeroxPrinter", "printer", xerox),
    ["xerox", "printer", "printers", "copier"],
  ),
  defineIcon(
    "canon-printer",
    "Canon printer",
    "vendors-hardware",
    createRoleIcon("CanonPrinter", "printer", canon),
    ["canon", "printer", "printers", "pixma", "imageclass"],
  ),
  defineIcon(
    "apple-computer",
    "Apple computer",
    "vendors-hardware",
    createRoleIcon("AppleComputer", "desktop", apple),
    ["apple", "computer", "desktop", "imac", "mac"],
  ),
  defineIcon(
    "windows-computer",
    "Windows computer",
    "vendors-hardware",
    createRoleIcon("WindowsComputer", "desktop", windows),
    ["windows", "computer", "desktop", "pc"],
  ),
  defineIcon(
    "lenovo-server",
    "Lenovo server",
    "vendors-hardware",
    createRoleIcon("LenovoServer", "server", lenovo),
    ["lenovo", "server", "thinksystem", "xclarity"],
  ),
  defineIcon(
    "lenovo-pc",
    "Lenovo PC",
    "vendors-hardware",
    createRoleIcon("LenovoPc", "desktop", lenovo),
    ["lenovo", "pc", "computer", "desktop", "thinkcentre"],
  ),
  defineIcon(
    "lenovo-laptop",
    "Lenovo laptop",
    "vendors-hardware",
    createRoleIcon("LenovoLaptop", "laptop", lenovo),
    ["lenovo", "laptop", "notebook", "thinkpad"],
  ),
  defineIcon(
    "dell-laptop",
    "Dell laptop",
    "vendors-hardware",
    createRoleIcon("DellLaptop", "laptop", dell),
    ["dell", "laptop", "notebook", "latitude", "xps"],
  ),
  defineIcon(
    "hp-laptop",
    "HP laptop",
    "vendors-hardware",
    createRoleIcon("HpLaptop", "laptop", hp),
    ["hp", "laptop", "notebook", "elitebook", "probook"],
  ),
  defineIcon(
    "macbook",
    "MacBook",
    "vendors-hardware",
    createRoleIcon("MacBook", "laptop", apple),
    ["macbook", "mac book", "apple laptop", "mac laptop", "notebook"],
  ),
  defineIcon(
    "razer-laptop",
    "Razer laptop",
    "vendors-hardware",
    createRoleIcon("RazerLaptop", "laptop", razer),
    ["razer", "laptop", "blade", "gaming"],
  ),
  defineIcon(
    "asus-laptop",
    "ASUS laptop",
    "vendors-hardware",
    createRoleIcon("AsusLaptop", "laptop", asus),
    ["asus", "laptop", "zenbook", "vivobook", "rog"],
  ),
  defineIcon(
    "clevo-laptop",
    "Clevo laptop",
    "vendors-hardware",
    createRoleIcon("ClevoLaptop", "laptop", clevo),
    ["clevo", "laptop", "notebook", "barebone"],
    "Clevo laptop with an app-authored device identifier; not an official Clevo logo.",
  ),
  defineIcon(
    "huawei-laptop",
    "Huawei laptop",
    "vendors-hardware",
    createRoleIcon("HuaweiLaptop", "laptop", huawei),
    ["huawei", "laptop", "matebook", "notebook"],
  ),
  defineIcon(
    "fujitsu-laptop",
    "Fujitsu laptop",
    "vendors-hardware",
    createRoleIcon("FujitsuLaptop", "laptop", fujitsu),
    ["fujitsu", "laptop", "lifebook", "notebook"],
  ),
  defineIcon(
    "samsung-laptop",
    "Samsung laptop",
    "vendors-hardware",
    createRoleIcon("SamsungLaptop", "laptop", samsung),
    ["samsung", "smasung", "laptop", "galaxy book", "notebook"],
  ),
  defineIcon(
    "lg-laptop",
    "LG laptop",
    "vendors-hardware",
    createRoleIcon("LgLaptop", "laptop", lg),
    ["lg", "laptop", "gram", "notebook"],
  ),
  defineIcon(
    "acer-laptop",
    "Acer laptop",
    "vendors-hardware",
    createRoleIcon("AcerLaptop", "laptop", acer),
    ["acer", "laptop", "aspire", "swift"],
  ),
  defineIcon(
    "msi-laptop",
    "MSI laptop",
    "vendors-hardware",
    createRoleIcon("MsiLaptop", "laptop", msi),
    ["msi", "laptop", "gaming", "notebook"],
  ),
  defineIcon(
    "toshiba-laptop",
    "Toshiba laptop",
    "vendors-hardware",
    createRoleIcon("ToshibaLaptop", "laptop", toshiba),
    ["toshiba", "laptop", "dynabook", "satellite"],
  ),
  defineIcon(
    "huawei-olt",
    "Huawei OLT",
    "vendors-hardware",
    createRoleIcon("HuaweiOlt", "olt", huawei),
    ["huawei", "olt", "optical line terminal", "gpon", "fiber", "fibre"],
  ),
  defineIcon(
    "huawei-access-point",
    "Huawei access point",
    "vendors-hardware",
    createRoleIcon("HuaweiAccessPoint", "access-point", huawei),
    ["huawei", "access point", "ap", "wifi", "wireless"],
  ),
  defineIcon(
    "huawei-router",
    "Huawei router",
    "vendors-hardware",
    createRoleIcon("HuaweiRouter", "router", huawei),
    ["huawei", "router", "gateway", "routing"],
  ),
  defineIcon(
    "huawei-switch",
    "Huawei switch",
    "vendors-hardware",
    createRoleIcon("HuaweiSwitch", "switch", huawei),
    ["huawei", "switch", "ethernet", "network"],
  ),
  defineIcon(
    "asus-router",
    "ASUS router",
    "vendors-hardware",
    createRoleIcon("AsusRouter", "router", asus),
    ["asus", "router", "aimesh", "rt ax", "gateway"],
  ),
  defineIcon(
    "cisco-router",
    "Cisco router",
    "vendors-hardware",
    createRoleIcon("CiscoRouter", "router", cisco),
    ["cisco", "router", "ios", "isr", "routing"],
  ),
  defineIcon(
    "ubiquiti-access-point",
    "Ubiquiti access point",
    "vendors-hardware",
    createRoleIcon("UbiquitiAccessPoint", "access-point", ubiquiti),
    ["ubiquiti", "unifi", "access point", "ap", "wifi"],
  ),
  defineIcon(
    "ubiquiti-switch",
    "Ubiquiti switch",
    "vendors-hardware",
    createRoleIcon("UbiquitiSwitch", "switch", ubiquiti),
    ["ubiquiti", "unifi", "switch", "ethernet"],
  ),
  defineIcon(
    "avaya-switch",
    "Avaya switch",
    "vendors-hardware",
    createRoleIcon("AvayaSwitch", "switch", avaya),
    ["avaya", "switch", "ethernet", "network"],
  ),
  defineIcon(
    "ilo",
    "HPE iLO",
    "vendors-hardware",
    createRoleIcon("HpeIlo", "server", hpe),
    [
      "ilo",
      "hp ilo",
      "hpe ilo",
      "integrated lights out",
      "server management",
      "bmc",
      "proliant",
    ],
  ),
  defineIcon(
    "juniper-router",
    "Juniper router",
    "vendors-hardware",
    createRoleIcon("JuniperRouter", "router", junipernetworks),
    ["juniper", "router", "junos", "mx", "routing"],
  ),
  defineIcon(
    "mikrotik-router",
    "MikroTik router",
    "vendors-hardware",
    createRoleIcon("MikrotikRouter", "router", mikrotik),
    ["mikrotik", "router", "routeros", "routerboard"],
  ),
  defineIcon(
    "qnap-nas",
    "QNAP NAS",
    "vendors-hardware",
    createRoleIcon("QnapNas", "nas", qnap),
    ["qnap", "nas", "qts", "network attached storage"],
  ),
  defineIcon(
    "lenovo-tablet",
    "Lenovo tablet",
    "vendors-hardware",
    createRoleIcon("LenovoTablet", "tablet", lenovo),
    ["lenovo", "tablet", "tablets", "tab", "yoga"],
  ),
  defineIcon(
    "samsung-tablet",
    "Samsung tablet",
    "vendors-hardware",
    createRoleIcon("SamsungTablet", "tablet", samsung),
    ["samsung", "smasung", "tablet", "tablets", "galaxy tab"],
  ),
  defineIcon(
    "apple-tablet",
    "Apple tablet",
    "vendors-hardware",
    createRoleIcon("AppleTablet", "tablet", apple),
    ["apple", "tablet", "tablets", "ipad", "ipad pro"],
  ),
  defineIcon(
    "ugreen-nas",
    "UGREEN NAS",
    "vendors-hardware",
    createRoleIcon("UgreenNas", "nas", ugreen),
    ["ugreen", "nas", "nasync", "network attached storage"],
  ),
  defineIcon(
    "schneider-electric-ups",
    "Schneider Electric UPS",
    "vendors-hardware",
    createRoleIcon("SchneiderElectricUps", "ups", schneiderelectric),
    [
      "schneider electric",
      "chneider eletric",
      "ups",
      "uninterruptible power supply",
      "battery backup",
    ],
  ),
  defineIcon(
    "vertiv-ups",
    "Vertiv UPS",
    "vendors-hardware",
    createRoleIcon("VertivUps", "ups", vertiv),
    [
      "vertiv",
      "liebert",
      "ups",
      "uninterruptible power supply",
      "battery backup",
    ],
  ),
  defineIcon(
    "riello-ups",
    "Riello UPS",
    "vendors-hardware",
    createRoleIcon("RielloUps", "ups", riello),
    ["riello", "ups", "uninterruptible power supply", "battery backup"],
  ),
  defineIcon(
    "apc-ups",
    "APC UPS",
    "vendors-hardware",
    createRoleIcon("ApcUps", "ups", apc),
    [
      "apc",
      "ups",
      "smart ups",
      "back ups",
      "battery backup",
      "uninterruptible power supply",
    ],
    "APC UPS with an app-authored device identifier; not an official APC logo.",
  ),
  defineIcon(
    "eaton-ups",
    "Eaton UPS",
    "vendors-hardware",
    createRoleIcon("EatonUps", "ups", eaton),
    [
      "eaton",
      "ups",
      "powerware",
      "battery backup",
      "uninterruptible power supply",
    ],
    "Eaton UPS with an app-authored device identifier; not an official Eaton logo.",
  ),
  defineIcon(
    "cyberpower-ups",
    "CyberPower UPS",
    "vendors-hardware",
    createRoleIcon("CyberPowerUps", "ups", cyberpower),
    [
      "cyberpower",
      "cyber power",
      "ups",
      "battery backup",
      "uninterruptible power supply",
    ],
    "CyberPower UPS with an app-authored device identifier; not an official CyberPower logo.",
  ),
  defineIcon(
    "tripplite-ups",
    "Tripp Lite UPS",
    "vendors-hardware",
    createRoleIcon("TrippLiteUps", "ups", tripplite),
    [
      "tripplite",
      "tripp lite",
      "ups",
      "battery backup",
      "uninterruptible power supply",
    ],
    "Tripp Lite UPS with an app-authored device identifier; not an official Tripp Lite logo.",
  ),
  defineIcon(
    "supermicro-bmc",
    "Supermicro BMC",
    "vendors-hardware",
    createRoleIcon("SupermicroBmc", "management-server", supermicro),
    [
      "supermicro bmc",
      "supermicro",
      "bmc",
      "ipmi",
      "baseboard management controller",
      "out of band",
    ],
  ),
  defineIcon(
    "dell-idrac",
    "Dell iDRAC",
    "vendors-hardware",
    createRoleIcon("DellIdrac", "management-server", dell),
    [
      "dell idrac",
      "idrac",
      "dell",
      "integrated dell remote access controller",
      "bmc",
      "server management",
    ],
  ),
  defineIcon(
    "lenovo-xclarity",
    "Lenovo XClarity",
    "vendors-hardware",
    createRoleIcon("LenovoXClarity", "management-server", lenovo),
    [
      "lenovo xclarity",
      "xclarity",
      "x clarity",
      "lenovo",
      "bmc",
      "server management",
    ],
  ),
  defineIcon(
    "truenas-nas",
    "TrueNAS NAS",
    "vendors-hardware",
    createRoleIcon("TrueNasStorage", "nas", truenas),
    ["truenas", "true nas", "nas", "freenas", "network attached storage"],
  ),
  defineIcon(
    "draytek-switch",
    "DrayTek switch",
    "vendors-hardware",
    createRoleIcon("DrayTekSwitch", "switch", draytek),
    ["draytek", "drautek", "switch", "vigor switch", "vigorswitch", "ethernet"],
    "DrayTek switch with an app-authored device identifier; not an official DrayTek logo.",
  ),
  defineIcon(
    "draytek-router",
    "DrayTek router",
    "vendors-hardware",
    createRoleIcon("DrayTekRouter", "router", draytek),
    ["draytek", "drautek", "router", "vigor", "gateway", "routing"],
    "DrayTek router with an app-authored device identifier; not an official DrayTek logo.",
  ),
  defineIcon(
    "intel-amt",
    "Intel AMT",
    "vendors-hardware",
    createRoleIcon("IntelAmt", "management-server", intel),
    [
      "intel amt",
      "amt",
      "active management technology",
      "intel",
      "vpro",
      "out of band",
      "remote management",
    ],
    "Intel AMT with a management-controller silhouette and the Intel brand mark, not a separate AMT product logo.",
  ),
  defineIcon(
    "mikrotik-access-point",
    "MikroTik access point",
    "vendors-hardware",
    createRoleIcon("MikroTikAccessPoint", "access-point", mikrotik),
    ["mikrotik", "access point", "ap", "wifi", "wireless", "capsman", "cap"],
  ),
  defineIcon(
    "mikrotik-switch",
    "MikroTik switch",
    "vendors-hardware",
    createRoleIcon("MikroTikSwitch", "switch", mikrotik),
    ["mikrotik", "switch", "ethernet", "routeros", "swos", "crs"],
  ),
  defineIcon(
    "access-point-ceiling",
    "Ceiling access point",
    "vendors-hardware",
    CeilingAccessPoint,
    [
      "ceiling access point",
      "access point ceiling",
      "ceiling ap",
      "wifi",
      "wireless",
      "access point variant",
    ],
  ),
  defineIcon(
    "access-point-wall",
    "Wall access point",
    "vendors-hardware",
    WallAccessPoint,
    [
      "wall access point",
      "access point wall",
      "wall ap",
      "in wall",
      "wifi",
      "access point variant",
    ],
  ),
  defineIcon(
    "switch-managed",
    "Managed switch",
    "vendors-hardware",
    createRoleIcon("ManagedSwitch", "switch", Settings),
    [
      "managed switch",
      "switch managed",
      "management",
      "ethernet",
      "switch variant",
    ],
  ),
  defineIcon(
    "switch-poe",
    "PoE switch",
    "vendors-hardware",
    createRoleIcon("PoeSwitch", "switch", Zap),
    [
      "poe switch",
      "switch poe",
      "power over ethernet",
      "ethernet",
      "switch variant",
    ],
  ),
  defineIcon(
    "switch-fiber",
    "Fiber switch",
    "vendors-hardware",
    createRoleIcon("FiberSwitch", "switch", Cable),
    [
      "fiber switch",
      "fibre switch",
      "switch fiber",
      "switch fibre",
      "sfp",
      "optical",
      "switch variant",
    ],
  ),
  defineIcon(
    "reolink-camera",
    "Reolink camera",
    "vendors-hardware",
    createRoleIcon("ReolinkCamera", "camera", reolink),
    ["reolink camera", "reolink", "ip camera", "security", "surveillance"],
    "Reolink camera silhouette with the publisher's R symbol.",
  ),
  defineIcon(
    "hikvision-camera",
    "Hikvision camera",
    "vendors-hardware",
    createRoleIcon("HikvisionCamera", "camera", hikvision),
    ["hikvision camera", "hikvision", "ip camera", "security"],
    "Hikvision camera with an app-authored identifier; not an official Hikvision logo.",
  ),
  defineIcon(
    "dahua-camera",
    "Dahua camera",
    "vendors-hardware",
    createRoleIcon("DahuaCamera", "camera", dahua),
    ["dahua camera", "dahua", "ip camera", "security"],
    "Dahua camera with an app-authored identifier; not an official Dahua logo.",
  ),
  defineIcon(
    "axis-camera",
    "Axis camera",
    "vendors-hardware",
    createRoleIcon("AxisCamera", "camera", axis),
    ["axis camera", "axis communications", "ip camera", "security"],
    "Axis camera silhouette with a monochrome adaptation of the publisher's logo geometry.",
  ),
  defineIcon(
    "hanwha-camera",
    "Hanwha Vision camera",
    "vendors-hardware",
    createRoleIcon("HanwhaCamera", "camera", hanwha),
    ["hanwha camera", "hanwha vision", "wisenet", "ip camera"],
    "Hanwha Vision camera with an app-authored identifier; not an official Hanwha Vision logo.",
  ),
  defineIcon(
    "uniview-camera",
    "Uniview camera",
    "vendors-hardware",
    createRoleIcon("UniviewCamera", "camera", uniview),
    ["uniview camera", "uniview", "unv", "ip camera"],
  ),
  defineIcon(
    "amcrest-camera",
    "Amcrest camera",
    "vendors-hardware",
    createRoleIcon("AmcrestCamera", "camera", amcrest),
    ["amcrest camera", "amcrest", "ip camera", "security"],
    "Amcrest camera with an app-authored identifier; not an official Amcrest logo.",
  ),
  defineIcon(
    "tplink-camera",
    "TP-Link camera",
    "vendors-hardware",
    createRoleIcon("TpLinkCamera", "camera", tplink),
    [
      "tplink camera",
      "tp-link camera",
      "tp link camera",
      "vigi",
      "tapo",
      "ip camera",
    ],
    "TP-Link camera using the parent-brand mark, not a separate VIGI or Tapo product logo.",
  ),
  defineIcon(
    "ubiquiti-camera",
    "Ubiquiti camera",
    "vendors-hardware",
    createRoleIcon("UbiquitiCamera", "camera", ubiquiti),
    ["ubiquiti camera", "unifi protect", "protect", "ip camera"],
    "Ubiquiti camera using the parent-brand mark, not a separate UniFi Protect product logo.",
  ),
  defineIcon(
    "reolink-nvr",
    "Reolink NVR",
    "vendors-hardware",
    createRoleIcon("ReolinkNvr", "recorder", reolink),
    ["reolink nvr", "reolink", "network video recorder", "ip recorder"],
    "Reolink network recorder silhouette with the publisher's R symbol.",
  ),
  defineIcon(
    "hikvision-dvr",
    "Hikvision DVR",
    "vendors-hardware",
    createRoleIcon("HikvisionDvr", "recorder", hikvision),
    ["hikvision dvr", "hikvision", "digital video recorder", "recorder"],
    "Hikvision DVR with an app-authored identifier; not an official Hikvision logo.",
  ),
  defineIcon(
    "dahua-dvr",
    "Dahua DVR",
    "vendors-hardware",
    createRoleIcon("DahuaDvr", "recorder", dahua),
    ["dahua dvr", "dahua", "digital video recorder", "recorder"],
    "Dahua DVR with an app-authored identifier; not an official Dahua logo.",
  ),
] as const;
