import {
  dell,
  hp,
  supermicro,
  hpe,
  synology,
  tplink,
  dlinkIdentifier,
  cisco,
  asus,
  leveloneIdentifier,
  aristaIdentifier,
  microsoft,
  netapp,
  apple,
  lenovo,
  brother,
  kyocera,
  xerox,
  epson,
  canon,
  huawei,
  samsung,
  razer,
  clevo,
  fujitsu,
  lg,
  ubiquiti,
  avaya,
  acer,
  msi,
  toshiba,
  junipernetworks,
  mikrotik,
  qnap,
  asustor,
  arduino,
  raspberrypi,
  espressif,
  shelly,
  ugreen,
  schneiderelectric,
  vertiv,
  riello,
  apc,
  eaton,
  cyberpower,
  tripplite,
  sonoff,
  tuya,
  truenas,
  draytek,
  microsoftexchangemodern as exchange,
  intel,
  bind,
  reolink,
  hikvision,
  dahua,
  axis,
  hanwha,
  uniview,
  amcrest,
} from "../brand";
import { defineIcon } from "./types";

/** Pure vendor and brand choices; appliance silhouettes remain in hardware. */
export const VENDOR_ICONS = [
  defineIcon("dell", "Dell", "vendors", dell, [
    "dell",
    "idrac",
    "server",
    "hardware",
  ]),
  defineIcon("hp", "HP", "vendors", hp, [
    "hp",
    "hewlett packard",
    "printer",
    "computer",
  ]),
  defineIcon("supermicro", "Supermicro", "vendors", supermicro, [
    "supermicro",
    "bmc",
    "server",
    "hardware",
  ]),
  defineIcon("hpe", "HPE", "vendors", hpe, [
    "hpe",
    "hewlett packard enterprise",
    "ilo",
    "aruba",
  ]),
  defineIcon("synology", "Synology", "vendors", synology, [
    "synology",
    "dsm",
    "diskstation",
    "storage",
  ]),
  defineIcon("tplink", "TP-Link", "vendors", tplink, [
    "tplink",
    "tp link",
    "tp-link",
    "omada",
  ]),
  defineIcon(
    "dlink",
    "D-Link",
    "vendors",
    dlinkIdentifier,
    ["dlink", "d link", "d-link", "network"],
    "D-Link connection icon: app-authored DL identifier, not an official brand logo.",
  ),
  defineIcon("cisco", "Cisco", "vendors", cisco, [
    "cisco",
    "ios",
    "network",
    "meraki",
  ]),
  defineIcon("asus", "ASUS", "vendors", asus, [
    "asus",
    "aimesh",
    "network",
    "hardware",
  ]),
  defineIcon(
    "levelone",
    "LevelOne",
    "vendors",
    leveloneIdentifier,
    ["levelone", "level one", "level1", "network"],
    "LevelOne connection icon: app-authored L1 identifier, not an official brand logo.",
  ),
  defineIcon(
    "arista",
    "Arista",
    "vendors",
    aristaIdentifier,
    ["arista", "arista networks", "eos", "network"],
    "Arista connection icon: app-authored A/network identifier, not an official brand logo.",
  ),
  defineIcon("microsoft", "Microsoft", "vendors", microsoft, [
    "microsoft",
    "microsoft generic",
    "ms",
    "software",
    "windows",
  ]),
  defineIcon("netapp", "NetApp", "vendors", netapp, [
    "netapp",
    "net app",
    "ontap",
    "storage",
    "san",
  ]),
  defineIcon("apple", "Apple", "vendors", apple, [
    "apple",
    "mac",
    "macbook",
    "imac",
  ]),
  defineIcon("lenovo", "Lenovo", "vendors", lenovo, [
    "lenovo",
    "thinkpad",
    "thinkcentre",
    "thinksystem",
  ]),
  defineIcon(
    "brother",
    "Brother",
    "vendors",
    brother,
    ["brother", "printer", "printers", "scanner"],
    "Brother's leading lowercase b, locally traced from the publisher wordmark for compact display.",
  ),
  defineIcon("kyocera", "Kyocera", "vendors", kyocera, [
    "kyocera",
    "printer",
    "printers",
    "ecosys",
    "taskalfa",
  ]),
  defineIcon("xerox", "Xerox", "vendors", xerox, [
    "xerox",
    "printer",
    "printers",
    "copier",
  ]),
  defineIcon("epson", "Epson", "vendors", epson, [
    "epson",
    "printer",
    "printers",
    "ecotank",
  ]),
  defineIcon("canon", "Canon", "vendors", canon, [
    "canon",
    "printer",
    "printers",
    "pixma",
    "imageclass",
  ]),
  defineIcon("huawei", "Huawei", "vendors", huawei, [
    "huawei",
    "network",
    "hardware",
  ]),
  defineIcon("samsung", "Samsung", "vendors", samsung, [
    "samsung",
    "smasung",
    "galaxy",
    "hardware",
  ]),
  defineIcon("razer", "Razer", "vendors", razer, [
    "razer",
    "blade",
    "gaming",
    "laptop",
  ]),
  defineIcon(
    "clevo",
    "Clevo",
    "vendors",
    clevo,
    ["clevo", "laptop", "notebook", "barebone"],
    "Clevo device identifier authored by the app; not an official Clevo logo.",
  ),
  defineIcon("fujitsu", "Fujitsu", "vendors", fujitsu, [
    "fujitsu",
    "lifebook",
    "primergy",
    "hardware",
  ]),
  defineIcon("lg", "LG", "vendors", lg, [
    "lg",
    "lg electronics",
    "gram",
    "hardware",
  ]),
  defineIcon("ubiquiti", "Ubiquiti", "vendors", ubiquiti, [
    "ubiquiti",
    "unifi",
    "ui",
    "network",
  ]),
  defineIcon("avaya", "Avaya", "vendors", avaya, [
    "avaya",
    "switch",
    "telephony",
    "network",
  ]),
  defineIcon("acer", "Acer", "vendors", acer, [
    "acer",
    "aspire",
    "swift",
    "travelmate",
  ]),
  defineIcon("msi", "MSI", "vendors", msi, [
    "msi",
    "micro star",
    "gaming",
    "laptop",
  ]),
  defineIcon("toshiba", "Toshiba", "vendors", toshiba, [
    "toshiba",
    "dynabook",
    "satellite",
    "laptop",
  ]),
  defineIcon("juniper", "Juniper", "vendors", junipernetworks, [
    "juniper",
    "juniper networks",
    "junos",
    "network",
  ]),
  defineIcon("mikrotik", "MikroTik", "vendors", mikrotik, [
    "mikrotik",
    "routeros",
    "routerboard",
    "network",
  ]),
  defineIcon("qnap", "QNAP", "vendors", qnap, [
    "qnap",
    "nas",
    "qts",
    "storage",
  ]),
  defineIcon("asustor", "ASUSTOR", "vendors", asustor, [
    "asustor",
    "nas",
    "storage",
    "adm",
    "network attached storage",
  ]),
  defineIcon("arduino", "Arduino", "vendors", arduino, [
    "arduino",
    "iot",
    "microcontroller",
    "development board",
    "uno",
    "maker",
  ]),
  defineIcon("raspberry-pi", "Raspberry Pi", "vendors", raspberrypi, [
    "raspberry pi",
    "raspberrypi",
    "raspbery pi",
    "rpi",
    "sbc",
    "single board computer",
    "iot",
  ]),
  defineIcon("espressif", "Espressif", "vendors", espressif, [
    "espressif",
    "esp32",
    "esp8266",
    "iot",
    "microcontroller",
    "wifi",
  ]),
  defineIcon("shelly", "Shelly", "vendors", shelly, [
    "shelly",
    "iot",
    "smart relay",
    "home automation",
    "energy monitor",
  ]),
  defineIcon("ugreen", "UGREEN", "vendors", ugreen, [
    "ugreen",
    "nas",
    "storage",
    "nasync",
    "hardware",
  ]),
  defineIcon(
    "schneider-electric",
    "Schneider Electric",
    "vendors",
    schneiderelectric,
    [
      "schneider electric",
      "schneiderelectric",
      "chneider eletric",
      "power",
      "ups",
      "industrial automation",
    ],
  ),
  defineIcon("vertiv", "Vertiv", "vendors", vertiv, [
    "vertiv",
    "liebert",
    "ups",
    "power",
    "datacenter",
  ]),
  defineIcon("riello", "Riello", "vendors", riello, [
    "riello",
    "ups",
    "power",
    "battery backup",
  ]),
  defineIcon(
    "apc",
    "APC",
    "vendors",
    apc,
    ["apc", "american power conversion", "schneider electric", "ups", "power"],
    "APC device identifier authored by the app; not an official APC logo.",
  ),
  defineIcon(
    "eaton",
    "Eaton",
    "vendors",
    eaton,
    ["eaton", "ups", "power", "powerware"],
    "Eaton device identifier authored by the app; not an official Eaton logo.",
  ),
  defineIcon(
    "cyberpower",
    "CyberPower",
    "vendors",
    cyberpower,
    ["cyberpower", "cyber power", "ups", "power", "battery backup"],
    "CyberPower device identifier authored by the app; not an official CyberPower logo.",
  ),
  defineIcon(
    "tripplite",
    "Tripp Lite",
    "vendors",
    tripplite,
    ["tripplite", "tripp lite", "eaton", "ups", "power"],
    "Tripp Lite device identifier authored by the app; not an official Tripp Lite logo.",
  ),
  defineIcon(
    "sonoff",
    "SONOFF",
    "vendors",
    sonoff,
    [
      "sonoff",
      "iot",
      "smart switch",
      "smart relay",
      "ewelink",
      "home automation",
    ],
    "SONOFF device identifier authored by the app; not an official SONOFF logo.",
  ),
  defineIcon(
    "tuya",
    "Tuya",
    "vendors",
    tuya,
    ["tuya", "iot", "smart life", "smart home", "home automation"],
    "Tuya device identifier authored by the app; not an official Tuya logo.",
  ),
  defineIcon("truenas", "TrueNAS", "vendors", truenas, [
    "truenas",
    "true nas",
    "freenas",
    "ixsystems",
    "storage",
    "nas",
  ]),
  defineIcon(
    "draytek",
    "DrayTek",
    "vendors",
    draytek,
    ["draytek", "dray tek", "drautek", "vigor", "network", "hardware"],
    "DrayTek italic wordmark locally hand-traced from the publisher artwork for monochrome display.",
  ),
  defineIcon(
    "exchange",
    "Microsoft Exchange",
    "vendors",
    exchange,
    ["exchange", "microsoft exchange", "mail", "email", "plain"],
    "Microsoft Exchange connection icon using the pinned Microsoft Exchange product mark.",
  ),
  defineIcon("intel", "Intel", "vendors", intel, [
    "intel",
    "processor",
    "amt",
    "vpro",
    "hardware",
    "plain",
  ]),
  defineIcon(
    "bind",
    "BIND",
    "vendors",
    bind,
    ["bind", "bind9", "dns", "isc", "named", "plain"],
    "BIND DNS identifier authored by the app; not an official ISC logo.",
  ),
  defineIcon(
    "reolink",
    "Reolink",
    "vendors",
    reolink,
    ["reolink", "camera", "security", "surveillance"],
    "Reolink connection icon using the publisher's R symbol.",
  ),
  defineIcon(
    "hikvision",
    "Hikvision",
    "vendors",
    hikvision,
    ["hikvision", "hik vision", "camera", "security", "surveillance"],
    "Hikvision identifier authored by the app; not an official Hikvision logo.",
  ),
  defineIcon(
    "dahua",
    "Dahua",
    "vendors",
    dahua,
    ["dahua", "dahua technology", "camera", "security", "surveillance"],
    "Dahua's compact loop and letterform emblem, locally traced from publisher raster artwork.",
  ),
  defineIcon(
    "axis",
    "Axis",
    "vendors",
    axis,
    ["axis", "axis communications", "camera", "security", "surveillance"],
    "Axis connection icon using a monochrome adaptation of the publisher's logo geometry.",
  ),
  defineIcon(
    "hanwha",
    "Hanwha Vision",
    "vendors",
    hanwha,
    ["hanwha", "hanwha vision", "wisenet", "camera", "surveillance"],
    "Hanwha Vision's three-ring publisher SVG emblem, uniformly scaled in the selected icon color.",
  ),
  defineIcon("uniview", "Uniview", "vendors", uniview, [
    "uniview",
    "unv",
    "camera",
    "security",
    "surveillance",
  ]),
  defineIcon(
    "amcrest",
    "Amcrest",
    "vendors",
    amcrest,
    ["amcrest", "camera", "security", "surveillance"],
    "Amcrest's compact hexagon and lens emblem, locally traced from publisher raster artwork.",
  ),
] as const;
