import {
  Monitor,
  Terminal,
  Globe,
  Shield,
  Wifi,
  Palette,
  LayoutGrid,
  Power,
  Zap,
  Server,
  Code,
  MousePointerClick,
  Archive,
  CloudCog,
  Fingerprint,
  MonitorDot,
  Cpu,
  Circle,
  ListVideo,
  RotateCcw,
  LucideIcon,
} from "lucide-react";
import { GlobalSettings, defaultSSHTerminalConfig } from "../../types/settings";

/* ═══════════════════════════════════════════════════════════════
   Tab definition
   ═══════════════════════════════════════════════════════════════ */

export interface SettingsTab {
  id: string;
  labelKey: string;     // i18n key or literal
  fallback?: string;    // fallback if labelKey isn't a valid key
  icon: LucideIcon;
}

/** Ordered list of sidebar tabs. `labelKey` is used with `t()`;
 *  if it doesn't resolve, `fallback` (or the raw key) is shown. */
export const SETTINGS_TABS: SettingsTab[] = [
  { id: "general", labelKey: "settings.general", icon: Monitor },
  { id: "behavior", labelKey: "Behavior", icon: MousePointerClick },
  { id: "startup", labelKey: "settings.startup.title", fallback: "Startup & Tray", icon: Power },
  { id: "theme", labelKey: "settings.theme", icon: Palette },
  { id: "layout", labelKey: "Layout", icon: LayoutGrid },
  { id: "security", labelKey: "settings.security", icon: Shield },
  { id: "trust", labelKey: "Trust Center", icon: Fingerprint },
  { id: "performance", labelKey: "settings.performance", icon: Zap },
  { id: "rdpDefaults", labelKey: "RDP", icon: MonitorDot },
  { id: "backup", labelKey: "Backup", icon: Archive },
  { id: "cloudSync", labelKey: "Cloud Sync", icon: CloudCog },
  { id: "proxy", labelKey: "Proxy", icon: Wifi },
  { id: "sshTerminal", labelKey: "settings.sshTerminal.tab", fallback: "SSH Terminal", icon: Terminal },
  { id: "recording", labelKey: "Recording", icon: Circle },
  { id: "macros", labelKey: "Macros", icon: ListVideo },
  { id: "webBrowser", labelKey: "Web Browser", icon: Globe },
  { id: "backend", labelKey: "Backend", icon: Cpu },
  { id: "api", labelKey: "API Server", icon: Server },
  { id: "advanced", labelKey: "settings.advanced", icon: Code },
  { id: "recovery", labelKey: "Recovery", icon: RotateCcw },
];

/* ═══════════════════════════════════════════════════════════════
   Per-tab resettable keys
   ═══════════════════════════════════════════════════════════════ */

export const TAB_DEFAULTS: Record<string, (keyof GlobalSettings)[]> = {
  general: [
    "language",
    "autoSaveEnabled",
    "autoSaveIntervalMinutes",
    "warnOnClose",
    "warnOnExit",
    "warnOnDetachClose",
    "quickConnectHistoryEnabled",
  ],
  behavior: [
    "singleClickConnect",
    "singleClickDisconnect",
    "doubleClickRename",
    "doubleClickConnect",
    "middleClickCloseTab",
    "singleWindowMode",
    "singleConnectionMode",
    "reconnectOnReload",
    "enableAutocomplete",
    "openConnectionInBackground",
    "switchTabOnActivity",
    "closeTabOnDisconnect",
    "confirmCloseActiveTab",
    "enableRecentlyClosedTabs",
    "recentlyClosedTabsMax",
    "focusTerminalOnTabSwitch",
    "scrollTreeToActiveConnection",
    "restoreLastActiveTab",
    "tabCycleMru",
    "copyOnSelect",
    "pasteOnRightClick",
    "clearClipboardAfterSeconds",
    "trimPastedWhitespace",
    "warnOnMultiLinePaste",
    "maxPasteLengthChars",
    "idleDisconnectMinutes",
    "sendKeepaliveOnIdle",
    "keepaliveIntervalSeconds",
    "dimInactiveTabs",
    "showIdleDuration",
    "autoReconnectOnDisconnect",
    "autoReconnectMaxAttempts",
    "autoReconnectDelaySecs",
    "notifyOnReconnect",
    "notifyOnConnect",
    "notifyOnDisconnect",
    "notifyOnError",
    "notificationSound",
    "flashTaskbarOnActivity",
    "confirmDisconnect",
    "confirmDeleteConnection",
    "confirmBulkOperations",
    "confirmImport",
    "enableFileDragDropToTerminal",
    "dragSensitivityPx",
    "showDropPreview",
    "terminalScrollSpeed",
    "terminalSmoothScroll",
    "treeRightClickAction",
    "mouseBackAction",
    "mouseForwardAction",
    "toolDisplayModes",
  ],
  startup: [
    "startMinimized",
    "startMaximized",
    "startWithSystem",
    "reconnectPreviousSessions",
    "autoOpenLastCollection",
    "lastOpenedCollectionId",
    "minimizeToTray",
    "closeToTray",
    "showTrayIcon",
    "hideQuickStartMessage",
    "hideQuickStartButtons",
    "welcomeScreenTitle",
    "welcomeScreenMessage",
  ],
  theme: [
    "theme",
    "colorScheme",
    "primaryAccentColor",
    "backgroundGlowEnabled",
    "backgroundGlowColor",
    "backgroundGlowOpacity",
    "backgroundGlowRadius",
    "backgroundGlowBlur",
    "windowTransparencyEnabled",
    "windowTransparencyOpacity",
    "showTransparencyToggle",
    "customCss",
    "animationsEnabled",
    "animationDuration",
    "reduceMotion",
  ],
  layout: [
    "persistWindowSize",
    "persistWindowPosition",
    "persistSidebarWidth",
    "persistSidebarPosition",
    "persistSidebarCollapsed",
    "enableTabReorder",
    "enableConnectionReorder",
    "showQuickConnectIcon",
    "showCollectionSwitcherIcon",
    "showImportExportIcon",
    "showSettingsIcon",
    "showProxyMenuIcon",
    "showInternalProxyIcon",
    "showShortcutManagerIcon",
    "showPerformanceMonitorIcon",
    "showActionLogIcon",
    "showDevtoolsIcon",
    "showSecurityIcon",
    "showWolIcon",
    "showBulkSSHIcon",
    "showScriptManagerIcon",
    "showMacroManagerIcon",
    "showRdpSessionsIcon",
    "showErrorLogBar",
  ],
  security: [
    "encryptionAlgorithm",
    "blockCipherMode",
    "keyDerivationIterations",
    "autoBenchmarkIterations",
    "benchmarkTimeSeconds",
    "totpEnabled",
    "totpIssuer",
    "totpDigits",
    "totpPeriod",
    "totpAlgorithm",
  ],
  trust: [
    "tlsTrustPolicy",
    "sshTrustPolicy",
    "showTrustIdentityInfo",
    "certExpiryWarningDays",
  ],
  performance: [
    "maxConcurrentConnections",
    "connectionTimeout",
    "retryAttempts",
    "retryDelay",
    "enablePerformanceTracking",
    "performancePollIntervalMs",
    "performanceLatencyTarget",
  ],
  rdpDefaults: ["rdpDefaults"],
  backup: ["backup"],
  cloudSync: ["cloudSync"],
  proxy: ["globalProxy"],
  advanced: [
    "tabGrouping",
    "hostnameOverride",
    "defaultTabLayout",
    "enableTabDetachment",
    "enableTabResize",
    "enableZoom",
    "enableStatusChecking",
    "statusCheckInterval",
    "statusCheckMethod",
    "networkDiscovery",
    "restApi",
    "wolEnabled",
    "wolPort",
    "wolBroadcastAddress",
    "enableActionLog",
    "logLevel",
    "maxLogEntries",
    "exportEncryption",
    "settingsDialog",
  ],
  recording: [
    "recording",
    "rdpRecording",
    "webRecording",
    "showRecordingManagerIcon",
  ],
  macros: ["macros"],
  backend: ["backendConfig"],
  sshTerminal: ["sshTerminal"],
  webBrowser: [
    "proxyKeepaliveEnabled",
    "proxyKeepaliveIntervalSeconds",
    "proxyAutoRestart",
    "proxyMaxAutoRestarts",
    "confirmDeleteAllBookmarks",
  ],
};

/* ═══════════════════════════════════════════════════════════════
   Default values (mirrors settingsManager.ts)
   ═══════════════════════════════════════════════════════════════ */

export const DEFAULT_VALUES: Partial<GlobalSettings> = {
  language: "en",
  theme: "dark",
  colorScheme: "blue",
  primaryAccentColor: "#3b82f6",
  autoSaveEnabled: false,
  autoSaveIntervalMinutes: 5,
  singleWindowMode: false,
  singleConnectionMode: false,
  reconnectOnReload: true,
  warnOnClose: true,
  warnOnExit: true,
  warnOnDetachClose: true,
  quickConnectHistoryEnabled: true,
  startMinimized: false,
  startMaximized: false,
  startWithSystem: false,
  reconnectPreviousSessions: false,
  autoOpenLastCollection: true,
  lastOpenedCollectionId: undefined,
  minimizeToTray: false,
  closeToTray: false,
  showTrayIcon: true,
  singleClickConnect: false,
  singleClickDisconnect: false,
  doubleClickRename: false,
  animationsEnabled: true,
  animationDuration: 550,
  reduceMotion: false,
  backgroundGlowEnabled: true,
  backgroundGlowColor: "#2563eb",
  backgroundGlowOpacity: 0.25,
  backgroundGlowRadius: 520,
  backgroundGlowBlur: 140,
  windowTransparencyEnabled: false,
  windowTransparencyOpacity: 0.94,
  showTransparencyToggle: false,
  showQuickConnectIcon: true,
  showCollectionSwitcherIcon: true,
  showImportExportIcon: true,
  showSettingsIcon: true,
  showPerformanceMonitorIcon: true,
  showActionLogIcon: true,
  showDevtoolsIcon: true,
  showSecurityIcon: true,
  showProxyMenuIcon: true,
  showInternalProxyIcon: true,
  showShortcutManagerIcon: true,
  showWolIcon: true,
  maxConcurrentConnections: 10,
  connectionTimeout: 30,
  retryAttempts: 3,
  retryDelay: 5000,
  enablePerformanceTracking: true,
  performancePollIntervalMs: 20000,
  performanceLatencyTarget: "1.1.1.1",
  encryptionAlgorithm: "AES-256-GCM",
  blockCipherMode: "GCM",
  keyDerivationIterations: 100000,
  autoBenchmarkIterations: false,
  benchmarkTimeSeconds: 1,
  totpEnabled: false,
  totpIssuer: "sortOfRemoteNG",
  totpDigits: 6,
  totpPeriod: 30,
  totpAlgorithm: "sha1" as const,
  tabGrouping: "none",
  hostnameOverride: false,
  defaultTabLayout: "tabs",
  enableTabDetachment: false,
  enableTabResize: true,
  enableZoom: true,
  enableTabReorder: true,
  enableConnectionReorder: true,
  enableStatusChecking: true,
  statusCheckInterval: 30,
  statusCheckMethod: "socket",
  persistWindowSize: true,
  persistWindowPosition: true,
  persistSidebarWidth: true,
  persistSidebarPosition: true,
  persistSidebarCollapsed: true,
  wolEnabled: false,
  wolPort: 9,
  wolBroadcastAddress: "255.255.255.255",
  enableActionLog: true,
  logLevel: "info",
  maxLogEntries: 1000,
  exportEncryption: false,
  globalProxy: {
    type: "http",
    host: "",
    port: 8080,
    enabled: false,
  },
  sshTerminal: defaultSSHTerminalConfig,
  settingsDialog: {
    showSaveButton: false,
    confirmBeforeReset: true,
    autoSave: true,
  },
};
