use crate::error::PortKnockError;
use crate::types::{
    FirewallBackend, FwknopAccessStanza, FwknopClientConfig, FwknopServerConfig, HmacAlgorithm,
    KnockEncryption, KnockProtocol,
};

/// fwknop (FireWall KNock OPerator) protocol support.
pub struct FwknopManager;

impl Default for FwknopManager {
    fn default() -> Self {
        Self::new()
    }
}

impl FwknopManager {
    pub fn new() -> Self {
        Self
    }

    /// Parses fwknop access.conf content.
    /// Stanzas are separated by blank lines. Each stanza has KEY  VALUE lines.
    pub fn parse_access_conf(content: &str) -> Result<Vec<FwknopAccessStanza>, PortKnockError> {
        let mut stanzas = Vec::new();
        let mut current: std::collections::HashMap<String, String> =
            std::collections::HashMap::new();

        for line in content.lines() {
            let trimmed = line.trim();

            // Skip comments
            if trimmed.starts_with('#') || trimmed.starts_with(';') {
                continue;
            }

            // Blank line = stanza separator
            if trimmed.is_empty() {
                if !current.is_empty() {
                    stanzas.push(build_access_stanza(&current)?);
                    current.clear();
                }
                continue;
            }

            // Parse KEY  VALUE (whitespace separated, or KEY: VALUE, or KEY = VALUE)
            let (key, value) = parse_kv_line(trimmed).ok_or_else(|| {
                PortKnockError::FwknopError(format!("Invalid line in access.conf: {}", trimmed))
            })?;
            current.insert(key.to_uppercase(), value);
        }

        // Don't forget last stanza
        if !current.is_empty() {
            stanzas.push(build_access_stanza(&current)?);
        }

        Ok(stanzas)
    }

    /// Generates access.conf content from stanzas.
    pub fn generate_access_conf(stanzas: &[FwknopAccessStanza]) -> String {
        let mut out = String::new();
        out.push_str("# fwknop access.conf - generated by sorng-port-knock\n\n");

        for (i, stanza) in stanzas.iter().enumerate() {
            if i > 0 {
                out.push('\n');
            }

            out.push_str(&format!("SOURCE                      {}\n", stanza.source));
            out.push_str(&format!(
                "OPEN_PORTS                  {}\n",
                stanza.open_ports.join(", ")
            ));

            if let Some(ref restrict) = stanza.restrict_ports {
                out.push_str(&format!(
                    "RESTRICT_PORTS              {}\n",
                    restrict.join(", ")
                ));
            }

            if let Some(ref key) = stanza.key {
                out.push_str(&format!("KEY                         {}\n", key));
            }
            if let Some(ref key_b64) = stanza.key_base64 {
                out.push_str(&format!("KEY_BASE64                  {}\n", key_b64));
            }
            if let Some(ref hmac_key) = stanza.hmac_key {
                out.push_str(&format!("HMAC_KEY                    {}\n", hmac_key));
            }
            if let Some(ref hmac_b64) = stanza.hmac_key_base64 {
                out.push_str(&format!("HMAC_KEY_BASE64             {}\n", hmac_b64));
            }

            if let Some(ref digest) = stanza.hmac_digest_type {
                let dt = match digest {
                    HmacAlgorithm::Sha256 => "SHA256",
                    HmacAlgorithm::Sha384 => "SHA384",
                    HmacAlgorithm::Sha512 => "SHA512",
                };
                out.push_str(&format!("HMAC_DIGEST_TYPE            {}\n", dt));
            }

            out.push_str(&format!(
                "FW_ACCESS_TIMEOUT           {}\n",
                stanza.fw_access_timeout
            ));

            let enc = encryption_str(stanza.encryption_mode);
            out.push_str(&format!("ENCRYPTION_MODE             {}\n", enc));

            if stanza.require_source_address {
                out.push_str("REQUIRE_SOURCE_ADDRESS      Y\n");
            }

            if let Some(ref gpg_id) = stanza.gpg_remote_id {
                out.push_str(&format!("GPG_REMOTE_ID               {}\n", gpg_id));
            }
            if let Some(ref gpg_dec) = stanza.gpg_decrypt_id {
                out.push_str(&format!("GPG_DECRYPT_ID              {}\n", gpg_dec));
            }
            if let Some(ref gpg_home) = stanza.gpg_home_dir {
                out.push_str(&format!("GPG_HOME_DIR                {}\n", gpg_home));
            }
            if let Some(ref nat) = stanza.force_nat {
                out.push_str(&format!("FORCE_NAT                   {}\n", nat));
            }
            if let Some(ref snat) = stanza.force_snat {
                out.push_str(&format!("FORCE_SNAT                  {}\n", snat));
            }
            if let Some(ref cmd_open) = stanza.cmd_exec_on_open {
                out.push_str(&format!("CMD_EXEC_ON_OPEN            {}\n", cmd_open));
            }
            if let Some(ref cmd_close) = stanza.cmd_exec_on_close {
                out.push_str(&format!("CMD_EXEC_ON_CLOSE           {}\n", cmd_close));
            }
        }

        out
    }

    /// Parses fwknopd.conf content.
    pub fn parse_fwknopd_conf(content: &str) -> Result<FwknopServerConfig, PortKnockError> {
        let mut map: std::collections::HashMap<String, String> = std::collections::HashMap::new();

        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with(';') {
                continue;
            }
            if let Some((key, value)) = parse_kv_line(trimmed) {
                map.insert(key.to_uppercase(), value);
            }
        }

        let pcap_interface = map
            .get("PCAP_INTF")
            .or_else(|| map.get("PCAP_INTERFACE"))
            .cloned()
            .unwrap_or_else(|| "eth0".to_string());

        let pcap_filter = map
            .get("PCAP_FILTER")
            .cloned()
            .unwrap_or_else(|| "udp port 62201".to_string());

        let enable_pcap_promisc = map
            .get("ENABLE_PCAP_PROMISC")
            .map(|v| v == "Y" || v == "1" || v.eq_ignore_ascii_case("yes"))
            .unwrap_or(false);

        let max_spa_packet_age = map
            .get("MAX_SPA_PACKET_AGE")
            .and_then(|v| v.parse().ok())
            .unwrap_or(120);

        let enable_digest_persistence = map
            .get("ENABLE_DIGEST_PERSISTENCE")
            .map(|v| v == "Y" || v == "1" || v.eq_ignore_ascii_case("yes"))
            .unwrap_or(true);

        let rules_check_threshold = map
            .get("RULES_CHECK_THRESHOLD")
            .and_then(|v| v.parse().ok())
            .unwrap_or(20);

        let flush_rules_at_init = map
            .get("FLUSH_RULES_AT_INIT")
            .map(|v| v == "Y" || v == "1" || v.eq_ignore_ascii_case("yes"))
            .unwrap_or(true);

        let flush_rules_at_exit = map
            .get("FLUSH_RULES_AT_EXIT")
            .map(|v| v == "Y" || v == "1" || v.eq_ignore_ascii_case("yes"))
            .unwrap_or(true);

        let firewall_backend = match map
            .get("FIREWALL_EXE")
            .or_else(|| map.get("FIREWALL_BACKEND"))
            .map(|s| s.to_lowercase())
            .as_deref()
        {
            Some(s) if s.contains("iptables") => FirewallBackend::Iptables,
            Some(s) if s.contains("nft") => FirewallBackend::Nftables,
            Some(s) if s.contains("pf") => FirewallBackend::Pf,
            Some(s) if s.contains("firewalld") => FirewallBackend::Firewalld,
            _ => FirewallBackend::Iptables,
        };

        Ok(FwknopServerConfig {
            pcap_interface,
            pcap_filter,
            enable_pcap_promisc,
            max_spa_packet_age,
            enable_digest_persistence,
            rules_check_threshold,
            flush_rules_at_init,
            flush_rules_at_exit,
            firewall_backend,
            access_stanzas: Vec::new(),
        })
    }

    /// Generates fwknopd.conf content from config struct.
    pub fn generate_fwknopd_conf(config: &FwknopServerConfig) -> String {
        let mut out = String::new();
        out.push_str("# fwknopd.conf - generated by sorng-port-knock\n\n");
        out.push_str(&format!(
            "PCAP_INTF                   {}\n",
            config.pcap_interface
        ));
        out.push_str(&format!(
            "PCAP_FILTER                 {}\n",
            config.pcap_filter
        ));
        out.push_str(&format!(
            "ENABLE_PCAP_PROMISC         {}\n",
            yn(config.enable_pcap_promisc)
        ));
        out.push_str(&format!(
            "MAX_SPA_PACKET_AGE          {}\n",
            config.max_spa_packet_age
        ));
        out.push_str(&format!(
            "ENABLE_DIGEST_PERSISTENCE   {}\n",
            yn(config.enable_digest_persistence)
        ));
        out.push_str(&format!(
            "RULES_CHECK_THRESHOLD       {}\n",
            config.rules_check_threshold
        ));
        out.push_str(&format!(
            "FLUSH_RULES_AT_INIT         {}\n",
            yn(config.flush_rules_at_init)
        ));
        out.push_str(&format!(
            "FLUSH_RULES_AT_EXIT         {}\n",
            yn(config.flush_rules_at_exit)
        ));

        let fw_exe = match config.firewall_backend {
            FirewallBackend::Iptables => "/sbin/iptables",
            FirewallBackend::Nftables => "/usr/sbin/nft",
            FirewallBackend::Pf => "/sbin/pfctl",
            FirewallBackend::Firewalld => "/usr/bin/firewall-cmd",
            FirewallBackend::Ufw => "/usr/sbin/ufw",
            FirewallBackend::WindowsFirewall => "netsh",
        };
        out.push_str(&format!("FIREWALL_EXE                {}\n", fw_exe));

        out
    }

    /// Generates .fwknoprc file content for the given stanza name.
    pub fn generate_client_rc(config: &FwknopClientConfig, stanza_name: &str) -> String {
        let mut out = String::new();
        out.push_str("# .fwknoprc - generated by sorng-port-knock\n\n");
        out.push_str(&format!("[{}]\n", stanza_name));
        out.push_str(&format!(
            "SPA_SERVER                  {}\n",
            config.spa_server
        ));
        out.push_str(&format!(
            "SPA_SERVER_PORT             {}\n",
            config.spa_server_port
        ));

        let proto = match config.spa_server_proto {
            KnockProtocol::Tcp => "tcp",
            KnockProtocol::Udp => "udp",
        };
        out.push_str(&format!("SPA_SERVER_PROTO            {}\n", proto));

        out.push_str(&format!(
            "ACCESS                      {}\n",
            config.access_port
        ));

        if let Some(ref ip) = config.allow_ip {
            out.push_str(&format!("ALLOW_IP                    {}\n", ip));
        } else {
            out.push_str("ALLOW_IP                    resolve\n");
        }

        if let Some(ref url) = config.resolve_ip_url {
            out.push_str(&format!("RESOLVE_IP_URL              {}\n", url));
        }

        let enc = encryption_str(config.encryption_mode);
        out.push_str(&format!("ENCRYPTION_MODE             {}\n", enc));

        if let Some(ref key) = config.key {
            out.push_str(&format!("KEY                         {}\n", key));
        }
        if let Some(ref key_b64) = config.key_base64 {
            out.push_str(&format!("KEY_BASE64                  {}\n", key_b64));
        }
        if let Some(ref hmac_key) = config.hmac_key {
            out.push_str(&format!("HMAC_KEY                    {}\n", hmac_key));
        }
        if let Some(ref hmac_b64) = config.hmac_key_base64 {
            out.push_str(&format!("HMAC_KEY_BASE64             {}\n", hmac_b64));
        }

        let hmac_dt = match config.hmac_digest_type {
            HmacAlgorithm::Sha256 => "SHA256",
            HmacAlgorithm::Sha384 => "SHA384",
            HmacAlgorithm::Sha512 => "SHA512",
        };
        out.push_str(&format!("HMAC_DIGEST_TYPE            {}\n", hmac_dt));

        if let Some(sp) = config.spa_source_port {
            out.push_str(&format!("SPA_SOURCE_PORT             {}\n", sp));
        }

        if let Some(ref nat) = config.nat_access {
            out.push_str(&format!("NAT_ACCESS                  {}\n", nat));
        }
        if config.nat_local {
            out.push_str("NAT_LOCAL                   Y\n");
        }
        if let Some(np) = config.nat_port {
            out.push_str(&format!("NAT_PORT                    {}\n", np));
        }
        if let Some(t) = config.server_timeout {
            out.push_str(&format!("SERVER_TIMEOUT              {}\n", t));
        }
        if let Some(ref gpg) = config.gpg_recipient {
            out.push_str(&format!("GPG_RECIPIENT               {}\n", gpg));
        }
        if let Some(ref gpg_s) = config.gpg_signer {
            out.push_str(&format!("GPG_SIGNER                  {}\n", gpg_s));
        }
        if let Some(ref gpg_h) = config.gpg_home_dir {
            out.push_str(&format!("GPG_HOME_DIR                {}\n", gpg_h));
        }

        out
    }

    /// Parses .fwknoprc content (takes the first stanza found).
    pub fn parse_client_rc(content: &str) -> Result<FwknopClientConfig, PortKnockError> {
        let mut map: std::collections::HashMap<String, String> = std::collections::HashMap::new();

        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty()
                || trimmed.starts_with('#')
                || trimmed.starts_with(';')
                || trimmed.starts_with('[')
            {
                continue;
            }
            if let Some((key, value)) = parse_kv_line(trimmed) {
                map.insert(key.to_uppercase(), value);
            }
        }

        let spa_server = map
            .get("SPA_SERVER")
            .cloned()
            .ok_or_else(|| PortKnockError::FwknopError("Missing SPA_SERVER".to_string()))?;

        let spa_server_port = map
            .get("SPA_SERVER_PORT")
            .and_then(|v| v.parse().ok())
            .unwrap_or(62201);

        let spa_server_proto = match map
            .get("SPA_SERVER_PROTO")
            .map(|s| s.to_lowercase())
            .as_deref()
        {
            Some("tcp") => KnockProtocol::Tcp,
            _ => KnockProtocol::Udp,
        };

        let access_port = map
            .get("ACCESS")
            .cloned()
            .unwrap_or_else(|| "tcp/22".to_string());

        let allow_ip =
            map.get("ALLOW_IP")
                .cloned()
                .and_then(|v| if v == "resolve" { None } else { Some(v) });

        let resolve_ip_url = map.get("RESOLVE_IP_URL").cloned();

        let encryption_mode = map
            .get("ENCRYPTION_MODE")
            .map(|v| parse_encryption_mode(v))
            .unwrap_or(KnockEncryption::Aes256Cbc);

        let key = map.get("KEY").cloned();
        let key_base64 = map.get("KEY_BASE64").cloned();
        let hmac_key = map.get("HMAC_KEY").cloned();
        let hmac_key_base64 = map.get("HMAC_KEY_BASE64").cloned();

        let hmac_digest_type = map
            .get("HMAC_DIGEST_TYPE")
            .map(|v| parse_hmac_algorithm(v))
            .unwrap_or(HmacAlgorithm::Sha256);

        let spa_source_port = map.get("SPA_SOURCE_PORT").and_then(|v| v.parse().ok());

        let nat_access = map.get("NAT_ACCESS").cloned();

        let nat_local = map
            .get("NAT_LOCAL")
            .map(|v| v == "Y" || v == "1" || v.eq_ignore_ascii_case("yes"))
            .unwrap_or(false);

        let nat_port = map.get("NAT_PORT").and_then(|v| v.parse().ok());
        let server_timeout = map.get("SERVER_TIMEOUT").and_then(|v| v.parse().ok());
        let gpg_recipient = map.get("GPG_RECIPIENT").cloned();
        let gpg_signer = map.get("GPG_SIGNER").cloned();
        let gpg_home_dir = map.get("GPG_HOME_DIR").cloned();

        Ok(FwknopClientConfig {
            spa_server,
            spa_server_port,
            spa_server_proto,
            access_port,
            allow_ip,
            resolve_ip_url,
            encryption_mode,
            key,
            key_base64,
            hmac_key,
            hmac_key_base64,
            hmac_digest_type,
            spa_source_port,
            nat_access,
            nat_local,
            nat_port,
            server_timeout,
            gpg_recipient,
            gpg_signer,
            gpg_home_dir,
        })
    }

    /// Builds the `fwknop` client command from the config.
    pub fn build_client_command(config: &FwknopClientConfig) -> String {
        let mut cmd = String::from("fwknop");

        cmd.push_str(&format!(" -A {}", config.access_port));
        cmd.push_str(&format!(" -D {}", config.spa_server));

        if config.spa_server_port != 62201 {
            cmd.push_str(&format!(" --server-port {}", config.spa_server_port));
        }

        if let KnockProtocol::Tcp = config.spa_server_proto {
            cmd.push_str(" --server-proto tcp");
        }

        if let Some(ref ip) = config.allow_ip {
            cmd.push_str(&format!(" -a {}", ip));
        } else {
            cmd.push_str(" -R");
        }

        if let Some(ref key_b64) = config.key_base64 {
            cmd.push_str(&format!(" --key-base64 {}", key_b64));
        } else if let Some(ref key) = config.key {
            cmd.push_str(&format!(" --key {}", key));
        }

        if let Some(ref hmac_b64) = config.hmac_key_base64 {
            cmd.push_str(&format!(" --hmac-base64 {}", hmac_b64));
        } else if let Some(ref hmac_key) = config.hmac_key {
            cmd.push_str(&format!(" --hmac-key {}", hmac_key));
        }

        let hmac_dt = match config.hmac_digest_type {
            HmacAlgorithm::Sha256 => "SHA256",
            HmacAlgorithm::Sha384 => "SHA384",
            HmacAlgorithm::Sha512 => "SHA512",
        };
        cmd.push_str(&format!(" --hmac-digest-type {}", hmac_dt));

        match config.encryption_mode {
            KnockEncryption::Aes256Cbc => {} // default, no flag needed
            KnockEncryption::Aes256Gcm => cmd.push_str(" --encryption-mode cbc"),
            _ => {
                if config.gpg_recipient.is_some() {
                    cmd.push_str(" --gpg-encryption");
                    if let Some(ref recip) = config.gpg_recipient {
                        cmd.push_str(&format!(" --gpg-recipient {}", recip));
                    }
                    if let Some(ref signer) = config.gpg_signer {
                        cmd.push_str(&format!(" --gpg-signer {}", signer));
                    }
                    if let Some(ref home) = config.gpg_home_dir {
                        cmd.push_str(&format!(" --gpg-home-dir {}", home));
                    }
                }
            }
        }

        if let Some(sp) = config.spa_source_port {
            cmd.push_str(&format!(" --source-port {}", sp));
        }

        if let Some(ref nat) = config.nat_access {
            cmd.push_str(&format!(" -N {}", nat));
        }
        if config.nat_local {
            cmd.push_str(" --nat-local");
        }
        if let Some(np) = config.nat_port {
            cmd.push_str(&format!(" --nat-port {}", np));
        }

        if let Some(t) = config.server_timeout {
            cmd.push_str(&format!(" --server-timeout {}", t));
        }

        cmd
    }

    /// Builds the command to start fwknopd server.
    pub fn build_server_start_command() -> String {
        "systemctl start fwknopd 2>/dev/null || fwknopd".to_string()
    }

    /// Builds the command to stop fwknopd server.
    pub fn build_server_stop_command() -> String {
        "systemctl stop fwknopd 2>/dev/null || killall fwknopd".to_string()
    }

    /// Builds the command to check fwknopd server status.
    pub fn build_server_status_command() -> String {
        "systemctl status fwknopd 2>/dev/null || fwknopd --status".to_string()
    }

    /// Returns the default access.conf path.
    pub fn get_access_conf_path() -> &'static str {
        "/etc/fwknop/access.conf"
    }

    /// Returns the default fwknopd.conf path.
    pub fn get_fwknopd_conf_path() -> &'static str {
        "/etc/fwknop/fwknopd.conf"
    }

    /// Returns the default .fwknoprc path.
    pub fn get_fwknoprc_path() -> &'static str {
        "~/.fwknoprc"
    }

    /// Returns the install command for the given distro.
    pub fn install_command(distro: &str) -> String {
        match distro.to_lowercase().as_str() {
            "debian" | "ubuntu" | "mint" | "pop" => {
                "apt-get install -y fwknop-client fwknop-server".to_string()
            }
            "rhel" | "centos" | "rocky" | "alma" | "fedora" => {
                "dnf install -y fwknop 2>/dev/null || yum install -y fwknop".to_string()
            }
            "arch" | "manjaro" => "pacman -S --noconfirm fwknop".to_string(),
            "suse" | "opensuse" => "zypper install -y fwknop".to_string(),
            "alpine" => "apk add fwknop".to_string(),
            "gentoo" => "emerge net-misc/fwknop".to_string(),
            _ => {
                format!(
                    "echo 'Unknown distro: {}. Try: apt-get install fwknop-client fwknop-server / dnf install fwknop / pacman -S fwknop'",
                    distro
                )
            }
        }
    }

    /// Generates a random key and HMAC key as base64 strings.
    /// Uses a simple PRNG from std; for production use a CSPRNG.
    pub fn generate_keys() -> (String, String) {
        use std::time::{SystemTime, UNIX_EPOCH};

        // Seed from system time for deterministic-free generation
        let seed = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();

        let mut state = seed;
        let mut gen_bytes = |len: usize| -> Vec<u8> {
            let mut buf = Vec::with_capacity(len);
            for _ in 0..len {
                // xorshift-style mixing
                state ^= state << 13;
                state ^= state >> 7;
                state ^= state << 17;
                buf.push((state & 0xFF) as u8);
            }
            buf
        };

        let key_bytes = gen_bytes(32);
        let hmac_bytes = gen_bytes(32);

        use crate::base64_util;
        let key_b64 = base64_util::encode(&key_bytes);
        let hmac_b64 = base64_util::encode(&hmac_bytes);

        (key_b64, hmac_b64)
    }

    /// Validates a single access stanza for required fields and consistency.
    pub fn validate_stanza(stanza: &FwknopAccessStanza) -> Result<(), PortKnockError> {
        if stanza.source.is_empty() {
            return Err(PortKnockError::FwknopError(
                "SOURCE must not be empty".to_string(),
            ));
        }

        if stanza.open_ports.is_empty() {
            return Err(PortKnockError::FwknopError(
                "OPEN_PORTS must have at least one entry".to_string(),
            ));
        }

        // Validate port format: "proto/port"
        for port_spec in &stanza.open_ports {
            let parts: Vec<&str> = port_spec.split('/').collect();
            if parts.len() != 2 {
                return Err(PortKnockError::FwknopError(format!(
                    "Invalid port spec '{}': expected proto/port",
                    port_spec
                )));
            }
            let proto = parts[0].to_lowercase();
            if proto != "tcp" && proto != "udp" {
                return Err(PortKnockError::FwknopError(format!(
                    "Invalid protocol '{}' in port spec",
                    parts[0]
                )));
            }
            if parts[1].parse::<u16>().is_err() {
                return Err(PortKnockError::FwknopError(format!(
                    "Invalid port number '{}' in port spec",
                    parts[1]
                )));
            }
        }

        // Must have at least one key mechanism
        let has_symmetric_key = stanza.key.is_some() || stanza.key_base64.is_some();
        let has_gpg_key = stanza.gpg_remote_id.is_some() && stanza.gpg_decrypt_id.is_some();

        if !has_symmetric_key && !has_gpg_key {
            return Err(PortKnockError::FwknopError(
                "Stanza must have either KEY/KEY_BASE64 or GPG_REMOTE_ID+GPG_DECRYPT_ID"
                    .to_string(),
            ));
        }

        if stanza.fw_access_timeout == 0 {
            return Err(PortKnockError::FwknopError(
                "FW_ACCESS_TIMEOUT must be > 0".to_string(),
            ));
        }

        Ok(())
    }
}

// ─── Helpers ───────────────────────────────────────────────────────

/// Parse a key-value line with flexible separators (whitespace, '=', ':').
fn parse_kv_line(line: &str) -> Option<(String, String)> {
    // Try "KEY = VALUE" first
    if let Some(eq_pos) = line.find('=') {
        let key = line[..eq_pos].trim();
        let value = line[eq_pos + 1..].trim();
        if !key.is_empty() {
            return Some((key.to_string(), value.to_string()));
        }
    }

    // Try whitespace separated: KEY  VALUE (first token is key, rest is value)
    let mut parts = line.splitn(2, char::is_whitespace);
    let key = parts.next()?.trim();
    let value = parts.next().unwrap_or("").trim();
    if key.is_empty() {
        return None;
    }
    Some((key.to_string(), value.to_string()))
}

/// Converts an encryption mode enum to its config string representation.
fn encryption_str(mode: KnockEncryption) -> &'static str {
    match mode {
        KnockEncryption::None => "NONE",
        KnockEncryption::Aes256Gcm => "AES_GCM",
        KnockEncryption::Aes256Cbc => "CBC",
        KnockEncryption::RijndaelCbc => "CBC",
        KnockEncryption::ChaCha20Poly1305 => "CHACHA20",
    }
}

/// Parses an encryption mode string to enum.
fn parse_encryption_mode(s: &str) -> KnockEncryption {
    match s.to_uppercase().as_str() {
        "CBC" | "RIJNDAEL" | "AES_CBC" => KnockEncryption::Aes256Cbc,
        "AES_GCM" | "GCM" => KnockEncryption::Aes256Gcm,
        "CHACHA20" | "CHACHA20_POLY1305" => KnockEncryption::ChaCha20Poly1305,
        "NONE" => KnockEncryption::None,
        _ => KnockEncryption::Aes256Cbc,
    }
}

/// Parses an HMAC algorithm string to enum.
fn parse_hmac_algorithm(s: &str) -> HmacAlgorithm {
    match s.to_uppercase().as_str() {
        "SHA384" => HmacAlgorithm::Sha384,
        "SHA512" => HmacAlgorithm::Sha512,
        _ => HmacAlgorithm::Sha256,
    }
}

/// Bool -> "Y"/"N".
fn yn(b: bool) -> &'static str {
    if b {
        "Y"
    } else {
        "N"
    }
}

/// Builds an FwknopAccessStanza from a parsed key-value map.
fn build_access_stanza(
    map: &std::collections::HashMap<String, String>,
) -> Result<FwknopAccessStanza, PortKnockError> {
    let source = map.get("SOURCE").cloned().ok_or_else(|| {
        PortKnockError::FwknopError("Missing SOURCE in access stanza".to_string())
    })?;

    let open_ports: Vec<String> = map
        .get("OPEN_PORTS")
        .map(|v| v.split(',').map(|s| s.trim().to_string()).collect())
        .unwrap_or_default();

    if open_ports.is_empty() {
        return Err(PortKnockError::FwknopError(
            "Missing or empty OPEN_PORTS in access stanza".to_string(),
        ));
    }

    let restrict_ports: Option<Vec<String>> = map
        .get("RESTRICT_PORTS")
        .map(|v| v.split(',').map(|s| s.trim().to_string()).collect());

    let key = map.get("KEY").cloned();
    let key_base64 = map.get("KEY_BASE64").cloned();
    let hmac_key = map.get("HMAC_KEY").cloned();
    let hmac_key_base64 = map.get("HMAC_KEY_BASE64").cloned();

    let hmac_digest_type = map.get("HMAC_DIGEST_TYPE").map(|v| parse_hmac_algorithm(v));

    let fw_access_timeout = map
        .get("FW_ACCESS_TIMEOUT")
        .and_then(|v| v.parse().ok())
        .unwrap_or(30);

    let encryption_mode = map
        .get("ENCRYPTION_MODE")
        .map(|v| parse_encryption_mode(v))
        .unwrap_or(KnockEncryption::Aes256Cbc);

    let require_source_address = map
        .get("REQUIRE_SOURCE_ADDRESS")
        .map(|v| v == "Y" || v == "1" || v.eq_ignore_ascii_case("yes"))
        .unwrap_or(false);

    let gpg_remote_id = map.get("GPG_REMOTE_ID").cloned();
    let gpg_decrypt_id = map.get("GPG_DECRYPT_ID").cloned();
    let gpg_home_dir = map.get("GPG_HOME_DIR").cloned();
    let force_nat = map.get("FORCE_NAT").cloned();
    let force_snat = map.get("FORCE_SNAT").cloned();
    let cmd_exec_on_open = map.get("CMD_EXEC_ON_OPEN").cloned();
    let cmd_exec_on_close = map.get("CMD_EXEC_ON_CLOSE").cloned();

    Ok(FwknopAccessStanza {
        source,
        open_ports,
        restrict_ports,
        key,
        key_base64,
        hmac_key,
        hmac_key_base64,
        hmac_digest_type,
        fw_access_timeout,
        encryption_mode,
        require_source_address,
        gpg_remote_id,
        gpg_decrypt_id,
        gpg_home_dir,
        force_nat,
        force_snat,
        cmd_exec_on_open,
        cmd_exec_on_close,
    })
}
