// @generated by scripts/generate-command-inventory.mjs; edit commands.json instead.
use crate::*;

pub const COMMAND_NAMES: &[&str] = &[
    #[cfg(feature = "kafka")]
    "kafka_alter_quotas",
    #[cfg(feature = "kafka")]
    "kafka_connect",
    #[cfg(feature = "kafka")]
    "kafka_create_acls",
    #[cfg(feature = "kafka")]
    "kafka_create_connector",
    #[cfg(feature = "kafka")]
    "kafka_create_topic",
    #[cfg(feature = "kafka")]
    "kafka_delete_acls",
    #[cfg(feature = "kafka")]
    "kafka_delete_connector",
    #[cfg(feature = "kafka")]
    "kafka_delete_subject",
    #[cfg(feature = "kafka")]
    "kafka_delete_topic",
    #[cfg(feature = "kafka")]
    "kafka_describe_consumer_group",
    #[cfg(feature = "kafka")]
    "kafka_disconnect",
    #[cfg(feature = "kafka")]
    "kafka_get_broker",
    #[cfg(feature = "kafka")]
    "kafka_get_broker_config",
    #[cfg(feature = "kafka")]
    "kafka_get_broker_metrics",
    #[cfg(feature = "kafka")]
    "kafka_get_cluster_id",
    #[cfg(feature = "kafka")]
    "kafka_get_cluster_metrics",
    #[cfg(feature = "kafka")]
    "kafka_get_connector",
    #[cfg(feature = "kafka")]
    "kafka_get_consumer_group_offsets",
    #[cfg(feature = "kafka")]
    "kafka_get_partition",
    #[cfg(feature = "kafka")]
    "kafka_get_schema",
    #[cfg(feature = "kafka")]
    "kafka_get_topic",
    #[cfg(feature = "kafka")]
    "kafka_get_topic_metrics",
    #[cfg(feature = "kafka")]
    "kafka_list_acls",
    #[cfg(feature = "kafka")]
    "kafka_list_brokers",
    #[cfg(feature = "kafka")]
    "kafka_list_connectors",
    #[cfg(feature = "kafka")]
    "kafka_list_consumer_groups",
    #[cfg(feature = "kafka")]
    "kafka_list_partitions",
    #[cfg(feature = "kafka")]
    "kafka_list_quotas",
    #[cfg(feature = "kafka")]
    "kafka_list_reassignments",
    #[cfg(feature = "kafka")]
    "kafka_list_sessions",
    #[cfg(feature = "kafka")]
    "kafka_list_subjects",
    #[cfg(feature = "kafka")]
    "kafka_list_topics",
    #[cfg(feature = "kafka")]
    "kafka_pause_connector",
    #[cfg(feature = "kafka")]
    "kafka_produce_message",
    #[cfg(feature = "kafka")]
    "kafka_register_schema",
    #[cfg(feature = "kafka")]
    "kafka_resume_connector",
    #[cfg(feature = "kafka")]
    "kafka_start_reassignment",
    #[cfg(feature = "kafka")]
    "kafka_test_connection",
    #[cfg(feature = "kafka")]
    "kafka_update_broker_config",
    "rabbit_aliveness_test",
    "rabbit_cancel_consumer",
    "rabbit_check_alarms",
    "rabbit_clone_vhost",
    "rabbit_close_connection",
    "rabbit_connect",
    "rabbit_create_binding",
    "rabbit_create_exchange",
    "rabbit_create_federation_upstream",
    "rabbit_create_policy",
    "rabbit_create_queue",
    "rabbit_create_shovel",
    "rabbit_create_user",
    "rabbit_create_vhost",
    "rabbit_definitions_summary",
    "rabbit_delete_binding",
    "rabbit_delete_exchange",
    "rabbit_delete_federation_upstream",
    "rabbit_delete_policy",
    "rabbit_delete_queue",
    "rabbit_delete_shovel",
    "rabbit_delete_user",
    "rabbit_delete_vhost",
    "rabbit_disconnect",
    "rabbit_export_definitions",
    "rabbit_export_vhost_definitions",
    "rabbit_get_channel",
    "rabbit_get_cluster_name",
    "rabbit_get_connection",
    "rabbit_get_exchange",
    "rabbit_get_message_rates",
    "rabbit_get_node",
    "rabbit_get_overview",
    "rabbit_get_queue",
    "rabbit_get_queue_rates",
    "rabbit_get_vhost",
    "rabbit_import_definitions",
    "rabbit_list_bindings",
    "rabbit_list_channels",
    "rabbit_list_connections",
    "rabbit_list_consumers",
    "rabbit_list_exchanges",
    "rabbit_list_federation_links",
    "rabbit_list_federation_upstreams",
    "rabbit_list_nodes",
    "rabbit_list_permissions",
    "rabbit_list_policies",
    "rabbit_list_queues",
    "rabbit_list_sessions",
    "rabbit_list_shovels",
    "rabbit_list_users",
    "rabbit_list_vhosts",
    "rabbit_monitoring_snapshot",
    "rabbit_purge_queue",
    "rabbit_restart_shovel",
    "rabbit_set_cluster_name",
    "rabbit_set_permission",
    "rabbit_test_connection",
];

pub fn is_command(command: &str) -> bool {
    COMMAND_NAMES.binary_search(&command).is_ok()
}

pub fn build() -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_alter_quotas,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_connect,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_create_acls,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_create_connector,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_create_topic,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_delete_acls,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_delete_connector,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_delete_subject,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_delete_topic,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_describe_consumer_group,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_disconnect,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_get_broker,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_get_broker_config,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_get_broker_metrics,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_get_cluster_id,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_get_cluster_metrics,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_get_connector,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_get_consumer_group_offsets,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_get_partition,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_get_schema,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_get_topic,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_get_topic_metrics,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_list_acls,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_list_brokers,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_list_connectors,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_list_consumer_groups,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_list_partitions,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_list_quotas,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_list_reassignments,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_list_sessions,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_list_subjects,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_list_topics,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_pause_connector,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_produce_message,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_register_schema,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_resume_connector,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_start_reassignment,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_test_connection,
        #[cfg(feature = "kafka")]
        kafka_commands::kafka_update_broker_config,
        rabbitmq_commands::rabbit_aliveness_test,
        rabbitmq_commands::rabbit_cancel_consumer,
        rabbitmq_commands::rabbit_check_alarms,
        rabbitmq_commands::rabbit_clone_vhost,
        rabbitmq_commands::rabbit_close_connection,
        rabbitmq_commands::rabbit_connect,
        rabbitmq_commands::rabbit_create_binding,
        rabbitmq_commands::rabbit_create_exchange,
        rabbitmq_commands::rabbit_create_federation_upstream,
        rabbitmq_commands::rabbit_create_policy,
        rabbitmq_commands::rabbit_create_queue,
        rabbitmq_commands::rabbit_create_shovel,
        rabbitmq_commands::rabbit_create_user,
        rabbitmq_commands::rabbit_create_vhost,
        rabbitmq_commands::rabbit_definitions_summary,
        rabbitmq_commands::rabbit_delete_binding,
        rabbitmq_commands::rabbit_delete_exchange,
        rabbitmq_commands::rabbit_delete_federation_upstream,
        rabbitmq_commands::rabbit_delete_policy,
        rabbitmq_commands::rabbit_delete_queue,
        rabbitmq_commands::rabbit_delete_shovel,
        rabbitmq_commands::rabbit_delete_user,
        rabbitmq_commands::rabbit_delete_vhost,
        rabbitmq_commands::rabbit_disconnect,
        rabbitmq_commands::rabbit_export_definitions,
        rabbitmq_commands::rabbit_export_vhost_definitions,
        rabbitmq_commands::rabbit_get_channel,
        rabbitmq_commands::rabbit_get_cluster_name,
        rabbitmq_commands::rabbit_get_connection,
        rabbitmq_commands::rabbit_get_exchange,
        rabbitmq_commands::rabbit_get_message_rates,
        rabbitmq_commands::rabbit_get_node,
        rabbitmq_commands::rabbit_get_overview,
        rabbitmq_commands::rabbit_get_queue,
        rabbitmq_commands::rabbit_get_queue_rates,
        rabbitmq_commands::rabbit_get_vhost,
        rabbitmq_commands::rabbit_import_definitions,
        rabbitmq_commands::rabbit_list_bindings,
        rabbitmq_commands::rabbit_list_channels,
        rabbitmq_commands::rabbit_list_connections,
        rabbitmq_commands::rabbit_list_consumers,
        rabbitmq_commands::rabbit_list_exchanges,
        rabbitmq_commands::rabbit_list_federation_links,
        rabbitmq_commands::rabbit_list_federation_upstreams,
        rabbitmq_commands::rabbit_list_nodes,
        rabbitmq_commands::rabbit_list_permissions,
        rabbitmq_commands::rabbit_list_policies,
        rabbitmq_commands::rabbit_list_queues,
        rabbitmq_commands::rabbit_list_sessions,
        rabbitmq_commands::rabbit_list_shovels,
        rabbitmq_commands::rabbit_list_users,
        rabbitmq_commands::rabbit_list_vhosts,
        rabbitmq_commands::rabbit_monitoring_snapshot,
        rabbitmq_commands::rabbit_purge_queue,
        rabbitmq_commands::rabbit_restart_shovel,
        rabbitmq_commands::rabbit_set_cluster_name,
        rabbitmq_commands::rabbit_set_permission,
        rabbitmq_commands::rabbit_test_connection,
    ]
}

#[cfg(test)]
mod tests {
    #[test]
    fn inventory_is_sorted_unique_and_bounded() {
        let names = super::COMMAND_NAMES;
        assert!(names.len() <= 250);
        assert!(names.windows(2).all(|pair| pair[0] < pair[1]));
        assert!(names.iter().all(|name| super::is_command(name)));
        assert!(!super::is_command("__unknown_command__"));
    }
}
