// Per-panel sub-tab registry for the unified Mail Server panel (t42 Wave M —
// the intra-panel analogue of the top-level integrations registry).
//
// Unlike the cpanel/php shells (one shared connection → tabs consume a
// `connectionId`), the 8 mail-chain crates are INDEPENDENT daemons: each sub-tab
// is a self-contained mini-panel that owns its own connect form + connection
// lifecycle + management views. The shell (`MailServerPanel.tsx`) only renders
// the sub-tab bar and Suspense-mounts the active tab from this array.
//
// Sub-tab executors (t42-mail-<crate>) DO NOT edit this file directly — the
// per-crate integrator appends their entry, mirroring the disjoint-append
// discipline of the top-level category registries. The lead ships it EMPTY.

import type { ComponentType } from "react";
import type { LucideIcon } from "lucide-react";
import { FileSignature } from "lucide-react";

/** Props every mail sub-tab receives from the shell. Each mail sub-tab manages
 *  its OWN service connection and persistence, so nothing is required. `active`
 *  is a visibility hint (only the active tab is mounted, so it is `true` when the
 *  tab renders) that a tab may use to defer polling; a tab can safely ignore it.
 *  No `connectionId` is passed — a sub-tab connects itself. */
export interface MailSubTabProps {
  active?: boolean;
}

/** One mail-chain crate's sub-tab in the unified Mail Server panel. `label` may
 *  be an i18n key resolved at render time; a plain English string is the safe
 *  default. */
export interface MailSubTab {
  /** Stable key, e.g. `"postfix"` / `"cyrusSasl"`. Used for the active-tab state
   *  and the i18n subtree (`integrations.mail.<subTabKey>.*`). */
  subTabKey: string;
  /** The backing Rust crate dir, e.g. `"sorng-postfix"`. Documentation only. */
  crate: string;
  /** Human label (or i18n key). */
  label: string;
  /** Lucide icon rendered on the sub-tab. */
  icon: LucideIcon;
  /** Lazy import of the sub-tab module; the shell wraps it in Suspense. */
  importTab: () => Promise<{ default: ComponentType<MailSubTabProps> }>;
}

/** Registered Mail Server sub-tabs, in mail-flow order (MTA → delivery →
 *  filter chain → auth). EMPTY at lead time; the per-crate integrator appends a
 *  `{ subTabKey, crate, label, icon, importTab }` for each of the 8 crate execs
 *  (postfix, dovecot, amavis, opendkim, cyrusSasl, procmail, rspamd, clamav). */
export const mailSubTabs: MailSubTab[] = [
  {
    subTabKey: "opendkim",
    crate: "sorng-opendkim",
    label: "OpenDKIM",
    icon: FileSignature,
    importTab: () => import("./OpendkimSubTab"),
  },
];
