import type {
  SynologyTab,
  SynologyAdminData,
} from "../../hooks/synology/synologyAdminData";

export const SYNOLOGY_SECTION_LABELS: Record<SynologyTab, string> = {
  fileStation: "File Station",
  dashboard: "Overview",
  system: "System",
  storage: "Storage",
  shares: "Shared folders",
  network: "Network",
  users: "Users and groups",
  packages: "Packages",
  services: "File services",
  docker: "Containers",
  vms: "Virtual machines",
  downloads: "Downloads",
  surveillance: "Cameras",
  backup: "Backup",
  security: "Security",
  hardware: "Hardware and power",
  logs: "Logs",
  notifications: "Notifications",
};

export const SYNOLOGY_READ_LABELS: Record<keyof SynologyAdminData, string> = {
  dashboard: "Overview",
  systemInfo: "System information",
  utilization: "Resource usage",
  storageOverview: "Storage overview",
  disks: "Disks",
  volumes: "Volumes",
  selectedDiskSmart: "Disk health",
  sharedFolders: "Shared folders",
  networkOverview: "Network overview",
  networkInterfaces: "Network interfaces",
  firewallRules: "Firewall rules",
  users: "Users",
  groups: "Groups",
  packages: "Packages",
  services: "Services",
  smbConfig: "Windows file sharing (SMB)",
  nfsConfig: "Network file sharing (NFS)",
  sshConfig: "Secure Shell (SSH)",
  dockerContainers: "Containers",
  dockerImages: "Container images",
  dockerNetworks: "Container networks",
  dockerProjects: "Container projects",
  vms: "Virtual machines",
  downloadTasks: "Download tasks",
  downloadStats: "Download statistics",
  cameras: "Cameras",
  backupTasks: "Backup tasks",
  activeBackupDevices: "Backup devices",
  securityOverview: "Security overview",
  blockedIps: "Blocked addresses",
  certificates: "Certificates",
  autoBlockConfig: "Automatic blocking",
  hardwareInfo: "Hardware information",
  upsInfo: "Uninterruptible power supply",
  powerSchedule: "Power schedule",
  systemLogs: "System logs",
  connectionLogs: "Connection logs",
  notificationConfig: "Notification settings",
};
