const PUBLIC_VERSION_PATTERN = /^(\d{2})\.([1-9]\d*)$/;
const DISPLAY_VERSION_PATTERN =
  /^v?(\d{2})\.(0|[1-9]\d*)(?:\.(?:0|[1-9]\d*))?(?:[-+].*)?$/;

export function projectVersion(value) {
  if (typeof value !== "string") {
    throw new TypeError("version.json must contain a string version");
  }

  const publicVersion = value.trim();
  const match = PUBLIC_VERSION_PATTERN.exec(publicVersion);
  if (!match) {
    throw new Error(
      `Invalid public version ${JSON.stringify(value)}; expected YY.N with N >= 1 (for example 26.1)`,
    );
  }

  return {
    publicVersion,
    machineVersion: `${publicVersion}.0`,
    year: Number(match[1]),
    release: Number(match[2]),
  };
}

export function formatPublicVersion(value, fallback = "-") {
  if (typeof value !== "string" || value.trim().length === 0) return fallback;

  const normalized = value.trim();
  const match = DISPLAY_VERSION_PATTERN.exec(normalized);
  return match ? `${match[1]}.${match[2]}` : normalized;
}

export function rewriteRootCargoManifest(source, machineVersion) {
  const newline = source.includes("\r\n") ? "\r\n" : "\n";
  let next = source;

  const workspacePackage = [
    "[workspace.package]",
    "# Machine-only SemVer projection of the public YY.N release in ../version.json.",
    `version = "${machineVersion}"`,
    "",
    "",
  ].join(newline);

  const workspacePackagePattern =
    /^\[workspace\.package\]\r?\n[\s\S]*?(?=^\[[^\]]+\]\r?$)/m;
  if (workspacePackagePattern.test(next)) {
    next = next.replace(workspacePackagePattern, workspacePackage);
  } else {
    const dependencyHeader = /^\[workspace\.dependencies\]\r?$/m;
    if (!dependencyHeader.test(next)) {
      throw new Error("Root Cargo.toml is missing [workspace.dependencies]");
    }
    next = next.replace(dependencyHeader, `${workspacePackage}$&`);
  }

  const packagePattern = /^\[package\]\r?\n[\s\S]*?(?=^\[[^\]]+\]\r?$)/m;
  const packageBlock = packagePattern.exec(next)?.[0];
  if (!packageBlock) throw new Error("Root Cargo.toml is missing [package]");

  const rewrittenPackageBlock = rewriteCargoPackageVersion(packageBlock);
  return next.replace(packageBlock, rewrittenPackageBlock);
}

export function rewriteMemberCargoManifest(source) {
  const packagePattern =
    /^\[package\]\r?\n[\s\S]*?(?=^\[[^\]]+\]\r?$|(?![\s\S]))/m;
  const packageBlock = packagePattern.exec(source)?.[0];
  if (!packageBlock) throw new Error("Cargo.toml is missing [package]");
  return source.replace(packageBlock, rewriteCargoPackageVersion(packageBlock));
}

function rewriteCargoPackageVersion(packageBlock) {
  const versionPattern = /^version(?:\.workspace)?\s*=.*$/m;
  if (!versionPattern.test(packageBlock)) {
    throw new Error("Cargo [package] is missing a version field");
  }
  return packageBlock.replace(versionPattern, "version.workspace = true");
}

export function cargoPackageName(source) {
  const packagePattern =
    /^\[package\]\r?\n[\s\S]*?(?=^\[[^\]]+\]\r?$|(?![\s\S]))/m;
  const packageBlock = packagePattern.exec(source)?.[0];
  const match = packageBlock?.match(/^name\s*=\s*"([^"]+)"\r?$/m);
  if (!match) throw new Error("Cargo [package] is missing a quoted name");
  return match[1];
}

export function rewriteCargoLock(source, packageNames, machineVersion) {
  const expected = new Set(packageNames);
  const found = new Set();
  const blockPattern =
    /^\[\[package\]\]\r?\n[\s\S]*?(?=^\[\[package\]\]\r?$|(?![\s\S]))/gm;

  const text = source.replace(blockPattern, (block) => {
    const name = block.match(/^name = "([^"]+)"\r?$/m)?.[1];
    if (!name || !expected.has(name)) return block;

    const versionPattern = /^version = "[^"]+"\r?$/m;
    if (!versionPattern.test(block)) {
      throw new Error(`Cargo.lock package ${name} is missing a version`);
    }
    found.add(name);
    return block.replace(versionPattern, `version = "${machineVersion}"`);
  });

  return { text, found };
}

export function renderFrontendVersionModule(publicVersion, machineVersion) {
  return [
    "// Generated by `npm run version:sync`; do not edit by hand.",
    "",
    "/** Public rolling release identity. Render this YY.N value in the UI. */",
    `export const APP_VERSION = "${publicVersion}";`,
    "",
    "/** Machine-only SemVer projection for package/build interoperability. Never render this value. */",
    `export const APP_MACHINE_VERSION = "${machineVersion}";`,
    "",
    "/** Convert updater SemVer values to the public YY.N release identity. */",
    "export function formatAppVersion(",
    "  version: string | null | undefined,",
    '  fallback = "-",',
    "): string {",
    '  if (typeof version !== "string" || version.trim().length === 0)',
    "    return fallback;",
    "",
    "  const value = version.trim();",
    "  const match =",
    "    /^v?(\\d{2})\\.(0|[1-9]\\d*)(?:\\.(?:0|[1-9]\\d*))?(?:[-+].*)?$/.exec(value);",
    "  return match ? `${match[1]}.${match[2]}` : value;",
    "}",
    "",
  ].join("\n");
}
