import { readFileSync } from "node:fs";
import {
  afterEach,
  beforeEach,
  describe,
  expect,
  it,
  vi,
  type MockInstance,
} from "vitest";
import {
  clearSessionActivityLog,
  getSessionActivityLog,
  recordSessionActivity,
  type SessionActivityCode,
} from "../../src/utils/monitoring/sessionActivityLog";
import {
  parseSynologyLoginProgress,
  SYNOLOGY_LOGIN_PROGRESS_VOCABULARY as hook,
} from "../../src/hooks/protocol/useDeferredSynologyLoginStatus";

// A status the helper emits but the bridge or hook does not accept is dropped
// silently, so the pill keeps showing an older phase. This suite reads the
// production helper and bridge from disk and requires all three to agree.
const helper = readFileSync(
  "src-tauri/crates/sorng-protocols/src/synology_autologin_client.js",
  "utf8",
);
const bridge = readFileSync(
  "src-tauri/crates/sorng-protocols/src/synology_login_progress_client.js",
  "utf8",
);

// The closed vocabulary fixed by plan t85 §2.2, plus the trace contract agreed
// between the page helper and the bridge.
const CONTRACT = {
  phases: [
    "waiting_document",
    "waiting_page",
    "waiting_root",
    "waiting_account_form",
    "waiting_account_editable",
    "waiting_account_stable",
    "requesting_username",
    "filling_username",
    "waiting_next_button",
    "waiting_password_form",
    "requesting_password",
    "filling_password",
    "waiting_signin_button",
    "verifying_sign_in",
    "submitted",
    "timeout",
    "stopped",
    "cancelled",
    "signed_in",
    "rejected",
  ],
  terminalPhases: [
    "submitted",
    "timeout",
    "stopped",
    "cancelled",
    "signed_in",
    "rejected",
  ],
  reasons: [
    "not-started",
    "document-loading",
    "form-settling",
    "input-settling",
    "next-not-advanced",
    "root-missing",
    "root-ambiguous",
    "form-missing",
    "form-ambiguous",
    "field-missing",
    "field-ambiguous",
    "button-missing",
    "button-ambiguous",
    "field-hidden",
    "field-disabled",
    "field-readonly",
    "button-hidden",
    "button-disabled",
    "panel-transition",
    "password-route",
    "requesting-username",
    "requesting-password",
    "submitted",
    "timeout",
    "stopped",
    "cancelled",
    "form-changed",
    "route-changed",
    "captcha",
    "credentials-unavailable",
    "invalid-credential-response",
    "route-pending",
    "page-busy",
    "controls-replaced",
    "value-refilled",
    "panel-quiet-wait",
    "next-reclicked",
    "captcha-required",
    "interactive-step-required",
    "user-input-detected",
    "unsafe-form-target",
    "account-mismatch",
    "left-login-page",
    "layout-unrecognized",
    "unsupported-login-path",
    "page-never-ready",
    "login-form-never-appeared",
    "password-panel-never-appeared",
    "signin-button-never-enabled",
    "left-signin-page",
    "error-visible",
    "sign-in-unconfirmed",
    "no-sign-in-page",
  ],
  // Generated by the bridge when it limits noisy reports; never page-supplied.
  bridgeGeneratedReasons: ["observation-limited"],
  // detail.trace = {steps, fingerprint: {counts, hash, readyState, stage},
  // handoff}, agreed with t85-e1; getTrace() returns the same shape.
  counts: ["root", "panel", "form", "field", "button"],
  hashes: [
    "empty",
    "slash",
    "signin",
    "password",
    "otp",
    "approve",
    "select-auth",
    "passkey",
    "other",
  ],
  readyStates: ["loading", "interactive", "complete"],
  stages: ["account", "password", "submitted"],
  handoffs: ["otp", "approve", "select-auth", "passkey", "other"],
};
const TRACE_LISTS = [
  "counts",
  "hashes",
  "readyStates",
  "stages",
  "handoffs",
] as const;
// Snake-case literals in the helper that are event names, not phases.
const NON_PHASE_SNAKE_LITERALS = ["sorng_synology_login_progress"];

const sorted = (values: Iterable<string>) => [...new Set(values)].sort();

/* Minimal ES5 source scanner: strings, comments, regex literals, brackets. */
function regexAllowed(text: string, index: number) {
  let cursor = index - 1;
  while (cursor >= 0 && /\s/.test(text[cursor])) cursor--;
  if (cursor < 0 || "(,=:[!&|?{};+-*%<>~^".includes(text[cursor])) return true;
  return /\b(?:return|typeof|case|in|of|void|delete)$/.test(
    text.slice(Math.max(0, cursor - 7), cursor + 1),
  );
}
/** Index after a string, comment or regex literal starting at `index`, else `index`. */
function skipLiteral(text: string, index: number): number {
  const char = text[index];
  if (char === '"' || char === "'" || char === "`") {
    for (let cursor = index + 1; cursor < text.length; cursor++) {
      if (text[cursor] === "\\") cursor++;
      else if (text[cursor] === char) return cursor + 1;
    }
    return text.length;
  }
  if (char !== "/") return index;
  if (text[index + 1] === "/") {
    const end = text.indexOf("\n", index);
    return end < 0 ? text.length : end;
  }
  if (text[index + 1] === "*") {
    const end = text.indexOf("*/", index + 2);
    return end < 0 ? text.length : end + 2;
  }
  if (!regexAllowed(text, index)) return index;
  let inClass = false;
  for (let cursor = index + 1; cursor < text.length; cursor++) {
    const next = text[cursor];
    if (next === "\\") cursor++;
    else if (next === "\n") return index;
    else if (next === "[") inClass = true;
    else if (next === "]") inClass = false;
    else if (next === "/" && !inClass) return cursor + 1;
  }
  return index;
}
const PAIRS: Record<string, string> = { "(": ")", "[": "]", "{": "}" };
/** Index of the bracket that closes the one at `open`. */
function closing(text: string, open: number): number {
  const stack = [PAIRS[text[open]]];
  for (let cursor = open + 1; cursor < text.length;) {
    const next = skipLiteral(text, cursor);
    if (next !== cursor) {
      cursor = next;
      continue;
    }
    const char = text[cursor];
    if (PAIRS[char]) stack.push(PAIRS[char]);
    else if (char === stack[stack.length - 1]) {
      stack.pop();
      if (!stack.length) return cursor;
    }
    cursor++;
  }
  return -1;
}
/** Splits at top-level commas; stops at an unbalanced closer or a top-level `;`. */
function splitTopLevel(text: string, stopAtSemicolon = false): string[] {
  const parts: string[] = [];
  let depth = 0,
    start = 0;
  for (let cursor = 0; cursor < text.length;) {
    const next = skipLiteral(text, cursor);
    if (next !== cursor) {
      cursor = next;
      continue;
    }
    const char = text[cursor];
    if (PAIRS[char]) depth++;
    else if (")]}".includes(char)) {
      if (depth === 0) return [...parts, text.slice(start, cursor)];
      depth--;
    } else if (depth === 0 && char === ",") {
      parts.push(text.slice(start, cursor));
      start = cursor + 1;
    } else if (depth === 0 && char === ";" && stopAtSemicolon)
      return [...parts, text.slice(start, cursor)];
    cursor++;
  }
  return [...parts, text.slice(start)];
}
const QUOTED = String.raw`(?:"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*')`;
const literals = (text: string) =>
  [...text.matchAll(new RegExp(QUOTED, "g"))].map((match) =>
    match[0].slice(1, -1),
  );
const NOT_CALLS = new Set([
  "if",
  "for",
  "while",
  "switch",
  "catch",
  "function",
  "return",
  "typeof",
  "void",
  "in",
  "of",
]);
/** Replaces every call's argument list with `()`, keeping grouping parentheses. */
function stripCallArguments(text: string): string {
  let result = "";
  for (let cursor = 0; cursor < text.length;) {
    const next = skipLiteral(text, cursor);
    if (next !== cursor) {
      result += text.slice(cursor, next);
      cursor = next;
      continue;
    }
    if (text[cursor] === "(") {
      const before = result.replace(/\s+$/, "");
      const word = /[A-Za-z_$][\w$]*$/.exec(before)?.[0];
      const close = closing(text, cursor);
      if (
        close > cursor &&
        ((word && !NOT_CALLS.has(word)) || /[)\]]$/.test(before))
      ) {
        result += "()";
        cursor = close + 1;
        continue;
      }
    }
    result += text[cursor++];
  }
  return result;
}
// Call arguments and literals compared against are not the value an
// expression produces, so they are removed before collecting values.
const valueExpression = (text: string) =>
  stripCallArguments(text)
    .replace(
      new RegExp(String.raw`[\w$.\])]+\s*(?:===|!==|==|!=)\s*${QUOTED}`, "g"),
      " ",
    )
    .replace(
      new RegExp(String.raw`${QUOTED}\s*(?:===|!==|==|!=)\s*[\w$.]+`, "g"),
      " ",
    );
const KEYWORDS = new Set([
  "true",
  "false",
  "null",
  "undefined",
  "this",
  "typeof",
  "void",
  "new",
  "in",
  "instanceof",
  "return",
  "var",
  "function",
  "delete",
]);
interface Reference {
  name: string;
  member: boolean;
  call: boolean;
}
/** Plain identifiers, the last property of member chains, and called names. */
function references(text: string): Reference[] {
  const code = text.replace(new RegExp(QUOTED, "g"), " ");
  return [
    ...code.matchAll(
      /(?<![\w$.])([A-Za-z_$][\w$]*)((?:\s*\.\s*[A-Za-z_$][\w$]*)*)(\s*\()?/g,
    ),
  ].flatMap((match) => {
    const members = match[2]
      .split(".")
      .map((part) => part.trim())
      .filter(Boolean);
    const name = members.length ? members[members.length - 1] : match[1];
    if (!members.length && KEYWORDS.has(name)) return [];
    return [{ name, member: members.length > 0, call: !!match[3] }];
  });
}

interface Definition {
  name: string;
  params: string[];
  open: number;
  close: number;
}
function definitions(text: string): Definition[] {
  return [
    ...text.matchAll(/function\s+([A-Za-z_$][\w$]*)\s*\(([^)]*)\)\s*\{/g),
  ].map((match) => {
    const open = match.index! + match[0].length - 1;
    return {
      name: match[1],
      params: match[2]
        .split(",")
        .map((param) => param.trim())
        .filter(Boolean),
      open,
      close: closing(text, open),
    };
  });
}
function calls(text: string, name: string) {
  const pattern = new RegExp(String.raw`(?<![\w$.])${name}\s*\(`, "g");
  return [...text.matchAll(pattern)].flatMap((match) => {
    const before = text.slice(Math.max(0, match.index! - 12), match.index);
    if (/function\s+$/.test(before)) return [];
    const open = match.index! + match[0].length - 1;
    const close = closing(text, open);
    return close > open
      ? [
          {
            offset: match.index!,
            args: splitTopLevel(text.slice(open + 1, close)),
          },
        ]
      : [];
  });
}
interface Source {
  expression: string;
  offset: number;
}
/** Right-hand sides matched by `pattern` within [from, to). */
function rightHandSides(
  text: string,
  pattern: RegExp,
  from = 0,
  to = text.length,
  stopAtSemicolon = true,
): Source[] {
  return [...text.slice(from, to).matchAll(pattern)].map((match) => {
    const offset = from + match.index! + match[0].length;
    return {
      expression: splitTopLevel(text.slice(offset), stopAtSemicolon)[0],
      offset,
    };
  });
}
const assignmentPattern = (name: string) =>
  new RegExp(String.raw`(?<![\w$.])${name}\s*=(?!=)`, "g");

type Kind = "phase" | "reason";
interface Slot {
  kind: Kind;
  suffixes: string[];
}
// Single-word values in the contract; other values must be snake or kebab case.
const SINGLE_WORD = {
  phase: CONTRACT.phases.filter((value) => !value.includes("_")),
  reason: CONTRACT.reasons.filter((value) => !value.includes("-")),
};
const SHAPE = {
  phase: /^[a-z]+(?:_[a-z]+)+$/,
  reason: /^[a-z]+(?:-[a-z]+)+$/,
};
/**
 * Status values flow into `publish(phase, reason)`, `reject(reason)` and
 * `failureReason = reason`. A function forwarding its own parameter into one
 * of those becomes a sink too. Values are then followed through local
 * assignments (nearest enclosing function first), object properties
 * (`found.missing`), function return values and generated `-suffix` names.
 */
function extractHelperVocabulary(text: string) {
  const defs = definitions(text);
  const chain = (offset: number) =>
    defs
      .filter((def) => def.open < offset && offset < def.close)
      .sort((left, right) => right.open - left.open);
  const sinks = new Map<string, Map<number, Slot>>([
    [
      "publish",
      new Map([
        [0, { kind: "phase", suffixes: [] }],
        [1, { kind: "reason", suffixes: [] }],
      ]),
    ],
    ["reject", new Map([[0, { kind: "reason", suffixes: [] }]])],
  ]);
  for (let round = 0, grew = true; grew && round < 8; round++) {
    grew = false;
    for (const [sink, slots] of [...sinks])
      for (const call of calls(text, sink))
        for (const [index, slot] of slots) {
          const expression = valueExpression(call.args[index] ?? "");
          const suffixes = literals(expression).filter((value) =>
            value.startsWith("-"),
          );
          for (const reference of references(expression)) {
            if (reference.member || reference.call) continue;
            const owner = chain(call.offset).find((def) =>
              def.params.includes(reference.name),
            );
            if (!owner || owner.name === sink) continue;
            const wrapper = sinks.get(owner.name) ?? new Map<number, Slot>();
            const param = owner.params.indexOf(reference.name);
            if (wrapper.has(param)) continue;
            wrapper.set(param, {
              kind: slot.kind,
              suffixes: suffixes.length ? suffixes : slot.suffixes,
            });
            sinks.set(owner.name, wrapper);
            grew = true;
          }
        }
  }
  const found = { phase: new Set<string>(), reason: new Set<string>() };
  const visited = new Set<string>();
  function resolve(
    expression: string,
    offset: number,
    kind: Kind,
    inherited: string[],
    depth = 0,
  ) {
    if (depth > 8) return;
    const value = valueExpression(expression);
    const values = literals(value);
    const own = values.filter((literal) => literal.startsWith("-"));
    const suffixes = own.length ? own : inherited;
    for (const literal of values) {
      if (literal.startsWith("-")) continue;
      for (const candidate of suffixes.length
        ? suffixes.map((suffix) => literal + suffix)
        : [literal])
        if (
          SHAPE[kind].test(candidate) ||
          SINGLE_WORD[kind].includes(candidate)
        )
          found[kind].add(candidate);
    }
    const enclosing = chain(offset);
    for (const reference of references(value)) {
      let sources: Source[] = [];
      let scope = "";
      if (reference.member) {
        if (reference.call) continue;
        sources = [
          ...rightHandSides(
            text,
            new RegExp(String.raw`[{,]\s*${reference.name}\s*:(?!:)`, "g"),
            0,
            text.length,
            false,
          ),
          ...rightHandSides(
            text,
            new RegExp(String.raw`\.\s*${reference.name}\s*=(?!=)`, "g"),
          ),
        ];
        scope = ".";
      } else if (reference.call) {
        sources = defs
          .filter((def) => def.name === reference.name)
          .flatMap((def) =>
            rightHandSides(text, /(?<![\w$.])return\b/g, def.open, def.close),
          );
        scope = "()";
      } else {
        if (enclosing.some((def) => def.params.includes(reference.name)))
          continue;
        const pattern = assignmentPattern(reference.name);
        for (const def of enclosing) {
          sources = rightHandSides(text, pattern, def.open, def.close);
          scope = String(def.open);
          if (sources.length) break;
        }
        if (!sources.length) {
          sources = rightHandSides(text, pattern);
          scope = "global";
        }
      }
      const key = `${kind}|${suffixes.join()}|${scope}|${reference.name}`;
      if (visited.has(key)) continue;
      visited.add(key);
      for (const source of sources)
        resolve(source.expression, source.offset, kind, suffixes, depth + 1);
    }
  }
  for (const source of rightHandSides(text, assignmentPattern("failureReason")))
    resolve(source.expression, source.offset, "reason", []);
  for (const [sink, slots] of sinks)
    for (const call of calls(text, sink))
      for (const [index, slot] of slots)
        resolve(call.args[index] ?? "", call.offset, slot.kind, slot.suffixes);
  return { phases: sorted(found.phase), reasons: sorted(found.reason) };
}
function bridgeList(name: string): string[] {
  const match = new RegExp(String.raw`var ${name} = \[([^\]]*)\]`).exec(bridge);
  if (!match) throw new Error(`bridge list ${name} not found`);
  return literals(match[1]);
}

/* Behavioural harness for the actual bridge. */
let messages: MockInstance<(message: unknown, targetOrigin: string) => void>;
function installBridge() {
  (window as unknown as { fixtureIdentity: unknown }).fixtureIdentity = {
    sessionId: "proxy-a",
    documentToken: "a".repeat(32),
    documentSequence: 2,
    navigationToken: "b".repeat(32),
  };
  window.eval(`(function(){var p=window.fixtureIdentity;${bridge}\n})();`);
}
const closeBridge = () => window.dispatchEvent(new Event("pagehide"));
function bridgeForwards(detail: unknown) {
  installBridge();
  const before = messages.mock.calls.length;
  document.dispatchEvent(
    new CustomEvent("sorng_synology_login_progress", { detail }),
  );
  closeBridge();
  return messages.mock.calls.length === before + 1;
}
const posted = () =>
  messages.mock.calls
    .map(([message]) => message as Record<string, unknown>)
    .filter((message) => message.type === "proxy_synology_login_progress");
beforeEach(() => {
  messages = vi.spyOn(window, "postMessage").mockImplementation(() => {});
});
afterEach(() => {
  closeBridge();
  Reflect.deleteProperty(window, "__sorng_synology_login");
  Reflect.deleteProperty(window, "fixtureIdentity");
  document.body.innerHTML = "";
  vi.clearAllTimers();
  vi.useRealTimers();
  vi.restoreAllMocks();
});

const extracted = extractHelperVocabulary(helper);

describe("Synology page-helper status vocabulary parity", () => {
  it("finds the helper's status literals instead of passing vacuously", () => {
    expect(extracted.phases).toEqual(
      expect.arrayContaining(["waiting_document", "cancelled", "waiting_root"]),
    );
    expect(extracted.reasons).toEqual(
      expect.arrayContaining(["not-started", "cancelled", "root-missing"]),
    );
    expect(extracted.phases.length).toBeGreaterThanOrEqual(8);
    expect(extracted.reasons.length).toBeGreaterThanOrEqual(15);
  });
  it("follows publish wrappers, local assignments, object properties, return values and generated suffixes", () => {
    const sample = `
      function publish(phase, reason, terminal) {}
      function run(data) {
        var phase = "account", failureReason = "stopped";
        function reject(reason) { failureReason = reason; throw 1; }
        function unique(selector, phase, part) {
          publish(phase, part + (count ? "-ambiguous" : "-missing"));
        }
        function editable(target) {
          var reason = target.matches(":disabled") ? "sample-disabled" : null;
          if (reason) publish(phase === "account-button" ? "sample_phase" : "other_phase", reason);
        }
        function settle(target, stage, publicPhase, why) { publish(publicPhase, why); }
        function finish(ok, reason) {
          if (!ok && failureReason === "timeout") reason = "reviewed-login-timeout";
          publish(ok ? "submitted" : reason === "x-y" ? "timeout" : "stopped", reason === "x-y" ? "sample-x" : failureReason, true);
        }
        unique("#root", "sample_root", "root");
        settle(a, "account-readiness", "sample_stable", "sample-settling");
        failureReason = "sample-stop";
        reject("sample-rejected");
        Promise.reject(new Error("not-a-status"));
        var pattern = /^[0-9a-f]{32}$/;
        phase = "fetching-account";
        var CONTROLS = { account: { form: "form#user", waiting: "table_phase" } };
        function locate(side) {
          var found = { waiting: "found_phase", missing: null, stage: "password-fetch" };
          var part = count ? ["field", 1] : ["button", 0];
          if (count) found.missing = part[0] + (part[1] ? "-ambiguous" : "-missing");
          else found.missing = count > 1 ? "found-plain" : "found-other";
          found.waiting = CONTROLS[side].waiting;
          return found;
        }
        function capReason(kind) {
          return kind === "password" ? "cap-password" : "cap-account";
        }
        var located = locate("account");
        publish(located.waiting, located.missing);
        settle(b, "stage", "sample_stable", capReason("password"));
        publish("helper_phase", describe(stage));
      }
      function describe(stage) { return stage === "x" ? "described-x" : "described-y"; }
    `;
    expect(extractHelperVocabulary(sample)).toEqual({
      phases: sorted([
        "sample_phase",
        "other_phase",
        "sample_root",
        "sample_stable",
        "submitted",
        "timeout",
        "stopped",
        "table_phase",
        "found_phase",
        "helper_phase",
      ]),
      reasons: sorted([
        "root-ambiguous",
        "root-missing",
        "sample-disabled",
        "sample-settling",
        "sample-stop",
        "sample-rejected",
        "sample-x",
        "stopped",
        "field-ambiguous",
        "field-missing",
        "button-ambiguous",
        "button-missing",
        "found-plain",
        "found-other",
        "cap-password",
        "cap-account",
        "described-x",
        "described-y",
      ]),
    });
  });
  it("keeps the bridge lists identical to the fixed contract", () => {
    expect(bridgeList("phases")).toEqual(CONTRACT.phases);
    expect(bridgeList("finishing")).toEqual(CONTRACT.terminalPhases);
    expect(bridgeList("reasons")).toEqual(CONTRACT.reasons);
    for (const list of TRACE_LISTS)
      expect(bridgeList(list)).toEqual(CONTRACT[list]);
  });
  it("keeps the hook vocabulary identical to the fixed contract", () => {
    expect(sorted(hook.phases)).toEqual(sorted(CONTRACT.phases));
    expect(sorted(hook.terminalPhases)).toEqual(
      sorted(CONTRACT.terminalPhases),
    );
    expect(sorted(hook.reasons)).toEqual(
      sorted([...CONTRACT.reasons, ...CONTRACT.bridgeGeneratedReasons]),
    );
    for (const list of TRACE_LISTS)
      expect([...hook[list]]).toEqual(CONTRACT[list]);
  });
  it("accepts every phase the helper can publish in both the bridge and the hook", () => {
    const refusedByBridge = extracted.phases.filter(
      (phase) => !bridgeForwards({ phase, reason: "not-started" }),
    );
    const refusedByHook = extracted.phases.filter(
      (phase) => !parseSynologyLoginProgress({ phase, reason: "not-started" }),
    );
    expect({ refusedByBridge, refusedByHook }).toEqual({
      refusedByBridge: [],
      refusedByHook: [],
    });
  });
  it("accepts every reason the helper can publish in both the bridge and the hook", () => {
    const refusedByBridge = extracted.reasons.filter(
      (reason) => !bridgeForwards({ phase: "waiting_root", reason }),
    );
    const refusedByHook = extracted.reasons.filter(
      (reason) =>
        !parseSynologyLoginProgress({ phase: "waiting_root", reason }),
    );
    expect({ refusedByBridge, refusedByHook }).toEqual({
      refusedByBridge: [],
      refusedByHook: [],
    });
  });
  it("treats every other snake-case helper literal as an accepted phase", () => {
    const phases: readonly string[] = hook.phases;
    expect(
      sorted(
        literals(helper).filter(
          (value) =>
            SHAPE.phase.test(value) &&
            !NON_PHASE_SNAKE_LITERALS.includes(value) &&
            !(CONTRACT.phases.includes(value) && phases.includes(value)),
        ),
      ),
    ).toEqual([]);
  });
  it("records every phase, and names every non-wait reason, in the Action Log", () => {
    const context = {
      sessionId: "session-a",
      connectionId: "connection-a",
      databaseId: "db-a",
    };
    const unlogged = CONTRACT.phases.filter((phase) => {
      clearSessionActivityLog();
      recordSessionActivity(context, "autofill", phase as SessionActivityCode);
      return getSessionActivityLog().length !== 1;
    });
    const waits = new Set([
      "not-started",
      "document-loading",
      "root-missing",
      "root-ambiguous",
      "form-missing",
      "form-ambiguous",
      "field-missing",
      "field-ambiguous",
      "button-missing",
      "button-ambiguous",
      "password-route",
      "requesting-username",
      "requesting-password",
      // Generic reasons repeat the phase summary.
      "submitted",
      "timeout",
      "stopped",
      "cancelled",
    ]);
    const unexplained = CONTRACT.reasons.filter((reason) => {
      if (waits.has(reason)) return false;
      clearSessionActivityLog();
      recordSessionActivity(context, "autofill", "stopped", { reason });
      return (
        getSessionActivityLog()[0]?.details ===
        "Page helper stopped before completing submission."
      );
    });
    clearSessionActivityLog();
    expect({ unlogged, unexplained }).toEqual({
      unlogged: [],
      unexplained: [],
    });
  });
  it("never lets the page supply the bridge-generated limit notice", () => {
    expect(
      bridgeForwards({ phase: "waiting_root", reason: "observation-limited" }),
    ).toBe(false);
  });
});

type Published = { phase: string; reason: string; trace: unknown };
type HelperApi = {
  runWhenReady(nonce: string, helpers: unknown): Promise<unknown>;
  cancel(): void;
};
async function runHelperThroughBridge() {
  vi.useFakeTimers();
  history.replaceState(null, "", "/");
  const published: Published[] = [];
  const collect = (event: Event) => {
    const { phase, reason, trace } = (event as CustomEvent).detail;
    published.push({
      phase,
      reason,
      trace:
        trace === undefined ? undefined : JSON.parse(JSON.stringify(trace)),
    });
  };
  document.addEventListener("sorng_synology_login_progress", collect);
  installBridge();
  window.eval(helper);
  const api = (window as unknown as { __sorng_synology_login: HelperApi })
    .__sorng_synology_login;
  try {
    const running = api.runWhenReady("c".repeat(32), {
      fillField: vi.fn(),
      isVisible: () => true,
      report: vi.fn(),
    });
    await vi.advanceTimersByTimeAsync(1500);
    api.cancel();
    await vi.advanceTimersByTimeAsync(0);
    await running;
  } finally {
    document.removeEventListener("sorng_synology_login_progress", collect);
    window.removeEventListener("pagehide", api.cancel);
    window.removeEventListener("unload", api.cancel);
  }
  // The helper and the bridge both suppress a repeated phase:reason pair.
  return published.filter(
    (report, index) =>
      index === 0 ||
      `${report.phase}:${report.reason}` !==
        `${published[index - 1].phase}:${published[index - 1].reason}`,
  );
}
/** What the bridge must forward for a helper trace that meets the contract. */
function forwardedTrace(raw: Record<string, unknown>) {
  const expected: Record<string, unknown> = {};
  const steps = raw.steps as unknown[];
  if (steps.length) expected.steps = steps.slice(-8);
  const fingerprint = Object.fromEntries(
    Object.entries(raw.fingerprint as Record<string, unknown>).map(
      ([key, value]) => [
        key,
        typeof value === "number" ? Math.min(value, 9) : value,
      ],
    ),
  );
  if (Object.keys(fingerprint).length) expected.fingerprint = fingerprint;
  if (raw.handoff !== null) expected.handoff = raw.handoff;
  return Object.keys(expected).length ? expected : undefined;
}
const tracedHelper = /\btrace:\s*traceCopy\(\)|detail:\s*\{[^}]*\btrace\b/.test(
  helper,
);

describe("actual helper to bridge delivery", () => {
  it("forwards every phase and reason the running helper publishes", async () => {
    const published = await runHelperThroughBridge();
    expect(published.length).toBeGreaterThanOrEqual(2);
    expect(published[published.length - 1]).toMatchObject({
      phase: "cancelled",
      reason: "cancelled",
    });
    expect(
      posted().map((message) => `${message.phase}:${message.reason}`),
    ).toEqual(published.map((report) => `${report.phase}:${report.reason}`));
  });
  it.skipIf(!tracedHelper)(
    "publishes only closed trace fields and the bridge forwards all of them",
    async () => {
      const published = await runHelperThroughBridge();
      const messages = posted();
      expect(messages).toHaveLength(published.length);
      published.forEach((report, index) => {
        const raw = report.trace as Record<string, unknown>;
        expect(raw).toBeTypeOf("object");
        expect(
          Object.keys(raw).filter(
            (key) => !["steps", "fingerprint", "handoff"].includes(key),
          ),
        ).toEqual([]);
        const steps = raw.steps as Record<string, unknown>[];
        expect(Array.isArray(steps) && steps.length <= 40).toBe(true);
        for (const step of steps) {
          expect(sorted(Object.keys(step))).toEqual(["phase", "reason", "t"]);
          expect(Number.isInteger(step.t) && Number(step.t) >= 0).toBe(true);
          expect(CONTRACT.phases).toContain(step.phase);
          expect(CONTRACT.reasons).toContain(step.reason);
        }
        const fingerprint = raw.fingerprint as Record<string, unknown>;
        for (const [key, value] of Object.entries(fingerprint)) {
          if (key === "hash") expect(CONTRACT.hashes).toContain(value);
          else if (key === "readyState")
            expect(CONTRACT.readyStates).toContain(value);
          else if (key === "stage") expect(CONTRACT.stages).toContain(value);
          else {
            expect(CONTRACT.counts).toContain(key);
            expect(
              Number.isInteger(value) &&
                Number(value) >= 0 &&
                Number(value) <= 9,
            ).toBe(true);
          }
        }
        if (raw.handoff !== null) {
          expect(CONTRACT.handoffs).toContain(raw.handoff);
          expect([report.phase, report.reason]).toEqual([
            "stopped",
            "interactive-step-required",
          ]);
        }
        expect(messages[index].trace).toEqual(forwardedTrace(raw));
      });
    },
  );
});
