use std::sync::Mutex as StdMutex;
use std::collections::HashMap;

pub mod types;
pub mod service;
pub mod commands;
pub mod recording;
pub mod automation;
pub mod tunnels;
pub mod diagnostics;

// Maximum buffer size in bytes (1MB)
pub(crate) const MAX_BUFFER_SIZE: usize = 1024 * 1024;

// Global terminal buffer storage
lazy_static::lazy_static! {
    pub(crate) static ref TERMINAL_BUFFERS: StdMutex<HashMap<String, String>> = StdMutex::new(HashMap::new());
}

// Global storage for active recordings
lazy_static::lazy_static! {
    pub(crate) static ref ACTIVE_RECORDINGS: StdMutex<HashMap<String, types::RecordingState>> = StdMutex::new(HashMap::new());
}

// Global storage for active automations
lazy_static::lazy_static! {
    pub(crate) static ref ACTIVE_AUTOMATIONS: StdMutex<HashMap<String, types::AutomationState>> = StdMutex::new(HashMap::new());
}

// Global storage for active FTP tunnels
lazy_static::lazy_static! {
    pub static ref FTP_TUNNELS: StdMutex<HashMap<String, types::FtpTunnelStatus>> = StdMutex::new(HashMap::new());
}

// Global storage for active RDP tunnels
lazy_static::lazy_static! {
    pub static ref RDP_TUNNELS: StdMutex<HashMap<String, types::RdpTunnelStatus>> = StdMutex::new(HashMap::new());
}

// Global storage for active VNC tunnels
lazy_static::lazy_static! {
    pub static ref VNC_TUNNELS: StdMutex<HashMap<String, types::VncTunnelStatus>> = StdMutex::new(HashMap::new());
}

// Re-export everything so that `use crate::ssh::*` still works.
// Using glob re-exports to include the hidden `__cmd__` items generated by #[tauri::command].

// All types
pub use types::*;

// Service struct and helpers
pub use service::SshService;
#[allow(unused_imports)]
pub use service::generate_totp_code;

// All tauri commands (glob re-exports include __cmd__ items)
pub use commands::*;
pub use recording::*;
pub use automation::*;
pub use tunnels::*;
pub use diagnostics::*;
