use std::collections::HashMap;
use std::sync::Mutex as StdMutex;

pub mod automation;
pub mod commands;
pub mod diagnostics;
pub mod fido2;
pub mod highlighting;
pub mod proxy_command;
pub mod recording;
pub mod service;
pub mod sk_keys;
pub mod tunnels;
pub mod types;
pub mod x11;

// Maximum buffer size in bytes (1MB)
pub(crate) const MAX_BUFFER_SIZE: usize = 1024 * 1024;

// Global terminal buffer storage
lazy_static::lazy_static! {
    pub(crate) static ref TERMINAL_BUFFERS: StdMutex<HashMap<String, String>> = StdMutex::new(HashMap::new());
}

// Global storage for active recordings
lazy_static::lazy_static! {
    pub(crate) static ref ACTIVE_RECORDINGS: StdMutex<HashMap<String, types::RecordingState>> = StdMutex::new(HashMap::new());
}

// Global storage for active automations
lazy_static::lazy_static! {
    pub(crate) static ref ACTIVE_AUTOMATIONS: StdMutex<HashMap<String, types::AutomationState>> = StdMutex::new(HashMap::new());
}

// Global storage for active highlight rule-sets (per session)
lazy_static::lazy_static! {
    pub(crate) static ref ACTIVE_HIGHLIGHTS: StdMutex<HashMap<String, types::HighlightState>> = StdMutex::new(HashMap::new());
}

// Global storage for active FTP tunnels
lazy_static::lazy_static! {
    pub static ref FTP_TUNNELS: StdMutex<HashMap<String, types::FtpTunnelStatus>> = StdMutex::new(HashMap::new());
}

// Global storage for active RDP tunnels
lazy_static::lazy_static! {
    pub static ref RDP_TUNNELS: StdMutex<HashMap<String, types::RdpTunnelStatus>> = StdMutex::new(HashMap::new());
}

// Global storage for active VNC tunnels
lazy_static::lazy_static! {
    pub static ref VNC_TUNNELS: StdMutex<HashMap<String, types::VncTunnelStatus>> = StdMutex::new(HashMap::new());
}

// Re-export everything so that `use crate::ssh::*` still works.
// Using glob re-exports to include the hidden `__cmd__` items generated by #[tauri::command].

// All types
pub use types::*;

// Service struct and helpers
#[allow(unused_imports)]
pub use service::generate_totp_code;
pub use service::SshService;

// All tauri commands (glob re-exports include __cmd__ items)
pub use automation::*;
pub use commands::*;
pub use diagnostics::*;
pub use fido2::*;
pub use highlighting::*;
pub use proxy_command::*;
pub use recording::*;
pub use sk_keys::*;
pub use tunnels::*;
pub use x11::*;
